### ISSUE TITLE
[Feature request] Allow overriding docker-compose.yml

### ISSUE THREAD

**Issue by DevilaN** [AbdBarho/stable-diffusion-webui-docker#101]
Docker compose allows using `docker-compose.override.yml` file for storing changes to service definitions in base `docker-compose.yml` file.
Having this allow us to continue using unmodified `docker-compose.yml` file in local copy of repository and do not bother about conflicts / not updating file when doing `git pull` on regular basis, as specific modifications are being made in `docker-compose.override.yml` file that should be not managed by git. Therefore it would be perfect if `docker-compose.override.yml` file was added to `.gitignore` so it will not pop up during `git status` command as untracked.
Also it would be nice if there was example override file distributed inside repository (`docker-compose.override.yml-dist` file) as a starter point for anybody who might want to set extra environment variables and other service tweaks without worrying about creating entire file from scratch.

I suppose, that this method should be described in README / wiki in setup & usage sections (as this is a good method to add / change CLI arguments for specific service.

**Comment by AbdBarho** [comment]
I totally agree with the benefit of `docker-compose.override.yml` and we should include it in the `.gitignore`.

I propose we document the override file in the wiki with a couple of examples, but not in the repo.

#100
