### ISSUE TITLE
How do I make this work in an Azure container?

### ISSUE THREAD

**Issue by Sam7** [AbdBarho/stable-diffusion-webui-docker#107]
I'd like to run this in Azure containers:
https://learn.microsoft.com/en-us/azure/container-instances/container-instances-gpu

But when I do that using these commands:

	az login
	az account set --subscription xxxxxxx
	docker context use AciContext
	docker compose --profile download up --build
	docker compose --profile auto up --build

Nothing happens.
Does anyone have experience with this?

**Comment by rgriffogoes** [comment]
Do you get any error messages? are you able to run other docker images?

`sudo docker run hello-world`

Or even nvidia hello world:

`sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`
