### ISSUE TITLE
Can't run Stable Diffusion

### ISSUE THREAD

**Issue by Can232** [AbdBarho/stable-diffusion-webui-docker#109]
Tried setting it up manually too but it just won't work. Here's the error it shows:
![Error](https://user-images.githubusercontent.com/114813456/193409921-d7d0e349-d5b6-4325-9a92-08a606bd4270.JPG)

**Comment by AbdBarho** [comment]
@Can232 please use the bug template next time.

Do you have the latest nvidia drivers? and wsl2? 

what is the output of this command?
```
docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
```


Also, check FAQ: https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ#other-build-errors-on-windows

**Comment by Can232** [comment]
I updated the Nvidia drivers and it still doesn't work. Here's a screenshot of the output.
![Error2](https://user-images.githubusercontent.com/114813456/193414868-b68b270f-141b-4b50-ab4d-89e1f782e3a2.JPG)

**Comment by AbdBarho** [comment]
what are the outputs of these commands?
```
docker version
docker compose version
wsl -l -v
```

**Comment by Can232** [comment]
![Error3](https://user-images.githubusercontent.com/114813456/193415502-9620a059-5c8f-427f-89ac-8f708a361a50.JPG)
![Error4](https://user-images.githubusercontent.com/114813456/193415504-9e57f5c9-1ec0-47ac-82b2-c7379bf547ce.JPG)
![Error5](https://user-images.githubusercontent.com/114813456/193415507-7215c752-5c7b-45a6-a6af-b3903c540517.JPG)

**Comment by AbdBarho** [comment]
all seems fine until now

and this one?
```
winver 
```

**Comment by Can232** [comment]
It didn't let me update for like a year now and won't even let me delete the previous version. No idea what to do without losing a year of downloads.
![WinVersion](https://user-images.githubusercontent.com/114813456/193415883-b354eae3-8b4b-4762-8c8e-89d7321ff07b.JPG)

**Comment by AbdBarho** [comment]
I think this is the problem, GPU support for WSL2 was added in windows 21H2, without it the container cannot access the GPU.

Either update windows, or, run on the cpu with
```
docker compose --profile auto-cpu up --build
```

**Comment by Can232** [comment]
it found no nvidia driver lmao
