### ISSUE TITLE
facexlib version conflict: gfpgan 1.3.4 depends on facexlib>=0.2.5

### ISSUE THREAD

**Issue by timbennett** [AbdBarho/stable-diffusion-webui-docker#11]
I received this error when building the repo a few minutes ago. Another user has explored it in more detail here: https://github.com/hlky/stable-diffusion/issues/169

**Comment by AbdBarho** [comment]
Related https://github.com/hlky/stable-diffusion-webui/issues/360

**Comment by AbdBarho** [comment]
@timbennett the problem should be fixed, I have rebuilt the container from scratch using latest commit and it worked fine, I have released `0.0.13`, can you give it a try?

**Comment by timbennett** [comment]
Thanks, it has built correctly now. No further issues.
