### ISSUE TITLE
Absolute path in `scripts/migratev1tov2.sh` to `/data/embeddings` fails to run

### ISSUE THREAD

**Issue by tokengeek** [AbdBarho/stable-diffusion-webui-docker#110]
**Describe the bug**
An absolute path is used rather than a relevant path in the new migration script for `/data/embeddings`. This reports an error if the user is unable to write to the root directory, or if they are would put the embedding in a different location to the other, relatively located files.

https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/14c4b36affa4535dd58012574e39e227c2b3d603/scripts/migratev1tov2.sh#L1

**Steps to Reproduce**
1. Attempt to run `bash scripts/migratev1tov2.sh`
2. See error

```
> bash scripts/migratev1tov2.sh
mkdir: cannot create directory ‘/data’: Permission denied
```

**Hardware / Software:**
 - OS: NixOS 22.05

**Additional context**
Things seem to run to completion if the `mkdir` is changed to `data/embeddings` except for a final:

```
cp: cannot stat 'embeddings/*': No such file or directory
this script was created 10/2022
Dont forget to run: docker compose --profile download up --build
the cache and embeddings folders can be deleted, but its not necessary.
```

I didn't have any embeddings beforehand but the `auto` profile is back up and working following a migration.

**Comment by AbdBarho** [comment]
damn typo!

**Comment by tokengeek** [comment]
Thanks!
