### ISSUE TITLE
Download fails with error on chmod call (dirs don't exist) - Fix included

### ISSUE THREAD

**Issue by eriknomitch** [AbdBarho/stable-diffusion-webui-docker#112]
**Has this issue been opened before? Check the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Main), the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=is%3Aissue)**

**Describe the bug**

Running the `download` service fails with:

```
...
webui-docker-download-1  | chmod: /output: No such file or directory
webui-docker-download-1 exited with code 1
```

```
...
webui-docker-download-1  | 10/02 05:23:08 [NOTICE] Download complete: /data/LDSR/model.ckpt
webui-docker-download-1  |
webui-docker-download-1  | Download Results:
webui-docker-download-1  | gid   |stat|avg speed  |path/URI
webui-docker-download-1  | ======+====+===========+=======================================================
webui-docker-download-1  | 1ad701|OK  |    21KiB/s|/data/LDSR/project.yaml
webui-docker-download-1  | 7af871|OK  |    14MiB/s|/data/RealESRGAN/RealESRGAN_x4plus_anime_6B.pth
webui-docker-download-1  | 1b1970|OK  |   6.9MiB/s|/data/RealESRGAN/RealESRGAN_x4plus.pth
webui-docker-download-1  | 78c58b|OK  |    20MiB/s|/data/GFPGAN/GFPGANv1.4.pth
webui-docker-download-1  | 05dbc4|OK  |    62MiB/s|/data/StableDiffusion/model.ckpt
webui-docker-download-1  | 495c9d|OK  |    14MiB/s|/data/LDSR/model.ckpt
webui-docker-download-1  |
webui-docker-download-1  | Status Legend:
webui-docker-download-1  | (OK):download completed.
webui-docker-download-1  | Checking SHAs...
webui-docker-download-1  | /data/LDSR/project.yaml: OK
webui-docker-download-1  | /data/RealESRGAN/RealESRGAN_x4plus_anime_6B.pth: OK
webui-docker-download-1  | /data/RealESRGAN/RealESRGAN_x4plus.pth: OK
webui-docker-download-1  | /data/GFPGAN/GFPGANv1.4.pth: OK
webui-docker-download-1  | /data/LDSR/model.ckpt: OK
webui-docker-download-1  | /data/StableDiffusion/model.ckpt: OK
webui-docker-download-1  | chmod: /output: No such file or directory
webui-docker-download-1 exited with code 1
```

**Which UI**

hlky or auto or auto-cpu or lstein?

`download` service only.

**Steps to Reproduce**
1. Clone repo
2. `docker compose --profile download up --build`

**Hardware / Software:**
 - OS: Ubuntu 20.04.3 LTS
 - RAM: 32G
 - GPU: NVIDIA Corporation GM204GL [Quadro M4000]
 - VRAM: 8126MiB
 - Docker Version: Docker version 20.10.18, build b40c2f6
 - Docker compose version: 
 - Release version [e.g. 1.0.1]

**Additional context**

The directories `/output` and `/data` do not exist when `services/download/download.sh` is run by `services/download/Dockerfile` so the `chmod` fails.

Adding this to `download.sh` before the last line (the `chmod`) fixes the issue:

```Bash
test -d /data || mkdir /data
test -d /output || mkdir /output
```

**Comment by eriknomitch** [comment]
I'm not sure if this is the cleanest way to ensure those directories so I didn't make a PR.

**Comment by AbdBarho** [comment]
@eriknomitch thank you for reporting, the folders should have been created while bounding them as volumes, I only bounded the `/data` but forgot the `/output`

https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/6f5eef42a78e2fc840864e3bded9398dab36a89a/docker-compose.yml#L6-L25

That being said, the `chmod` is not necessary, I will just remove it.
