### ISSUE TITLE
auto: Download of sd-v1-4.ckpt from drive.yerf.org times out or is very slow (roughly 1h30m download time estimate)

### ISSUE THREAD

**Issue by GeorgiaM-honestly** [AbdBarho/stable-diffusion-webui-docker#115]
After removing all instances of the repo, stopping all containers, and cleaning up everything with "docker system prune --volumes" thus bringing me to a clean state as far as I know, I performed a git clone and then followed the setup instructions. Upon issuing this command:

``
docker compose --profile auto up --build
``

There is an attempt to download sd-v1-4.ckpt from drive.yerf.org. After about 10 minutes, it seemed to be quite slow to me so I tried the same URL on a different system using wget. While a TCP connection was established, nothing happened after that and after a few minutes I terminated the attempt. I tried a few more times with the same result. I then tried on a different system in another state, and the first 3 attempts had the same result. The 4th attempt worked, however, was at roughly the speed 850KB/s or less, and an estimated time of 1h30m.

UI: Default? I didn't tell it which one to use.

Auto.

**Steps to Reproduce**
1. Perform git clone
2. cd into the resultant directory
3. docker compose --profile download up --build
4. If 3 is successful: docker compose --profile auto up --build
5. Wait for the attempt to download sd-v1-4.ckpt from drive.yerf.org ( Displays: webui-docker-auto-1  | Downloading: "https://drive.yerf.org/wl/?id=EBfTrmcCCUAGaQBXVIj5lJmEhjoP1tgl&mode=grid&download=1" to /stable-diffusion-webui/models/Stable-diffusion/sd-v1-4.ckpt
6. If there are issues, try the download using curl or wget from other systems and particularly different internet connections / providers

**Hardware / Software:**
 - OS: Linux, Debian GNU/Linux 11 (bullseye)
 - RAM: 24GB
 - GPU: NVIDIA Corporation TU102 [GeForce RTX 2080 Ti Rev. A] (rev a1).
 - VRAM: 12GB
 - Docker Version, Docker compose version: 20.10.18, build b40c2f6, v2.10.2
 - Release version: 2.0.0

**Expected behavior:**
A more reasonable download time, keeping in mind that we all know hosting can get expensive.

**Comment by GeorgiaM-honestly** [comment]
On closer review this appears to be an upstream issue, not an issue with your project. I apologize. Please close it if you wish.

**Comment by AbdBarho** [comment]
@GeorgiaM-honestly This should not be the case.

as part of the `docker compose --profile download up --build` command, the model should be downloaded. (speed is not something I can control, but it should be there).

Can you check the contents of the folder `data/StableDiffusion`? it should have at least one file with the name `model.ckpt` (~4GB) in size.
Is this the case?

**Comment by GeorgiaM-honestly** [comment]
I understand, the auto project (or something it depends on) is controlling where the files are hosted.

After obtaining a TCP/HTTP(s) session that is both established and data is sent slowly and waiting long enough, the entire file is indeed there.

**Comment by xiangcp** [comment]
docker compose v2
https://blog.csdn.net/hanxiaotongtong/article/details/125477514
