### ISSUE TITLE
Error load metadata for docker.io/library/alpine:3.15

### ISSUE THREAD

**Issue by kywch** [AbdBarho/stable-diffusion-webui-docker#118]
Hello, thank you @AbdBarho for making this wonderful docker! 

I'm a novice docker user, and I encountered the below error while running the first command `docker compose --profile download up --build`.

```
=> ERROR [internal] load metadata for docker.io/library/bash:alpine3.15
------
 > [internal] load metadata for docker.io/library/bash:alpine3.15
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials -err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`
```

I solved this issue by [the following comment](https://github.com/docker/buildx/issues/476#issuecomment-761875948)

1. Create an account on 'https://hub.docker.com/'
2. Run in terminal: 'docker login'
3. Authorized in terminal
4. Try run docker build again

And both the download and ui (auto) builds ran well.

Thank you!

**Comment by AbdBarho** [comment]
Might be related to #56 

A docker account is not necessary for downloading and running this app. maybe there is some sort of misconfiguration in your docker setup that led to this.

Anyway, glad it worked.

**Comment by hmartiro** [comment]
I ran `sudo apt install gnome-keyring` per https://github.com/microsoft/vscode-docker/issues/1515 and this worked for me on Ubuntu Bionic.
