### ISSUE TITLE
failed to solve: executor failed running [/bin/bash -ceuxo pipefail conda install python=3.8.5 && conda clean -a -y]: error creating overlay mount to /var/lib/docker/overlay2/1tyz8ab42xxmlt0sxcv66mirh/merged: too many levels of symbolic links

### ISSUE THREAD

**Issue by TehFridge** [AbdBarho/stable-diffusion-webui-docker#119]
![image](https://user-images.githubusercontent.com/85436576/194155887-ab9672e5-a633-44e9-8fa0-81c7d1b0c879.png)
i am just trying to install this with docker and on the second step it just does this.

**Comment by AbdBarho** [comment]
@TehFridge please  use the bug template next time.

what version of windows / wsl / docker / docker compose do you have?

**Comment by TehFridge** [comment]
Docker version 20.10.17, build 100c701
Docker Compose version v2.10.2
WSL2

**Comment by TWIISTED-STUDIOS** [comment]
@TehFridge what was your issue and how did you resolve it because i have the same issue

**Comment by TehFridge** [comment]
> @TehFridge what was your issue and how did you resolve it because i have the same issue 

Well i didnt. I just moved to the normal version of the web-ui by AUTOMATIC1111

**Comment by TWIISTED-STUDIOS** [comment]
> > @TehFridge what was your issue and how did you resolve it because i have the same issue
> 
> Well i didnt. I just moved to the normal version of the web-ui by AUTOMATIC1111

Yh I also have the normal version installed locally, I was just curious as to the docker version and see how well it would work.

**Comment by DevilaN** [comment]
There are many possible problems that will end up with too many levels of symbolic links.

Best shot here is to try from start by removing everything from docker directories and rebuild containers.
Warning: ***THIS IS DESTRUCTIVE OPTION FOR DOCKER IMAGES AND CONTAINERS EXISTING IN SYSTEM***
1. Clear everything with `docker system prune -a`.
2. Build webui with `docker compose --profile auto up --build`
3. Test if it works fine :-)

**Comment by Pyroglyph** [comment]
> Clear everything with `docker system prune -a`.

Despite completely reinstalling Docker, this issue still occurred for me, yet pruning fixed it. Very strange.
