### ISSUE TITLE
Feature Request - Please add the following as docker shares in /data

### ISSUE THREAD

**Issue by ChronoStriker1** [AbdBarho/stable-diffusion-webui-docker#122]
I'm currently manually editing an override file for this but I think it may be helpful to those less familiar with docker containers if you could add the following destinations.  I'm assuming you would want them in the ./data dir.

So you can save styles - I don't think I created this correctly since it seems to say its in use when writing back to it
      `- ./services/AUTOMATIC1111/styles.csv:/stable-diffusion-webui/styles.csv`

this one is less necessary, I only put it here since having the backup would be usefull, but I have the same issue as above and this would cause things to error, so I disabled it in my override yaml
      `- ./services/AUTOMATIC1111/styles.csv.bak:/stable-diffusion-webui/styles.csv.bak`

this is only useful for those who plan on using the NAI models
      `- ./data/hypernetworks:/stable-diffusion-webui/models/hypernetworks`
 same but less important
      `- ./data/v2.pt:/stable-diffusion-webui/v2.pt`
for custom scripts - it may be worth doing the same for the modules folder as well
      `- ./data/scripts:/stable-diffusion-webui/script`

for using the textual inversion checkpoints - i have also created a ./data/textual_inversion and have directories for datasets, logs, and templates, that last one I'm not sure if should have a mount point or should be linked after a git pull since its possible the Automatic1111 repo could update or add more themselves.

**Comment by AbdBarho** [comment]
@ChronoStriker1 Thank you for the suggestion, this seems to be related to #102.

The biggest question / concern that I have is keeping stuff that can be used across multiple UIs separate from UI-specific features & mounts.

I am unsure how to go about this, `data/auto/...` for all the stuff related to this UI, and then `data/hlky/...` and so on? or maybe a new folder called `ui` for all ui specific stuff. or maybe leave it all up to the user just like you managed to do it.

The biggest pain-point would be migration, I want to have the least amount of breaking changes as possible (looking into the future), just like you mentioned at the end, if the UI updates stuff, this might break the entire folder structure.

what do you think?

**Comment by ChronoStriker1** [comment]
Keeping it up to the user I think would be fine I would at that point just have the lines needed in the docker file commented out as optionals and just mention it int he wiki how to add them as an override or have a script that when the download profile is run, checks to see if those lines are uncommented and then creates the folder structure.  That might be overly complicated for a feature only one person asked for.  Ether way I think mentioning those folders as possible mount locations would be useful.  Also how to create a override yaml may be of use to people not familiar with docker compose, that was a first for me so I kind winged it.  Not sure if this was the correct way to do it.  Ill just post what I have here so there is at least a record incase someone goes searging. Side note the commented out line for the —deepdanbooru flag was in preparation for the the Automatic1111 is up to an update that implements it.

services:
  auto:
    volumes:
      - ./data:/data
      - ./output:/output
      - ./services/AUTOMATIC1111/config.json:/stable-diffusion-webui/config.json
      - ./services/AUTOMATIC1111/styles.csv:/stable-diffusion-webui/styles.csv
#      - ./services/AUTOMATIC1111/styles.csv.bak:/stable-diffusion-webui/styles.csv.bak
      - ./data/hypernetworks:/stable-diffusion-webui/models/hypernetworks
      - ./data/v2.pt:/stable-diffusion-webui/v2.pt
      - ./data/scripts:/stable-diffusion-webui/scripts
    environment:
      - CLI_ARGS=--allow-code --opt-split-attention --gradio-img2img-tool color-sketch --xformers #--deepdanbooru

**Comment by Hexadecimalism** [comment]
> I'm currently manually editing an override file

Looking to do this as a temporary solution, where is the override file? The closest I've found is mount.sh in services/AUTOMATIC1111.
