### ISSUE TITLE
Image save path problem in WSL with docker 

### ISSUE THREAD

**Issue by Decayo** [AbdBarho/stable-diffusion-webui-docker#124]
Overall, is able to produce images and works very well.
But in WSL + Docker environment, it seems that images cannot be saved

webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui.py", line 158, in f
webui-docker-auto-1  |     res = list(func(*args, **kwargs))
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui.py", line 125, in save_files
webui-docker-auto-1  |     with open(os.path.join(opts.outdir_save, "log.csv"), "a", encoding="utf8", newline='') as file:
webui-docker-auto-1  | FileNotFoundError: [Errno 2] No such file or directory: '/output/saved/log.csv'
webui-docker-auto-1  | 

Is any way to solve it ?

**Comment by AbdBarho** [comment]
you can try creating a folder in the `output` folder called `saved`, see if that works?

**Comment by Decayo** [comment]
It works! Thanks a lot. But the error still happenned.

**Comment by AbdBarho** [comment]
Fixed, now an empty directory will be created if it is not there
