### ISSUE TITLE
Build Error. failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0

### ISSUE THREAD

**Issue by RWoxiN** [AbdBarho/stable-diffusion-webui-docker#125]
**Describe the bug**
![image](https://user-images.githubusercontent.com/78133217/195098832-6391acd3-e378-4d06-9167-281749448596.png)

**Hardware / Software:**
 - OS: WSL
 - Docker Version, Docker compose version
![image](https://user-images.githubusercontent.com/78133217/195099142-e3723b8e-7d38-4e1c-8ccd-092bdfc9b7b6.png)
![image](https://user-images.githubusercontent.com/78133217/195099225-ec3228aa-5520-477a-b418-c23381c34a18.png)
 - Release version: latest

**Comment by AbdBarho** [comment]
Can you open the docker ui and go into settings, is  the `Use Docker Compose V2` checked? it should be checked

**Comment by AbdBarho** [comment]
Oh, it seems you are running docker from within wsl, can you try running it from windows powershell?

**Comment by RWoxiN** [comment]
> Oh, it seems you are running docker from within wsl, can you try running it from windows powershell?

The same happened in powershell environment.

> Can you open the docker ui and go into settings, is the `Use Docker Compose V2` checked? it should be checked

Already checked.

**Comment by AbdBarho** [comment]
my best guess is that docker buildkit is not correctly enabled.

maybe try this? https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds

What is your Windows version? and WSL version?

**Comment by RWoxiN** [comment]
> my best guess is that docker buildkit is not correctly enabled.
> maybe try this? https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds

BuildKit builds has enabled before.
![image](https://user-images.githubusercontent.com/78133217/195319763-faad6d7c-ca83-4515-b200-e4efbcbae350.png)

> What is your Windows version? and WSL version?
![image](https://user-images.githubusercontent.com/78133217/195320037-00e05b05-c52b-4aad-ad5a-48dbffba2b78.png)
![image](https://user-images.githubusercontent.com/78133217/195320197-ed5ef6ee-cd1f-4797-a2ae-f866997f7e90.png)

**Comment by AbdBarho** [comment]
I am sorry man, I  am out of  ideas, the problem is that your docker version for whatever reason does not recognize the new syntax, even though you have all up-to-date versions.

**Comment by azamtoiri** [comment]
how you solve this?

**Comment by shadowwinds** [comment]
i got same error when registry-mirrors is specified
check this https://github.com/moby/moby/issues/39120

**Comment by playlinuxcn** [comment]
update docker version is ok.

https://download.docker.com/linux/centos/docker-ce.repo

yum update docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

**Comment by BraINstinct0** [comment]
Had exactly same issue even with currently most recent environment (WSL2, Ubuntu 22.04+Docker), but simply rerunning worked
