### ISSUE TITLE
nvidia-container-cli error when running UI

### ISSUE THREAD

**Issue by jiayuandeng** [AbdBarho/stable-diffusion-webui-docker#129]
**Describe the bug**
Getting the following error when `docker compose --profile hlky up --build`
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
```

I'm using WSL2 (latest Docker Desktop).
GPU is RTX3090.

**Which UI**

hlky and auto

Please advise.

**Comment by AbdBarho** [comment]
Which windows version are you running?
Are running docker compose in powershell or in Wsl?

**Comment by jiayuandeng** [comment]
Windows 10 Pro, 20H2, 19042.928
Running docker compose in powershell

**Comment by AbdBarho** [comment]
you need >= 2021H2 

https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ#other-build-errors-on-windows

**Comment by jiayuandeng** [comment]
That makes sense. Thanks!
