### ISSUE TITLE
auto-cpu but it throws an error because no Nvidia found

### ISSUE THREAD

**Issue by xNissX233** [AbdBarho/stable-diffusion-webui-docker#132]
**Has this issue been opened before?**
No

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

After downloading latest release and build the docker with docker compose --profile download up --build, I try to run it with docker compose --profile auto-cpu up --build but it exits with an error saying that it didn't find nvidia drivers, which makes sense because I'running it in a VM... but I would expect the auto-cpu flag to make this run without the gpu. Is this a bug or am I missing something?.

**Which UI**

auto-cpu

**Hardware / Software**
 - OS: Debian VM
 - OS version: 11
 - Docker Version: Latest from official repositories
 - Docker compose version: Latest from official repositories
 - Repo version: Release 2.0.1
 - RAM: 4G
 - GPU/VRAM: 256MB

**Steps to Reproduce**
1. docker compose --profile download up --build
2. docker compose --profile auto-cpu up --build

**Comment by AbdBarho** [comment]
@RBNXI can you please show the entire log? I need to see the error.

**Comment by AbdBarho** [comment]
yeah no, the problem is not nvidia, 4GB RAM is not enough, you need at least 16! sorry I did not see it earlier.

**Comment by AbdBarho** [comment]
the error you see is a just warning, it starts to load the model:
```
webui-docker-auto-cpu-1 | LatentDiffusion: Running in eps-prediction mode
```
and then crashes.

try it with 12, if it fails, increase to 16?

**Comment by AbdBarho** [comment]
@RBNXI may I ask why are you running in a VM? is it on the cloud?
