### ISSUE TITLE
[upgrade] Getting rid of unnecesary git clone of other repositories

### ISSUE THREAD

**Issue by DevilaN** [AbdBarho/stable-diffusion-webui-docker#135]
Currently service "download" and other services are using sequence of commands:
`git clone REPOSITORY_URL && cd REPO_DIR && git reset --hard COMMIT_SHA`
This unnecesary downloads entire repository history only to change it's state to specific commit.

It would be better not to download entire repository, but zip file from specific commit instead.
Download link format is https://github.com/{username}/{projectname}/archive/{sha}.zip - then there is only a matter of unzipping and renaming directory.

**Comment by AbdBarho** [comment]
that is a great idea!

would you like to contribute?

**Comment by karpfediem** [comment]
in the case of downloads using git, the `depth` flag exists to make shallow copies:
`--depth <depth>       create a shallow clone of that depth`

**Comment by DevilaN** [comment]
@AbdBarho sure, but I am running only AUTOMATIC1111 version. Is that ok, to improve only it's Dockerfile or I have to do rework of other ones (I am not sure whether I've got enough disk space to build all images).

Also those changes will surely bust docker cache forcing users to rebuild entire image almost from scratch, so it would be better to merge it later with some bigger changes also involving cache bust, as for now it is small gain only, but gain nonetheless.

**Comment by karpfediem** [comment]
> @karpfediem that is also neat, maybe verbose, but still neat! is it faster than cloning the entire repo?

Yes, it will only download that specific commit with git fetch.

I'd argue against archive downloads since they are very much github specific, not that i've seen any other repositories being used though to be fair :sweat_smile:

**Comment by DevilaN** [comment]
Remove `.git` directory afterwards. It is not necessary and takes half of space inside directory.
