### ISSUE TITLE
Community finetune files are not working for me.

### ISSUE THREAD

**Issue by Corshi** [AbdBarho/stable-diffusion-webui-docker#137]
AI thing. I have a problem with addiction, 
So I use the " AbdBarho / stable-diffusion-webui-docker" repo and "AUTOMATIC1111" version from it. All normal hypernetworks .pt files works fine for me. But all community's ones give me thins like this:
```
webui-docker-auto-1  | + python3 -u ../../webui.py --listen --port 7860 --hide-ui-dir-config --ckpt-dir /stable-diffusion-webui/models/Stable-diffusion --allow-code --medvram
webui-docker-auto-1  | Error loading hypernetwork /stable-diffusion-webui/models/hypernetworks/queencomplexstyle-2-4300.pt
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/hypernetwork.py", line 48, in load_hypernetworks
webui-docker-auto-1  |     hn = Hypernetwork(filename)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/hypernetwork.py", line 40, in __init__
webui-docker-auto-1  |     self.layers[size] = (HypernetworkModule(size, sd[0]), HypernetworkModule(size, sd[1]))
webui-docker-auto-1  | TypeError: 'int' object is not subscriptable
```
any ideas?

"by normal hypernetworks .pt files works", I mean that I added this line:
```
MOUNTS["${ROOT}/models/hypernetworks"]="/data/hypernetworks"
```
to \services\AUTOMATIC1111\mount.sh
and all the appropriate file in there

WEBUI AUTOMATIC1111 (auto)

**Hardware / Software**
 - OS: Windows 11
 - OS version: 2aH2 22000.652
 - Docker&compose version: Latest
 - RAM: 32GB
 - GPU/VRAM: 8GB

I just put the community generated files into the hypernetworks and those do not work. I eventually tried to add the "hypernetwork.py" file from original AUTOMATIC1111 repo, but no luck.

PS: AUTOMATIC1111 webui had an update and now there is a new merging process for models. Unrelated, but interesting.

**Comment by AbdBarho** [comment]
@Corshi can you give a link to the normal and community hypernetworks so I can test?

**Comment by Corshi** [comment]
"normal hypernetworks" are the .pt modules that are part of the leaked models and is now used by community.
Aka "novelaileak". Sadly can't publicly share or direct you to it. They work thou. 

The community models are on the discord server https://discord.gg/JhVXMWza under the #Hyper-data 
AUTOMATIC1111 is also on that server...
And other pointer also are there.
Sorry for being cryptic.

**Comment by AbdBarho** [comment]
No probs, I will see if I can get some to test.

That being said, from the first look I can say the problem is probably not in this repo, but rather in the original https://github.com/AUTOMATIC1111/stable-diffusion-webui

Have you checked there?

**Comment by Corshi** [comment]
Nothing there about the problem like that.
And if it's about trying to recreate/find the problem on that repo.
No luck, as can't make it to install at all.
 I'm having there some kind of problems recognizing my python and pip. So I will have to check that some other time.

**Comment by AbdBarho** [comment]
After looking into hypernetworks, I seriously question the legality of any of this.

I apologize I won't be able to assist you further.
