### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'output/txt2img-images'

### ISSUE THREAD

**Issue by AbdBarho** [AbdBarho/stable-diffusion-webui-docker#138]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Error happens on start up, the rest works fine, I can generate images.

**Which UI**

auto

**Comment by KagurazakaNyaa** [comment]
This issue has been fixed in https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cd28465bf87d911965790513c37e6881e4231523

**Comment by AbdBarho** [comment]
@KagurazakaNyaa  Thank you, I created an MR #146
