### ISSUE TITLE
FileExistsError: [Errno 17] when starting 'auto' interface

### ISSUE THREAD

**Issue by Bluejay47** [AbdBarho/stable-diffusion-webui-docker#140]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

```
webui-docker-auto-1  | + python3 -u ../../webui.py --listen --port 7860 --hide-ui-dir-config --ckpt-dir /stable-diffusion-webui/models/Stable-diffusion --allow-code --medvram
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/../../webui.py", line 12, in <module>
webui-docker-auto-1  |     from modules import devices, sd_samplers
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_samplers.py", line 10, in <module>
webui-docker-auto-1  |     from modules import prompt_parser, devices, processing
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/processing.py", line 13, in <module>
webui-docker-auto-1  |     import modules.sd_hijack
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
webui-docker-auto-1  |     import modules.textual_inversion.textual_inversion
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
webui-docker-auto-1  |     from modules import shared, devices, sd_hijack, processing, sd_models
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/shared.py", line 91, in <module>
webui-docker-auto-1  |     os.makedirs(cmd_opts.hypernetwork_dir, exist_ok=True)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
webui-docker-auto-1  |     mkdir(name, mode)
webui-docker-auto-1  | FileExistsError: [Errno 17] File exists: '/stable-diffusion-webui/models/hypernetworks'
webui-docker-auto-1 exited with code 1
```
is generated in response to

```
docker compose --profile auto up --build
```

lstein and hlky seem to run fine

**Which UI**

hlky or auto or auto-cpu or lstein?

auto

**Hardware / Software**
 - OS: Ubuntu
 - 22.04
 - Docker Version: 20.10.18
 - Docker compose version: Docker Compose version v2.10.2
 - Repo version: from master
 - RAM: 64GB
 - GPU/VRAM: Nvidia 3090 / 24GB

**Steps to Reproduce**
1. enter "docker compose --profile auto up --build" at command prompt

**Additional context**
Started with recent version. I had been running previous versions prior to this. I deleted all artifacts (including docker prune and deleting all existing images and containers) and stated over with this version I cloned a few hours ago.

**Comment by Bluejay47** [comment]
Note: I was able to temporarily bypass the error by removing:

```
MOUNTS["${ROOT}/models/hypernetworks"]="/data/Hypernetworks"
```

from the mounts.sh file in the services/AUTOMATIC1111 directory.

**Comment by gregwbrooks** [comment]
Merely commenting to say that I experienced the same bug under the same circumstances today; only difference was that it also showed up on a completely new AWS VM with no previous SD install.

**Comment by AbdBarho** [comment]
This should be fixed now, please check in your `data` folder if there is a `Hypernetworks` FILE, if so, please remove it first, otherwise if it is  a folder, everything should work fine.
