### ISSUE TITLE
"Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]" when trying to compose the auto-cpu profile

### ISSUE THREAD

**Issue by cspace-echo** [AbdBarho/stable-diffusion-webui-docker#142]
**Describe the bug**

Tried to run the GPU:less mode on an old pentium mini-PC, this worked when I ran it as root, but to properly run it in the background I made a user with docker rights to run it in a screen session(which worked as root). The installer/download script failed to install a face-fix component, but that wasn't an issue earlier.
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

**Which UI**

auto-cpu

**Hardware / Software**
 - OS: Ubuntu Server
 - OS version: 22.04.1 kernel Linux 5.15.0-50-generic on x86_64
 - Docker Version: 20.10.18
 - Docker compose version: v2.10.2
 - Repo version: 
 - RAM: 8 Gb
 - GPU/VRAM: none, or what an Intel chipset happens to have

**Steps to Reproduce**
1. downloaded and unpacked stable-diffusion-ui-linux.tar
2. ran start.sh with no obvious errors
3. ran "docker compose --profile download up --build" which gave the error "Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]", that wasn't relevant to running CPU only.
4. ran "docker compose --profile auto-cpu up --build" and get the same error, dumped output below

**Additional context**
console dump:
stable-diffusion@cspaceserver01:~/stable-diffusion-ui/stable-diffusion$ docker compose --profile auto-cpu up --build
[+] Building 1.9s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                                                       0.0s
 => => transferring dockerfile: 32B                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                          0.0s
 => => transferring context: 34B                                                                                                           0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.3.1-base-ubuntu20.04                                                             0.6s
 => [internal] load build context                                                                                                          1.2s
 => => transferring context: 4.38MB                                                                                                        1.1s
 => [1/7] FROM docker.io/nvidia/cuda:11.3.1-base-ubuntu20.04@sha256:0274590a738be104d1672eaef4cc65cc5d539f07a767567017f42affc4f0743d       0.0s
 => CACHED [2/7] RUN apt update  && apt install --no-install-recommends -y curl wget git  && apt-get clean                                 0.0s
 => CACHED [3/7] RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh -O ~/miniconda.sh  && bash ~/minicon  0.0s
 => CACHED [4/7] COPY . /root/stable-diffusion                                                                                             0.0s
 => CACHED [5/7] RUN eval "$($HOME/miniconda/bin/conda shell.bash hook)"  && cd /root/stable-diffusion  && conda env create -f environmen  0.0s
 => CACHED [6/7] RUN ln -s /data /root/stable-diffusion/models/ldm/stable-diffusion-v1  && mkdir -p /output /root/stable-diffusion/output  0.0s
 => CACHED [7/7] WORKDIR /root/stable-diffusion                                                                                            0.0s
 => exporting to image                                                                                                                     0.0s
 => => exporting layers                                                                                                                    0.0s
 => => writing image sha256:4a6d2581fde754a36525bf271a81fdca134c11210f1fcfef18282a2f6c971072                                               0.0s
 => => naming to docker.io/library/stable-diffusion-sd                                                                                     0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Attaching to stable-diffusion-sd-1
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

Probably unrelated GFPGAN install error:
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

**Comment by AbdBarho** [comment]
@cspace-echo this is not the correct repo. this is not my code.

**Comment by cspace-echo** [comment]
Ach sorry, I mixed up two similarly named archive files. I'm guessing "cmdr2/stable-diffusion-ui"'s script overwrote some of your code when I ran it, when I started from scratch to transition from root to my service-user account.

**Comment by AbdBarho** [comment]
No probs!
