### ISSUE TITLE
[Request] Add easy way to change max batch size

### ISSUE THREAD

**Issue by dathide** [AbdBarho/stable-diffusion-webui-docker#147]
Thanks for keeping this repo up to date! Changing max batch sizes is a line change in uiconfig.json
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Change-UI-Defaults

With the latest version of this repo, a batch size of 8 only uses around 5GB of VRAM on my 3090's 24GB. Could you add something in docker-compose.yml to allow the max batch sizes to be changed? I tried doing it myself by adding these lines to AUTO's Dockerfile, but it didn't work:
```
RUN sed -i 's@"txt2img/Batch size/maximum": 8@txt2img/Batch size/maximum": 32@g' ../../ui-config.json
RUN sed -i 's@"img2img/Batch size/maximum": 8@img2img/Batch size/maximum": 32@g' ../../ui-config.json
```

**Comment by AbdBarho** [comment]
@dathide what we should probably do is make the `ui-config.json` be available for users to modify.

I will see if I can get to it by the end of the day.

**Comment by AbdBarho** [comment]
@dathide the feature is added, here is what you should do:

* pull the latest state from master
* start the auto ui & open in the browser
* stop the ui
* you should now have a file `data/config/auto/ui-config.json`
* you can change whatever you want there, not just the batch size.
