### ISSUE TITLE
No such file or directory: 'F:\\git\\stable-diffusion-webui-docker\\test_input_frames'

### ISSUE THREAD

**Issue by Zudva** [AbdBarho/stable-diffusion-webui-docker#156]
I am getting this error when I start the Batch Image2Image process:

```
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui.py", line 212, in f
webui-docker-auto-1  |     res = list(func(*args, **kwargs))
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/../../webui.py", line 64, in f
webui-docker-auto-1  |     res = func(*args, **kwargs)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/img2img.py", line 120, in img2img
webui-docker-auto-1  |     process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, args)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/img2img.py", line 22, in process_batch
webui-docker-auto-1  |     images = [file for file in [os.path.join(input_dir, x) for x in os.listdir(input_dir)] if os.path.isfile(file)]
webui-docker-auto-1  | FileNotFoundError: [Errno 2] No such file or directory: 'F:\\git\\stable-diffusion-webui-docker\\test_input_frames'
```

I need add this folder to docker container?

**Comment by AbdBarho** [comment]
all the data that you want to put in or get out of the container should be either in the `data` or the `output` folders.

both folders are mounted in the container under `/`, meaning if you have your input folder called `train_images`, you put it under the `data` folder, and in the web ui you reference to it using the path `/data/train_images`, and so on.

Of course you can mount other folders if you want to.

**Comment by Zudva** [comment]
> all the data that you want to put in or get out of the container should be either in the `data` or the `output` folders.
> 
> both folders are mounted in the container under `/`, meaning if you have your input folder called `train_images`, you put it under the `data` folder, and in the web ui you reference to it using the path `/data/train_images`, and so on.
> 
> Of course you can mount other folders if you want to.

This work! Thank you!
