### ISSUE TITLE
Error during download phase (can't get /data/StableDiffusion/model.ckpt)

### ISSUE THREAD

**Issue by bhjolly** [AbdBarho/stable-diffusion-webui-docker#159]
**Has this issue been opened before?**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

`sudo docker compose --profile download up --build` fails to download StableDiffusion, investigating further up the terminal output shows the following error:

```
webui-docker-download-1  | 10/21 00:00:58 [ERROR] CUID#7 - Download aborted. URI=https://www.googleapis.com/storage/v1/b/aai-blog-files/o/sd-v1-4.ckpt?alt=media
webui-docker-download-1  | Exception: [AbstractCommand.cc:351] errorCode=24 URI=https://www.googleapis.com/storage/v1/b/aai-blog-files/o/sd-v1-4.ckpt?alt=media
webui-docker-download-1  |   -> [HttpSkipResponseCommand.cc:215] errorCode=24 Authorization failed.
```

**Which UI**

'download' profile

**Hardware / Software**
 - OS: Ubuntu
 - OS version: 20.04 LTS
 - Docker Version: 
 - Docker compose version: v2.12.0
 - Repo version: 31e4dec (latest)
 - RAM: 64 GB
 - GPU/VRAM: 24 GB

**Steps to Reproduce**
Vanilla docker and docker-compose install
Clone repo
cd to repo
`sudo docker compose --profile download up --build`

**Comment by d4rk6un** [comment]
same issue.

**Comment by AbdBarho** [comment]
it  seems that the link is dead, I will try to find other links

**Comment by AbdBarho** [comment]
A new  link is now used, @d4rk6un  @bhjolly can you try from latest master? if it is not working, re-open this issue.

**Comment by d4rk6un** [comment]
> 

It's working. Thanks, @AbdBarho
