### ISSUE TITLE
Compose won't build

### ISSUE THREAD

**Issue by pixartist** [AbdBarho/stable-diffusion-webui-docker#16]
**Has this issue been opened before? Check issues [here](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=is%3Aissue) and in [this one as well](https://github.com/hlky/stable-diffusion-webui)**

**Describe the bug**
running docker-compose build causes
```
Error response from daemon: dockerfile parse error line 33: unknown instruction: GIT
ERROR: Service 'model' failed to build : Build failed
```
**Hardware / Software:**
 - Ubuntu 22

**Comment by AbdBarho** [comment]
use `docker compose` instead of `docker-compose`?

**Comment by tr7zw** [comment]
Ran into the same issue, I had to update docker(was on a rather old version).

**Comment by fivethreeo** [comment]
Or make heredoc to multiline bash RUN

**Comment by shodanx2** [comment]
Hi

Having the same issue

```
root@stablediffusion:/opt/stable-diffusion-webui-docker# docker-compose build
Building model
Sending build context to Docker daemon  7.168kB
Error response from daemon: dockerfile parse error line 14: unknown instruction: GIT
ERROR: Service 'model' failed to build : Build failed
root@stablediffusion:/opt/stable-diffusion-webui-docker# docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu4
root@stablediffusion:/opt/stable-diffusion-webui-docker# docker compose build
docker: 'compose' is not a docker command.
See 'docker --help'
```

Even though I have a very recent docker , something changed between 20.10.12 and 20.10.18 and now you need the latest

On ubuntu, upgrading was as easy as

```
apt remove docker-compose
apt -y install curl
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
```

then you can resume your stablediffusion installation

**Comment by isapir** [comment]
installing the `docker-compose-plugin` [1] on Ubuntu resolved the issue for me: 
```
sudo apt-get install docker-compose-plugin
```

[1] https://docs.docker.com/compose/install/linux/#install-the-plugin-manually

**Comment by Paulie420** [comment]
For the last poster, dont just install docker-compose by 'sudo apt install docker-compose' ... you want to install the newest docker compose (see, not docker-compose...) by following this : https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04
If yer not using 22.04, google search 'ubuntu docker compose' and select the digitalocean.com howto for your ubuntu version... this is different than installing docker-compose. :P
