### ISSUE TITLE
desc = failed to solve with frontend dockerfile.v0

### ISSUE THREAD

**Issue by zhoutaizi** [AbdBarho/stable-diffusion-webui-docker#160]
when I entered the command "docker compose --profile auto up --build", 
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = dockerfile parse error on line 14: unknown instruction: git

**Comment by zhoutaizi** [comment]
I'm very sorry that it's my first time to use "issues", I realized someone posted same issue before, and I can't delete this.

**Comment by AbdBarho** [comment]
@zhoutaizi No problem! I hope your problem is fixed.
