### ISSUE TITLE
unknown flag: --profile ? And my docker is latest?

### ISSUE THREAD

**Issue by lizekui** [AbdBarho/stable-diffusion-webui-docker#165]
My OS is Ubuntu 16.04, when I type `docker compose --profile download up --build`

returns:

```
unknown flag: --profile
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers
```

My software version is as follows:

```
$ docker --version
Docker version 20.10.7, build f0df350

$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

**Comment by AbdBarho** [comment]
`docker compose` not `docker-compose`

**Comment by AbdBarho** [comment]
`docker-compose` is the old v1 which does not have the flag.

`docker compose` is v2 which has the flag

what is your `docker compose version`?

**Comment by DevilaN** [comment]
Ubuntu Linux 16.04 LTS reached the end of its five-year LTS window on April 30th 2021 and is no longer supported by its vendor, Canonical except through a paid annual Extended Security Maintenance (ESM).
Your docker version (`20.10.7`) has been released on `2021-06-02` and almost for sure does not contain `compose v2`, because it has been release with 20.10.13 as a plugin to run alongside v1.
Docker compose v1 does not support --profile flag.
> What is the ridiculous problem with my docker?
Without updating system to more recent one supporting proper docker version there is nothing anybody can do to help you any further.

**Comment by xiangcp** [comment]
```
$ docker -v
Docker version 20.10.21, build baeda1f
$ docker compose version
Docker Compose version v2.2.3
$ docker compose --profile download up --build
(root) Additional property name is not allowed

```
Although my docker compose version is changed to v2, it still reports an error：(root) Additional property name is not allowed

**Comment by AbdBarho** [comment]
@xiangcp update to latest docker compose, mine is `2.10.2`

**Comment by shinyone** [comment]
Had the same issue with `unknown flag profile`

Solution from another issue

`sudo apt install docker-compose-plugin`

**Comment by lizekui** [comment]
@shinyone your solution just save me! Thanks dear everyone~

**Comment by spuliz** [comment]
When I run sudo apt install docker-compose-plugin I get "No package docker-compose-plugin available."

**Comment by shinyone** [comment]
what are your versions?  You need V2

```
$ docker --version
$ docker-compose --version
```

**Comment by AbdBarho** [comment]
@webdevbyjoss maybe it is a typo but:
```
docker-compose
```
and
```
docker compose
```
are two different things

**Comment by webdevbyjoss** [comment]
thnx for the comment, in my case the reported version is still the same
```
# docker compose version
Docker Compose version v2.13.0
```

**Comment by webdevbyjoss** [comment]
> also, --profile [x] up, not up --profile [x]

Yes!! That was it!

```
# docker compose --profile [service X] up
```

Thank you. I hope this will be useful for others.

**Comment by JansenSmith** [comment]
Thank you @shinyone !

**Comment by alhabarneh** [comment]
@AbdBarho
> also, `--profile [x] up`, not `up --profile [x]`

This saved me! Thanks!!

**Comment by hocop** [comment]
For me `sudo apt install docker-compose-plugin` didn't work. What did work was:
```
sudo apt install docker-compose-v2
```

**Comment by C2jeremy** [comment]
> For me `sudo apt install docker-compose-plugin` didn't work. What did work was:对我来说 `sudo apt install docker-compose-plugin` 没有用。起作用的是：
> 
> ```
> sudo apt install docker-compose-v2
> ```

This saves me ! Thank you
