### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Corshi** [AbdBarho/stable-diffusion-webui-docker#177]
New error after yesterdays update. This update happened to me 12 hours ago.
Cant use models and webui doesn't seem to work properly. Defiantly cant generate anything
Also I didn't do anything new. That just started to happen and no reinstalling helped.

This is the error log from after clicking "Generate"
```
Error completing request
Arguments: ('hand', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 0, '', False, False, None, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/ui.py", line 221, in f
    res = list(func(*args, **kwargs))
  File "/stable-diffusion-webui/repositories/stable-diffusion/../../webui.py", line 63, in f
    res = func(*args, **kwargs)
  File "/stable-diffusion-webui/modules/txt2img.py", line 48, in txt2img
    processed = process_images(p)
  File "/stable-diffusion-webui/modules/processing.py", line 437, in process_images
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength)
  File "/stable-diffusion-webui/modules/processing.py", line 584, in sample
    x = create_random_tensors([opt_C, self.height // opt_f, self.width // opt_f], seeds=seeds, subseeds=subseeds, subseed_strength=self.subseed_strength, seed_resize_from_h=self.seed_resize_from_h, seed_resize_from_w=self.seed_resize_from_w, p=self)
  File "/stable-diffusion-webui/modules/processing.py", line 244, in create_random_tensors
    if p is not None and p.sampler is not None and (len(seeds) > 1 and opts.enable_batch_seeds or opts.eta_noise_seed_delta > 0):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

WEBUI AUTOMATIC1111 (auto)

Hardware / Software

    OS: Windows 11
    OS version: 2aH2 22000.652
    Docker&compose version: Latest
    RAM: 32GB
    GPU/VRAM: 8GB

On the side note. I don't any reasons to to include those "now an extensions" by default.
https://github.com/AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients
https://github.com/yfszzx/stable-diffusion-webui-images-browser
Or maybe even this small script:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Custom-Scripts#wildcards

**Comment by AbdBarho** [comment]
I have just pushed an update to master, see if that fixes the issue, you can also try and clear your settings and try again.

Otherwise this error is in the UI and there is nothing I can do about it.

**Comment by Corshi** [comment]
So I did a fresh install. Same bug - it was before the update you did.
I did git pull in old install. Same bug.
Did fresh install WITH the update you did. It works.

Thank you very much!

For future reference, where are the settings saved?
