### ISSUE TITLE
Eternal download loop

### ISSUE THREAD

**Issue by NickDevoctomy** [AbdBarho/stable-diffusion-webui-docker#182]
Running the first download command in my WSL distro results in a looping download process, seemingly downloading the same files over and over

`docker compose --profile download up --build`

**Hardware / Software**
 - OS: Windows 11 / Ubuntu 22.04.01 LTS WSL2 distro
 - WIndows version : 22H2 Build 22621.675
 - WSL version :  2
 - Docker Version: 4.13.0
 - Docker compose version: 2.12.0
 - Repo version: master 5b4acd605df682e8617cfda98bf0527d691ea827
 - RAM: 32gb
 - GPU/VRAM: 3090Ti 24gb

**Steps to Reproduce**
1. Open WSL2 distro in Windows terminal
2. Checkout repository using git command
3. Change to repo folder,
4. Run following command

`docker compose --profile download up --build`

5. Same files get downloaded over and over (please see attached logs)
 
[logs.txt](https://github.com/AbdBarho/stable-diffusion-webui-docker/files/9877738/logs.txt)

**Comment by DevilaN** [comment]
Where is the loop?
I can see, that some of files has been downloaded and others not yet.
```
grep complete logs.txt 
webui-docker-download-1  | 10/27 08:17:35 [NOTICE] Download complete: [MEMORY][METADATA]v1-5-pruned-emaonly.ckpt
webui-docker-download-1  | 10/27 08:17:53 [NOTICE] Download complete: /data/RealESRGAN/RealESRGAN_x4plus_anime_6B.pth
webui-docker-download-1  | 10/27 08:17:54 [NOTICE] Download complete: /data/LDSR/project.yaml
webui-docker-download-1  | 10/27 08:19:57 [NOTICE] Download complete: /data/RealESRGAN/RealESRGAN_x4plus.pth
webui-docker-download-1  | 10/27 08:26:11 [NOTICE] Download complete: /data/StableDiffusion/v1-5-pruned-emaonly.ckpt
webui-docker-download-1  | 10/27 08:27:05 [NOTICE] Download complete: /data/GFPGAN/GFPGANv1.4.pth
```

Following info from bottom of your log fille states that those two files are remaining to download. There is no info before about finishing or redownload for those:
```
webui-docker-download-1  |  *** Download Progress Summary as of Thu Oct 27 08:30:40 2022 ***
webui-docker-download-1  | ===============================================================================
webui-docker-download-1  | [#6bf1cc 1.5GiB/3.9GiB(39%) CN:1 DL:5.8MiB ETA:7m2s]
webui-docker-download-1  | FILE: /data/StableDiffusion/model.ckpt
webui-docker-download-1  | -------------------------------------------------------------------------------
webui-docker-download-1  | [#753d59 1.5GiB/1.8GiB(80%) CN:1 DL:5.8MiB ETA:1m3s]
webui-docker-download-1  | FILE: /data/LDSR/model.ckpt
```
Can you clarify which files are being downloaded over and over?

**Comment by NickDevoctomy** [comment]
I believe this is downloaded over and over

`/data/StableDiffusion/model.ckpt`

**Comment by NickDevoctomy** [comment]
or is it attempting to download all files at the same time?

**Comment by NickDevoctomy** [comment]
will run again, maybe the logs are confusing me.

**Comment by NickDevoctomy** [comment]
Okay, my apologies, please disregard, it just seems to be much slower than it has previously been for me.  And I misread the logs thinking the same files were being downloaded over and over.
