### ISSUE TITLE
Weird interface layout in automatic

### ISSUE THREAD

**Issue by DevilaN** [AbdBarho/stable-diffusion-webui-docker#183]
**Describe the bug**
After upgrading some time ago regular layout changed to "flex" with stretches everything to tiles and some of buttons that previously has been hidden are now visible all time.
![obraz](https://user-images.githubusercontent.com/12526613/198515562-671dbe64-0e58-4beb-b7ca-bf959e597f62.png)

**Which UI**
Auto

**Hardware / Software**
Seems not hardware / software relevant. Everything else except UI look seems to work fine.
Checked if this is browser problem, but both Firefox 106 and Chrome 106.0.5249.119 shows layout the same way.

**Steps to Reproduce**
Sorry. It just is like that. But additional research shows that it is working with commit `5122f83c0f820f7d06a6a51a81ba8b9c1b7d6110` and next commit `49ad173e95bc417131f716b5d8055460f2859f89` and all other later are with broken UI.

**Additional context**
IDK if anybody else has such problem or this is like it supposed to look like right now.
Also I've been looking at issues in auto repository, but found nothing relevant.
No extensions installed. Also I've cleaned `data/config/auto/` directory to make sure that this is not a problem with some previous configuration.

**Comment by AbdBarho** [comment]
@DevilaN I think this is the intended behaviour, I think it is related to gradio, and probably the layout changed between the different versions.

The same can be seen in `hlky`s fork.

**Comment by AbdBarho** [comment]
@DaVinniCode I am pretty sure the `history` tab was moved to an  extension https://github.com/yfszzx/stable-diffusion-webui-images-browser

**Comment by DevilaN** [comment]
@AbdBarho, ok but it has been working fine with previous gradio version? Right now interface is barely useable. Basic functionality like right clicking [GENERATE] button to access "generate forever" is broken, and other things are also f-word up.

I've tried and despite of version of image has not changed between `49ad173e95bc417131f716b5d8055460f2859f89` and `1211e9c5de17a492756dfc4c3dff72fa53d52e48`, the `49ad17` commit still does not work properly even if forcing docker to build image (so it will not use cached image from build from commit `1211e9`).
Also checked by not forcing downgrade of gradio from 3.5 to 3.4.1 but even then interface remains bulky.
I've checked also colab notebook: https://github.com/TheLastBen/fast-stable-diffusion - it seems that it uses latest version of A1111 and there are no problems with interface at all.

Still digging...

**Comment by AbdBarho** [comment]
@DevilaN it is probably related to the 1000 errors in the browser's console

![image](https://user-images.githubusercontent.com/24505302/199171807-fcec7717-4de8-40bd-a195-e63eb8dc9245.png)

it seems like a problem with svelte on the gradio side.

**Comment by DevilaN** [comment]
@AbdBarho, I don't have those errors. Only warnings from svelte about no corresponding translation to interface elements for my browser default language settings. Would you be so kind to provide some of those error messages? I hope it would lead us to actual source of problem.

**Comment by AbdBarho** [comment]
Ok now for whatever reasons the errors don't appear in the console. weird.

That being said, if you didn't see the errors yet you saw the weird layout, these error are probably unrelated.

**Comment by pirahtays** [comment]
> I've checked also colab notebook: https://github.com/TheLastBen/fast-stable-diffusion - it seems that it uses latest version of A1111 and there are no problems with interface at all.
> 
> Still digging...

I was having the same issue and took a look here.  Looks like that colab has 3 post fixes it applies to the A1111 repo

```
!sed -i 's@gpu_call).*@gpu_call) \n        demo.queue(concurrency_count=111500)@' /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py
!sed -i 's@css = "".*@with open(os.path.join(script_path, "style.css"), "r", encoding="utf8") as file:\n        css = file.read()@' /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py
!sed -i 's@min-height: 4.*@min-height: 5.5em;@g' /content/gdrive/MyDrive/sd/stable-diffusion-webui/style.css
```

I was able to apply this same patch and it appears to have corrected the issue:
```
RUN <<EOF
sed -i 's@gpu_call).*@gpu_call) \n        demo.queue(concurrency_count=111500)@' ${ROOT}/webui.py
sed -i 's@css = "".*@with open(os.path.join(script_path, "style.css"), "r", encoding="utf8") as file:\n        css = file.read()@' ${ROOT}/modules/ui.py
sed -i 's@min-height: 4.*@min-height: 5.5em;@g' ${ROOT}/style.css  
EOF
```

I haven't investigated yet fully why this is needed unless it's just a bug in the A1111 repo.

**Comment by DevilaN** [comment]
Yup! That fixes it!
@pirahtays: Your patch places fixes in a place that would bust docker cache and image layers. It would be better to place fixes on the bottom of Dockerfile, so it is applied anyway.

**Comment by pirahtays** [comment]
> Yup! That fixes it! @pirahtays: Your patch places fixes in a place that would bust docker cache and image layers. It would be better to place fixes on the bottom of Dockerfile, so it is applied anyway.

I'm not seeing that happen when I run.  Where it's placed it's only going to bust the cache if those lines change or the webui code changes which would require the cache to be busted?

```
 => CACHED [stage-2  2/15] RUN pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113                                                                                            0.0s
 => CACHED [stage-2  3/15] RUN apt-get update && apt install fonts-dejavu-core rsync git jq moreutils -y && apt-get clean                                                                                                                    0.0s
 => CACHED [stage-2  4/15] RUN <<EOF (git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git...)                                                                                                                              0.0s
 => CACHED [xformers 2/3] RUN apk add aria2                                                                                                                                                                                                  0.0s
 => CACHED [xformers 3/3] RUN aria2c --dir / --out wheel.whl 'https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/download/2.1.0/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl'                                           0.0s
 => CACHED [stage-2  5/15] COPY --from=xformers /wheel.whl xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl                                                                                                                                 0.0s
 => CACHED [stage-2  6/15] RUN pip install xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl && rm xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl                                                                                         0.0s
 => CACHED [download 2/8] RUN <<EOF (cat <<'EOE' > /clone.sh...)                                                                                                                                                                             0.0s
 => CACHED [download 3/8] RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6   && rm -rf data assets **/*.ipynb                                                 0.0s
 => CACHED [download 4/8] RUN . /clone.sh stable-diffusion https://github.com/CompVis/stable-diffusion.git 69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc   && rm -rf assets data/**/*.png data/**/*.jpg data/**/*.gif                             0.0s
 => CACHED [download 5/8] RUN . /clone.sh CodeFormer https://github.com/sczhou/CodeFormer.git c5b4593074ba6214284d6acd5f1719b6c5d739af   && rm -rf assets inputs                                                                             0.0s
 => CACHED [download 6/8] RUN . /clone.sh BLIP https://github.com/salesforce/BLIP.git 48211a1594f1321b00f14c9f7a5b4813144b2fb9                                                                                                               0.0s
 => CACHED [download 7/8] RUN . /clone.sh k-diffusion https://github.com/crowsonkb/k-diffusion.git f4e99857772fc3a126ba886aadf795a332774878                                                                                                  0.0s
 => CACHED [download 8/8] RUN . /clone.sh clip-interrogator https://github.com/pharmapsychotic/clip-interrogator 2486589f24165c8e3b303f84e9dbbea318df83e8                                                                                    0.0s
 => CACHED [stage-2  7/15] COPY --from=download /git/ /stable-diffusion-webui                                                                                                                                                                0.0s
 => CACHED [stage-2  8/15] RUN mkdir /stable-diffusion-webui/interrogate && cp /stable-diffusion-webui/repositories/clip-interrogator/data/* /stable-diffusion-webui/interrogate                                                             0.0s
 => CACHED [stage-2  9/15] RUN pip install --prefer-binary --no-cache-dir -r /stable-diffusion-webui/repositories/CodeFormer/requirements.txt                                                                                                0.0s
 => CACHED [stage-2 10/15] RUN <<EOF (cd stable-diffusion-webui...)                                                                                                                                                                          0.0s
-----
 => CACHED [stage-2 11/15] RUN <<EOF (sed -i 's@gpu_call).*@gpu_call) \n        demo.queue(concurrency_count=111500)@' /stable-diffusion-webui/webui.py...)                                                                                  0.0s
-----
 => CACHED [stage-2 12/15] RUN pip install opencv-python-headless   git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379   git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1  0.0s
 => CACHED [stage-2 13/15] COPY . /docker                                                                                                                                                                                                    0.0s
 => CACHED [stage-2 14/15] RUN chmod +x /docker/entrypoint.sh && python3 /docker/info.py /stable-diffusion-webui/modules/ui.py                                                                                                               0.0s
 => CACHED [stage-2 15/15] WORKDIR /stable-diffusion-webui/repositories/stable-diffusion                                                                                                                                                     0.0s
 => exporting to image                                                                                                                                                                                                                       0.0s

```

**Comment by AbdBarho** [comment]
@pirahtays it works! I chose another hacky way to solve it #196 

I guess this is either a misconfiguration in the setup of this project, or a problem upstream.

eitherway, it looks way more usable now.

**Comment by DevilaN** [comment]
@pirahtays As this issue has been closed, this pos  is only for educational value here.
The log output from build you've provided was created after first build with your changes. Each step is already cached in build cache.
If you change anything in step `[stage-2 11/15]`, then following steps cannot be pulled from build cache because docker does not have any knowledge whether your change in step 11/15 altered anything that other layers are using - so it starts over building everything that's in next steps of the Dockerfile.
