### ISSUE TITLE
[Suggestion] Add Mounting to extensions for AUTOMATIC1111 repo

### ISSUE THREAD

**Issue by Corshi** [AbdBarho/stable-diffusion-webui-docker#184]
I just added:
`MOUNTS["${ROOT}/extensions"]="/data/extensions"`
To the mount.sh in stable-diffusion-webui-docker\services\AUTOMATIC1111

It works. Extensions can now be installed in stable-diffusion-webui-docker\data\extensions

I also added line:
`MOUNTS["${ROOT}/models/deepbooru"]="/data/deepbooru"`
Mostly because folder is created in there, but don't seem to be any mounting. I was not using it...

**Comment by AbdBarho** [comment]
Duplicate #172 #148 #176
