### ISSUE TITLE
Auto: Extensions Tab: Installing: OSError: [Errno 18] Invalid cross-device link: '/stable-diffusion-webui/tmp/sd-dynamic-prompts' -> '/stable-diffusion-webui/extensions/sd-dynamic-prompts'

### ISSUE THREAD

**Issue by GeorgiaM-honestly** [AbdBarho/stable-diffusion-webui-docker#199]
**Has this issue been opened before?**

- [x] It is not in the [FAQ]( https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ ), I checked.
- [x] It is not in the [issues]( https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=Invalid+cross-device+link ), I searched.

**Describe the bug**

When attempting to install extensions under the extensions tab (NOTE: webuy.py must be started with --enable-insecure-extension-access if you have either of --listen or --share also in use -- This is a new feature), and then under the available tab, then choosing Dynamic Prompts install by selecting install, the following error is shown in the UI:

``
OSError: [Errno 18] Invalid cross-device link: '/stable-diffusion-webui/tmp/sd-dynamic-prompts' -> '/stable-diffusion-webui/extensions/sd-dynamic-prompts'
``

On the console, this is shown:

webui-docker-auto-1  | Error completing request
webui-docker-auto-1  | Arguments: ('https://github.com/adieyal/sd-dynamic-prompts',) {}
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui.py", line 185, in f
webui-docker-auto-1  |     res = list(func(*args, **kwargs))
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui_extensions.py", line 144, in install_extension_from_index
webui-docker-auto-1  |     ext_table, message = install_extension_from_url(None, url)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui_extensions.py", line 135, in install_extension_from_url
webui-docker-auto-1  |     os.rename(tmpdir, target_dir)
webui-docker-auto-1  | OSError: [Errno 18] Invalid cross-device link: '/stable-diffusion-webui/tmp/sd-dynamic-prompts' -> '/stable-diffusion-webui/extensions/sd-dynamic-prompts'

Similar errors are returned for numerous others on that page when I try to install them such as:

``
OSError: [Errno 18] Invalid cross-device link: '/stable-diffusion-webui/tmp/stable-diffusion-webui-artists-to-study' -> '/stable-diffusion-webui/extensions/stable-diffusion-webui-artists-to-study'
``

**Which UI**

Auto

**Hardware / Software**
 - OS: Linux **Running inside of qemu with pcie passthrough, bare metal OS is Gentoo linux**
 - OS Version: Debian GNU/Linux 11 (bullseye)
 - Docker Version: 20.10.19
 - Docker compose version: 2.11.2
 - Repo version: from master
 - RAM: 32GB
 - GPU/VRAM: Nvidia 2080ti founders/12GB

**Steps to Reproduce**
1. Go to 'Extensions' tab
2. Click on 'Available' sub-tab
3. Click on 'Load from:' (URL should be: https://raw.githubusercontent.com/wiki/AUTOMATIC1111/stable-diffusion-webui/Extensions-index.md )
4. Look for 'Dynamic Prompts' (or any other item) and click on 'Install'
5. Cat explodes
6. Observe error (varies by extension): OSError: [Errno 18] Invalid cross-device link: '/stable-diffusion-webui/tmp/sd-dynamic-prompts' -> '/stable-diffusion-webui/extensions/sd-dynamic-prompts'

**Additional context**
I have not observed users of the auto project filing issues or starting discussions in that repo. It is possible that this is related to running inside of docker, however, I poked around with:

``
docker exec -it webui-docker-auto-1 bash
``

... and was not really able to determine what's going on.

**Comment by AbdBarho** [comment]
@GeorgiaM-honestly I hacked it quickly, can you try from the branch #200 if it works?

**Comment by GeorgiaM-honestly** [comment]
Hello, I'm not a developer or anything like that and I am not entirely sure what you mean. So I hate to do this to ya however... How do I proceed? Thanks for the super fast weekend response!

**Comment by AbdBarho** [comment]
@GeorgiaM-honestly  Did you clone this repository with `git`? or did you just download it as a zip file?

**Comment by GeorgiaM-honestly** [comment]
I used git clone.

**Comment by AbdBarho** [comment]
great, open a terminal in the repo and run the following:
```sh
git fetch
git checkout extensions-hack
```
and then you can try to install the extensions again:
```
docker compose --profile auto up --build
```

**Comment by GeorgiaM-honestly** [comment]
That works! The only issue, which doesn't affect functionality, is during install the animated square / timer counting up is listed twice.

Anything else you'd like me to do?

**Comment by AbdBarho** [comment]
I have merged the branch to master, don't forget to switch back:
```sh
git checkout master
git pull
```
