### ISSUE TITLE
github branch main or master？

### ISSUE THREAD

**Issue by abelzhyb** [AbdBarho/stable-diffusion-webui-docker#209]
when I exec docker compose --profile [ui] up --build ，
https://github.com/TencentARC/GFPGAN    master
git+https://github.com/openai/CLIP            main

get error info below:

 > [stage-2 12/15] RUN pip install opencv-python-headless   git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379   git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1   pyngrok:
#0 0.207 + pip install opencv-python-headless git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 pyngrok
#0 0.620 Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
#0 0.621   Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to /tmp/pip-req-build-_98fx61s
#0 0.624   Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git /tmp/pip-req-build-_98fx61s
#0 124.1   Running command git rev-parse -q --verify 'sha^8d2447a2d918f8eba5a4a01463fd48e45126a379'
#0 124.1   Running command git fetch -q https://github.com/TencentARC/GFPGAN.git 8d2447a2d918f8eba5a4a01463fd48e45126a379
#0 309.8   fatal: unable to access 'https://github.com/TencentARC/GFPGAN.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
#0 309.8   error: subprocess-exited-with-error
#0 309.8
#0 309.8   × git fetch -q https://github.com/TencentARC/GFPGAN.git 8d2447a2d918f8eba5a4a01463fd48e45126a379 did not run successfully.
#0 309.8   │ exit code: 128
#0 309.8   ╰─> See above for output.
#0 309.8
#0 309.8   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 309.8 error: subprocess-exited-with-error
#0 309.8
#0 309.8 × git fetch -q https://github.com/TencentARC/GFPGAN.git 8d2447a2d918f8eba5a4a01463fd48e45126a379 did not run successfully.
#0 309.8 │ exit code: 128
#0 309.8 ╰─> See above for output.
#0 309.8
#0 309.8 note: This error originates from a subprocess, and is likely not a problem with pip.
#0 311.1
#0 311.1 [notice] A new release of pip available: 22.2.2 -> 22.3.1
#0 311.1 [notice] To update, run: pip install --upgrade pip
------
failed to solve: executor failed running [/bin/bash -ceuxo pipefail pip install opencv-python-headless   git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379   git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1   pyngrok]: exit code: 1

**Comment by AbdBarho** [comment]
@abelzhyb it seems like a network failure, what happens if you try again?

**Comment by GeorgiaM-honestly** [comment]
I have seen sporadic temporary failures to resolve github.com in numerous sitations and haven't been able to figure it out. If it persists, at least on linux or linux-like operating systems I do this on a *temporary* basis:

- Get an IP of github.com: dig +short github.com
- Edit /etc/hosts and append the following line:
the-ip-you-got[tab]github.com
- Try again
- Remove that line later

This is a dirty hack and temporary.

**Comment by AbdBarho** [comment]
@GeorgiaM-honestly I have the same problem occasionally, this is likely a problem with github servers, not your local machine.
