### ISSUE TITLE
/bin/bash: line 1: /docker/mount.sh: Permission denied on container startup

### ISSUE THREAD

**Issue by hughk** [AbdBarho/stable-diffusion-webui-docker#21]
Building the container works. Starting the container fails with the following message:

stable-diffusion-webui-docker-model-1  | + /docker/mount.sh
stable-diffusion-webui-docker-model-1  | /bin/bash: line 1: /docker/mount.sh: Permission denied

**Steps to Reproduce**
1. docker compose build
2. docker compose up --build
3. [error...]

**Hardware / Software:**
 - OS: Windows 11/WSL2
 - Docker version
 - GPU: [Nvidia 3090]
 - Docker version: v20.10.17

**Additional context**
Attempted to add a chmod +x /docker/mount.sh before the command is run in dockerfile, the command does execute but does not improve things. Docker seems to work otherwise.

**Comment by El-Fitz** [comment]
I'm facing the same issue on an AWS EC2 Linux instance. Fixed after running `chmod +x ./build/mount.sh` from outside the docker container.

**Comment by AbdBarho** [comment]
I have directly updated the executable status in the git index.

@hughk Can you try again from latest master?

Working on a windows machine makes detecting this problems almost impossible.

**Comment by MiccoHadje** [comment]
I've forked to modify the Shell command in the build to use "//bin/bash" instead of "/bin/bash", which has resolved a similar error for me. On WSL the precedent "/" before the filepath indicates a *nix filepath. After that modification the build was successful for me.

**Comment by AbdBarho** [comment]
what sort of black magic is this?

@MiccoHadje why is this necessary? could you guide to some sort of documentation that explains this behaviour?

The bash command is executed within the miniconda container, I would assume that the rules of WSL don't apply / matter anymore?

**Comment by MiccoHadje** [comment]
> what sort of black magic is this?

Universal Naming Convention (UNC) is what I believe drives this 'trick'. Here's the Microsoft Docs page that talks about it. https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats

Regardless, it works for me :)

**Comment by AbdBarho** [comment]
@MiccoHadje thanks! I will look deeper into it.

One question, did you install docker on windows powershell or inside wsl? and did you run docker on powershell or inside wsl?

> It appears that my system does not see bash at /bin/bash and kept throwing a 'command not found' error at the Shell call.

So the error was thrown [at this line](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/5af482ed8c975df6aa0210225ad68b218d4f61da/build/Dockerfile#L11) when building the container?

**Comment by hughk** [comment]
>  have directly updated the executable status in the git index.

> @hughk Can you try again from latest master?

I have checked and it seems to have moved past this point. Will close when I have confirmed.

**Comment by hughk** [comment]
Have confirmed that it is now working as supposed to on Ubunto 22.04.01/WSL2

**Comment by MiccoHadje** [comment]
> @MiccoHadje thanks! I will look deeper into it.
> 
> One question, did you install docker on windows or inside wsl? and did you run docker on powershell or inside wsl?
> 
> > It appears that my system does not see bash at /bin/bash and kept throwing a 'command not found' error at the Shell call.
> 
> So the error was thrown [at this line](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/5af482ed8c975df6aa0210225ad68b218d4f61da/build/Dockerfile#L11) when building the container?

Yes, that is the line the error was thrown on. I installed Docker on Windows, and run Docker from Powershell.

**Comment by AbdBarho** [comment]
@MiccoHadje Ok, I will update the FAQ, its weird that I can't reproduce this problem...

@hughk glad its working!
