### ISSUE TITLE
Quadro 4000 Not supported On hlky and auto

### ISSUE THREAD

**Issue by schrummy14** [AbdBarho/stable-diffusion-webui-docker#210]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Quadro 4000 nvidia cards with latest drivers are not detected by either UI.

**Which UI**

hlky and auto (have not tried lstein)

**Hardware / Software**
 - OS: [Ubuntu ]
 - OS version:  Ubuntu 20.04.5 LTS
 - WSL version (if applicable): 
 - Docker Version:  20.10.19
 - Docker compose version:  2.12.2
 - Repo version:  master
 - RAM: 32
 - GPU/VRAM: Quadro 4000 2Gb

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by AbdBarho** [comment]
@schrummy14 could you provide some error logs? did it work before the latest driver?

**Comment by schrummy14** [comment]
Hello,
I have not tried other drivers just the latest driver available on ubuntu.
During the building processes it prints "Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx'".

Running the command "docker compose --profile auto up --build" simply exits with "Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]" I don't see any other logs.

**Comment by AbdBarho** [comment]
what is the output if you type `nvidia-smi` in the console?

**Comment by schrummy14** [comment]
`Thu Nov 10 15:00:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.154                Driver Version: 390.154                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro 4000         Off  | 00000000:03:00.0 Off |                  N/A |
| 40%   48C   P12    N/A /  N/A |     12MiB /  1984MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

**Comment by AbdBarho** [comment]
`390.154` is really really old, you need >= `418.81.07` as per the nvidia container toolkit docs: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installation-guide

Also, 2GB of GPU is probably not enough to use any UI, but you can try.

**Comment by schrummy14** [comment]
I haven't found any newer drivers for the Quadro 4000. As far as I can tell, it will always stay in the 300s. No worries. We can close this out.
