### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by lolihopper** [AbdBarho/stable-diffusion-webui-docker#214]
Getting this error when I try and install.

   File "C:\stable-diffustion-webui-master\modules\__init__.py", line 3, in <module>
          from jsonmerge.jsonvalue import JSONValue
ModuleNotFoundError: No module named 'jsonmerge'

I have tried to use "pip install jsonmerge" as well as uninstalling and reinstalling and nothing seems to work.
No clue what could be the issue.

**Comment by AbdBarho** [comment]
@lolihopper please use the template, I can't help like this.

Also, it seems that this is the wrong repo for the issue you are creating.

**Comment by lolihopper** [comment]
ah im dumb lol
