### ISSUE TITLE
Broken Dreambooth Extension for the Stable Diffusion Web UI (`auto`)

### ISSUE THREAD

**Issue by mrauhu** [AbdBarho/stable-diffusion-webui-docker#218]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Dreambooth Extension not working, because of:

* different CUDA version for `torch`, the right one is installed via:
    ```
    TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"
    ```
* missing the `gcc` package.

**Which UI**

auto

**Hardware / Software**
 - OS: Debian GNU/Linux x64
 - OS version: 11.5
 - WSL version (if applicable): 2
 - Docker Version: 20.10.20
 - Docker compose version:  2.12.1
 - Repo version: https://github.com/AbdBarho/stable-diffusion-webui-docker/commit/53ac3601d73ca66ad13ee46788e3888db9363c8d
 - RAM: 32 GB
 - GPU/VRAM: Nvidia GeForce RTX 3090 24 GB

**Steps to Reproduce**
1. Go to *Extensions — Available* tab.
2. Click on the *[Load from]* button.
3. Scroll down to the *Dreambooth* extension and click *[Install]*.
4. Restart Web UI using:

    ```
    docker compose --profile=auto stop
    docker compose --profile=auto up
    ```
5. See error.

**Comment by AbdBarho** [comment]
@mrauhu there are 2 points here:

1. if you want to install any additional dependencies for any extension, you can create a script `data/config/auto/startup.sh` and put whatever commands you want in it:
```sh
echo "installing stuff for dreambooth"
apt-get update && apt-get install gcc -y
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
```
No need to modify the container

2. that being said, if the auto webui works with the newer pytorch versions without any problems, we can change the default version in the container, no need to make it complicated with build args.

**Comment by mrauhu** [comment]
1. It's good solution for the installing dependencies via APT.
PyTorch is heavy and installing it in the `startup.sh` will be add ~2GB to the total container size.

2. It's great, if you can update a version of the PyTorch in the `auto/Dockerfile`.

**Comment by AbdBarho** [comment]
@mrauhu I will test the auto UI with the new pytorch version and update it tomorrow.

**Comment by AbdBarho** [comment]
cu11.6 seems to work fine, it is now the default
