### ISSUE TITLE
model.ckpt not found when deployed to GCP Cloud Run

### ISSUE THREAD

**Issue by flamz3d** [AbdBarho/stable-diffusion-webui-docker#224]
I built and ran this docker on a linux VM without a hitch, then tagged and pushed the image to GCP so I can run it via Cloud Run 
Everything seems to go well, until I get 

**Can't run without a checkpoint. Find and place a .ckpt file into any of those locations. The program will exit.**

here's the full log:

`mkdir: created directory '/data/.cache'
Mounted .cache
mkdir: created directory '/data/LDSR'
Mounted LDSR
mkdir: created directory '/data/Hypernetworks'
Mounted Hypernetworks
mkdir: created directory '/data/VAE'
Mounted VAE
mkdir: created directory '/data/GFPGAN'
Mounted GFPGAN
mkdir: created directory '/data/RealESRGAN'
Mounted RealESRGAN
mkdir: created directory '/data/ScuNET'
Mounted ScuNET
Mounted .cache
mkdir: created directory '/data/StableDiffusion'
Mounted StableDiffusion
mkdir: created directory '/data/embeddings'
Mounted embeddings
mkdir: created directory '/data/ESRGAN'
Mounted ESRGAN
Mounted config.json
mkdir: created directory '/data/Deepdanbooru'
Mounted Deepdanbooru
mkdir: created directory '/data/SwinIR'
Mounted SwinIR
Mounted ui-config.json
Mounted BSRGAN
mkdir: created directory '/data/Codeformer'
Mounted Codeformer
mkdir: created directory '/data/config/auto/extensions'
Mounted extensions
+ python3 -u ../../webui.py --listen --port 7860 --ckpt-dir /stable-diffusion-webui/models/Stable-diffusion
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
Removing empty folder: /stable-diffusion-webui/models/BSRGAN
No checkpoints found. When searching for checkpoints, looked at:
- file /stable-diffusion-webui/model.ckpt
- directory /stable-diffusion-webui/models/Stable-diffusion
- directory /stable-diffusion-webui/models/Stable-diffusion
Can't run without a checkpoint. Find and place a .ckpt file into any of those locations. The program will exit.`

**Which UI**
auto-cpu 

**Hardware / Software**
 - Docker Version: 20.10. 14.
 - Docker compose version: 1.47.3

**Comment by AbdBarho** [comment]
you need to download the data / models and mount them correspondingly. the image is just code, it cannot do anything on its own.

basically, all of the stuff is downloaded to a folder called `data`, which should be mounted to `/data` in the container.

see the setup instructions in the wiki and the `docker-compose.yml` in for more info.

**Comment by AbdBarho** [comment]
Also, due to the structure of this repo, and the amount of data required, I don't think cloud run is the right tool, maybe compute engine vms are a better fit.
