### ISSUE TITLE
My build issues resolved

### ISSUE THREAD

**Issue by SuddenDevelopment** [AbdBarho/stable-diffusion-webui-docker#23]
update to latest windows 10 release 2021H2 (required for WSL to see the GPU)
update to WSL2 (download and switch to version 2)
install docker (duh, Docker Desktop)
wsl2 dos2unix dockerfile ( these were not so obvious, some characters in the files werent going well)
wsl2 dos2unix ./build/mount.sh

**Comment by AbdBarho** [comment]
Thank you @SuddenDevelopment ! I will add this info to the FAQ page just in case anyone faces the same problem!

I pushed an update that should fix the line endings problem.

**Comment by SuddenDevelopment** [comment]
great, thanks!
