### ISSUE TITLE
Images not saved to subdirectories (auto)

### ISSUE THREAD

**Issue by LeagueOfPoro** [AbdBarho/stable-diffusion-webui-docker#236]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Images are saved directly to  `/output` directory instead of a subdirectory like `/output/txt2img`

**Which UI**

auto

**Hardware / Software**
Tested on two machines
 - OS: Windows 11
 - OS version: 22H2
 - WSL version (if applicable): 2
 - Docker Version: 20.10.21
 - Docker compose version: v2.12.2
 - Repo version: from master
 - RAM: 64GB and 32GB
 - GPU/VRAM: TITAN RTX 24GB, RTX 3080 10GB

**Steps to Reproduce**
1. Install the repo according to the Setup
2. Generate an image in txt2img
3. Observe the image saved to `/output` directory instead of `/output/txt2img`

**Additional context**
Tested on two physical machines. Clean install from master

**Comment by AbdBarho** [comment]
@LeagueOfPoro why is this a problem?

if we want to change the folders, we also have to update it for the other UI's, this will be a breaking change and will require a major version bump

**Comment by LeagueOfPoro** [comment]
Saving images into directories based on the method used (e.g. txt2img) is the default behavior of the Auto. 

The folders are even created in `entrypoint.sh`:
`mkdir -p /output/saved /output/txt2img-images/ /output/img2img-images /output/extras-images/ /output/grids/ /output/txt2img-grids/ /output/img2img-grids/`

**Comment by AbdBarho** [comment]
Fixed in #254
