### ISSUE TITLE
Add --enable-insecure-extension-access to install extension with auto

### ISSUE THREAD

**Issue by Sulexa** [AbdBarho/stable-diffusion-webui-docker#242]
**Has this issue been opened before?**

- [ x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

When trying to install an extension i have this :
[Bug]: AssertionError: extension access disabed because of commandline flags

**Which UI**

auto

**Hardware / Software**
 - OS: windowds 11
 - OS version: 22H2 (OS Build 22621.819)
 - WSL version (if applicable): docker-desktop V2d
 - Docker Version: Docker Desktop 4.13.0 (89412)
 - Docker compose version:v2.12.0
 - Repo version: release 3.2.0
 - RAM: 32
 - GPU/VRAM: 3090 24giga

**Steps to Reproduce**
1. Go to extensions
2. Go to availables
3. Try to install dreambooth

**Additional context**
By adding --enable-insecure-extension-access to the CLI_ARGS it work, it's linked to this change :
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ccf1a15412ef6b518f9f54cc26a0ee5edf458108#diff-15faa364afc7fd40ccc1e6a38893b2dac62c846715710dfbe44f25fb65205440

**Comment by AbdBarho** [comment]
@Sulexa that is the intended behavior:

https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Usage#extensions

maybe we should enable it by default.

**Comment by Sulexa** [comment]
Oh my bad, i did not see there was an entry in the wiki for extensions.
Now that there is a tab to install extension maybe it should be ? The error is not clear when you try to install an extension without --enable-insecure-extension-access through the UI...
