### ISSUE TITLE
137 error on a low resources VPS

### ISSUE THREAD

**Issue by b1tdreamer** [AbdBarho/stable-diffusion-webui-docker#258]
**Has this issue been opened before?**

- [X ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I just installed this docker on an VPS without GPU and 3.1Gb free memory and receive a 137 error, it seems there's no enough RAM for running it. Is there a posibility to work with it even if it takes a lot of time?
It would work if the used model is lighter?

Thanks

**Which UI**

auto-cpu

**Hardware / Software**

- OS: SMP Debian 4.19.260-1 (2022-09-29)
- OS version: Debian GNU/Linux 10 (buster)
- WSL version (if applicable): -
- Docker Version: 20.10.21
- Docker compose version: Docker Compose version v2.12.2
- Repo version: from master
- RAM: 4Gb
- GPU/VRAM: -

**Steps to Reproduce**

1. Run docker-compose --profile auto-cpu up --build

**Additional context**
.
webui-docker-auto-cpu-1  | Removing empty folder: /stable-diffusion-webui/models/BSRGAN
webui-docker-auto-cpu-1  | LatentDiffusion: Running in eps-prediction mode
webui-docker-auto-cpu-1 exited with code 137

**Comment by AbdBarho** [comment]
@b1tdreamer oof, that would definitely be a challenge...

I have no immediate solution in mind, but I know that the auto UI takes around 14GB of RAM just for startup, maybe you can setup your swap large enough to accommodate for this.

> It would work if the used model is lighter?

you can try using a fp16 version of your model, it might help.

**Comment by DevilaN** [comment]
4GB RAM? No way :(
Using a lot of swap might be possible, but do not go this way.
Google Colab is FREE. You could generate 1 image per 10 seconds. This will probably generate more images in 1 minute than your VPS in 1 day.
