### ISSUE TITLE
Can't get Stable Diffusion UP

### ISSUE THREAD

**Issue by Paulie420** [AbdBarho/stable-diffusion-webui-docker#275]
**Describe the bug**

docker compose --profile auto-cpu up --build
Sending build context to Docker daemon   2.69kB
1 error occurred:
        * Error response from daemon: dockerfile parse error line 8: unknown instruction: CAT
-----
I get this error no matter which UI I try to run 'docker compose --profile ANY up --build' with. I'm using a Proxmox VM with Ubuntu 22.04 - maybe I'm an idiot and need to run on actual hardware??

**Which UI**

auto-cpu

**Hardware / Software**

- OS: Ubuntu 22.04
- Docker Version: 20.10.22
- Docker compose version: 2.3.3
- RAM: 4G
- GPU/VRAM: 0

**Steps to Reproduce**

Run any of the 'docker compose --profile ANY up --build' commands;
paulie420@StableDiffusion:~/stable-diffusion-webui-docker$ docker compose --profile auto up --build
Sending build context to Docker daemon   2.69kB
1 error occurred:
        * Error response from daemon: dockerfile parse error line 8: unknown instruction: CAT

paulie420@StableDiffusion:~/stable-diffusion-webui-docker$ docker compose --profile sygil up --build
Sending build context to Docker daemon  1.705kB
1 error occurred:
        * Error response from daemon: dockerfile parse error line 14: unknown instruction: GIT

**Additional context**
Sorry that this is a very rookie question/issue - I was hoping that I could run Stable Diffusion on my server and have a play. Thanks - I'm a tryin!!

**Comment by AbdBarho** [comment]
I am sorry to tell you that 4GB RAM is not enough, you need at least 16.

If you want I can still try to debug this with you.

If you want to try SD there are Google Collab options that are free.

Apologies and Merry Christmas.

**Comment by Paulie420** [comment]
I have plenty of memory... lemme push it up to 16GB and retry.

**Comment by AbdBarho** [comment]
Now we are talking!

can you try
```sh
docker pull docker/dockerfile:latest


DOCKER_BUILDKIT=1 docker compose --profile auto-cpu up --build
```
[more info here](https://docs.docker.com/build/buildkit/#getting-started)

**Comment by Paulie420** [comment]
Ok, well disco on that... heres the output:
`paulie420@StableDiffusion:~/stable-diffusion-webui-docker$ docker pull docker/dockerfile:latest
latest: Pulling from docker/dockerfile
1328b32c40fc: Pull complete 
Digest: sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc
Status: Downloaded newer image for docker/dockerfile:latest
docker.io/docker/dockerfile:latest
paulie420@StableDiffusion:~/stable-diffusion-webui-docker$ DOCKER_BUILDKIT=1 docker compose --profile auto-cpu up --build
[+] Building 285.0s (36/36) FINISHED       `

Ok - its doing its thing still, I suppose it might go up after it finishes? Could you explain what you did there?
I assume you pulled the newest dockerfile for Stable Diffusion, but what was the buildkit part??
(And, thanks for playing w/ me... :P)

**Comment by AbdBarho** [comment]
the problem you are facing was because your docker version did not enable buildkit, if you want to enable this permanently, see the link that I sent to update the docker config.


Please note that running on cpu is slow and you might face errors since it is all just a hack...

Unfortunately, all other UIs require a gpu.

**Comment by Paulie420** [comment]
Understood, on all - maybe the FAQ should suggest the above; well, for dummies installing on Ubuntu 22.04. :P At any rate, I may spin it up on a different machine that has a 3080... thanks for getting my discs spinning. 

- I am more interested in poking around Stable Diffusion that running it, so you've got me sorted. Thank you!!
-

**Comment by DevilaN** [comment]
@Paulie420: Unfortunately each linux distro is different and comes with preconfigured docker in specific way. On my gentoo everything is working out of the box (except I needed to install nvidia-cuda-toolkit from overlay).
Probably most popular linux flavors like ubuntu could be covered better in howto, but still it is a lot of work to install other distributions and making tutorials for them. In the end there are always some edge cases when user changed something and it no longer works like intended. Most of the time giving direct support is probably better :-)
