### ISSUE TITLE
Custom WebUI SHA

### ISSUE THREAD

**Issue by SuddenDevelopment** [AbdBarho/stable-diffusion-webui-docker#28]
It looks like you set the webui repo to a specific stable version. 

When I go look at that project it is frequently being updated.

How can I easily update my container? Do I need to rebuild it from main each time?

be a nice option, thanks

**Comment by AbdBarho** [comment]
Hi @SuddenDevelopment, you are correct, I pin to a specific version because it helps in the reproducibility, and although there are many updates to the project, stuff gets broken all of the time.

That being said, I will consider this to be a feature request, for anyone who might need it.

**Comment by AbdBarho** [comment]
@SuddenDevelopment Feature added https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/082876aab38dceb9c523e3f5315b9649edb86102/docker-compose.yml#L8-L10

You can now change the SHA and run `docker compose up --build` and have that commit. This will only rebuild part of the container, takes ~2 minutes on my machine.
