### ISSUE TITLE
After successfully running the first time, when I try to run the auto docker image, it won't start

### ISSUE THREAD

**Issue by vcalexa** [AbdBarho/stable-diffusion-webui-docker#289]
**Has this issue been opened before?**

- [ x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

After successfully running the first time, when I try to run the auto docker image from Docker Desktop app, it won't start.
I get the following error:
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
2023-01-11 23:24:56 Removing empty folder: /stable-diffusion-webui/models/BSRGAN
2023-01-11 23:24:57 No checkpoints found. When searching for checkpoints, looked at:
2023-01-11 23:24:57  - file /stable-diffusion-webui/model.ckpt
2023-01-11 23:24:57  - directory /stable-diffusion-webui/models/Stable-diffusion
2023-01-11 23:24:57 Can't run without a checkpoint. Find and place a .ckpt file into any of those locations. The program will exit.

**Which UI**

auto 

**Hardware / Software**

- OS:Windows 10
- OS version: 
- Docker Version: 20.10.21
- Docker compose version: v2.13.0
- Repo version: 4.0.0
- RAM: 16GB
- GPU/VRAM: RTX 3070 8GB

**Steps to Reproduce**

1. run the download and the auto docker compose commands
2. stop the auto container
3. try to start the auto image from docker desktop

**Comment by AbdBarho** [comment]
> try to start the auto image from docker desktop

The docker compose file has important additional configs, docker desktop does not provide thes. Please always use the `docker compose` commands as described in the wiki.

**Comment by vcalexa** [comment]
Thanks for the reply @AbdBarho 
Of course running the docker compose command works, but I thought there would be a quicker way.
Since the images are already built, I thought I wouldn't have to wait 5-10 min again after I kill the container.

**Comment by AbdBarho** [comment]
@vcalexa it won't build again, you can try it.

**Comment by vcalexa** [comment]
Now I get this error, and I remember to fix it I need to run the build command for the download image:

=> CACHED [stage-2 16/16] WORKDIR /stable-diffusion-webui                                                             0.0s  => exporting to image                                                                                                 0.1s  => => exporting layers                                                                                                0.0s  => => writing image sha256:d0013f3453b6edd39ef815091e0c353c3574c477cd5cf665730a6be7bae45e57                           0.0s  => => naming to docker.io/library/sd-auto:18                                                                          0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
time="2023-01-12T17:49:48+01:00" level=warning msg="container e1fde24dfb80db53e4249701ec23e2d5250ad112c79fd998a9b63cefb6866137 is missing com.docker.compose.container-number label"
time="2023-01-12T17:49:48+01:00" level=warning msg="container e1fde24dfb80db53e4249701ec23e2d5250ad112c79fd998a9b63cefb6866137 has invalid com.docker.compose.container-number label: "
time="2023-01-12T17:49:48+01:00" level=warning msg="container a1d669cd60000361a5df165f2236edec73b4e0ea5a9f1ba7f24475e40fa952e1 is missing com.docker.compose.container-number label"
time="2023-01-12T17:49:48+01:00" level=warning msg="container a1d669cd60000361a5df165f2236edec73b4e0ea5a9f1ba7f24475e40fa952e1 has invalid com.docker.compose.container-number label: "
[+] Running 0/1
 - Container hardcore_maxwell  Recreate                                                                                0.0s strconv.Atoi: parsing "": invalid syntax

**Comment by AbdBarho** [comment]
@vcalexa you are using v18 which is very old, can you try pulling again from master?

**Comment by vcalexa** [comment]
After pulling new version and restarting, it works!!
Only takes ~ 2 min the second time.
Thanks @AbdBarho
