### ISSUE TITLE
"unknown flag --profile" on arm based device

### ISSUE THREAD

**Issue by Pesoen** [AbdBarho/stable-diffusion-webui-docker#291]
**Has this issue been opened before?**

- [ X ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ X ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I cloned the git, cd into it and try to run the "docker compose --profile download up --build" command, and get the "unknown flag --profile" error. also tried "docker-compose --profile download up --build" since my install uses the dash.

**Which UI**

did not make it that far, so none?

**Hardware / Software**

- OS: Raspian
- OS version: Raspbian GNU/Linux 10 (buster)
- WSL version (if applicable): 
- Docker Version: 20.10.22
- Docker compose version: 1.21.0,
- Repo version: 5.0.0
- RAM: 8GB
- GPU/VRAM: 512MB

**Steps to Reproduce**

1. git clone the repo.
2. cd into it.
3. run the command

**Additional context**
Trying to install onto a raspberry pi, just to see if i can get any pictures out of it, even if it will take forever to complete even one picture. purely for giggles and to see if its possible. been wanting to have a stable diffusion installed on it since i first had fun with it on my main rig, but i get a BSOD after 4 pictures, and i am still not sure why, but first 4 pictures are fine, after that it will BSO during the 5th.

**Comment by Pesoen** [comment]
forgot to add, tried the docker-compose-plugin without success..

**Comment by AbdBarho** [comment]
> Docker compose version: 1.21.0

you need docker compose v2 !!

**Comment by nonetrix** [comment]
This also happens on Podman
