### ISSUE TITLE
Scripts are copied and cannot be removed easily 

### ISSUE THREAD

**Issue by DevilaN** [AbdBarho/stable-diffusion-webui-docker#295]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Although my cat didn't exploded, I encountered problem with script added to `stable-diffusion-webui-docker/data/config/auto/scripts` directory.
Adding it works fine. It is copied to internal directory inside container, but removing file from scripts directory does not remove copied file from container's internal directory. After testing some script from web and then removing it it still behaves as script file is there.

**Which UI**

auto

**Hardware / Software**

Doesn't matter.

**Steps to Reproduce**

1. Copy script file to `stable-diffusion-webui-docker/data/config/auto/scripts`
2. Run `auto`. Script is there.
3. Stop and remove script file from directory mentioned in 1.
4. Run `auto` again. Script is still there splitting its own messages / errors during startup.

**Additional context**
I suggest linking files instead of copying them and during container startup, using entrypoint script to check for dead links and remove it.

**Comment by AbdBarho** [comment]
Reason:

https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/13dfd4eba5286fa2264670a6e3c177079c3d42d4/services/AUTOMATIC1111/entrypoint.sh#L14-L15

Will fix soon.

**Comment by AbdBarho** [comment]
Could you try again from latest master?

**Comment by DevilaN** [comment]
Sorry, but due to lack of disk space I've pruned docker build cache and I have weak Internet connection @ home so, I can check it on Monday.

**Comment by DevilaN** [comment]
Tried today's latest. Unfortunately something went wrong...

    webui-docker-auto-1  | '/data/config/auto/scripts/embedding_to_png.py' -> '/stable-diffusion-webui/scripts/embedding_to_png.py'
    webui-docker-auto-1  | cp: cannot create symbolic link '/stable-diffusion-webui/scripts/embedding_to_png.py' to '/data/config/auto/scripts/embedding_to_png.py': File exists
    webui-docker-auto-1 exited with code 1

**Comment by AbdBarho** [comment]
@DevilaN could you try running again but adding `f` to the flags of this line?
https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/510f9fab2b776cd495d5011a1e5ef89e5365fd83/services/AUTOMATIC1111/entrypoint.sh#L8

**Comment by DevilaN** [comment]
Yup. `f` flag really forced things like it should be from empirical side.

There are still dead symlinks inside container:
```
# find . -xtype l
./embedding_to_png.py
./test-it.py
./test-it2.py
./test.xxx

root@e342de9172ba:/stable-diffusion-webui/scripts# ls -alh
[...]
lrwxrwxrwx 1 root root   36 Jan 23 20:08 test-it.py -> /data/config/auto/scripts/test-it.py
lrwxrwxrwx 1 root root   37 Jan 23 20:39 test-it2.py -> /data/config/auto/scripts/test-it2.py
lrwxrwxrwx 1 root root   37 Jan 23 20:41 test-it3.py -> /data/config/auto/scripts/test-it3.py
lrwxrwxrwx 1 root root   34 Jan 23 16:22 test.xxx -> /data/config/auto/scripts/test.xxx
[...]
```

But at least it is working again.

**Comment by AbdBarho** [comment]
Then we probably also need a
```
find /stable-diffusion-webui/scripts -maxdepth 1 -type l -delete
```
before it.

**Comment by AbdBarho** [comment]
You know what, I am going to check, if `auto` finds all scripts recursivly in the scripts folder, then we can probably mount our folder in the original one and then we don't need to worry about all these symlinks.

**Comment by DevilaN** [comment]
Great! That will solve it without creating new problems (hope so).

**Comment by DevilaN** [comment]
Any news about this issue?
I saw other tries committed to resolve this issue, but nothing worked so far as intended.

**Comment by AbdBarho** [comment]
I added a fix to master

**Comment by DevilaN** [comment]
Fix fixes it :)
