### ISSUE TITLE
Auto-CPU container exits while loading model

### ISSUE THREAD

**Issue by schech1** [AbdBarho/stable-diffusion-webui-docker#296]
**Has this issue been opened before?**

- [X] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I start the container with:
`docker compose --profile auto-cpu  up --build`
I have no GPU, therefore auto-cpu.

The container spins up, but exits during loading the model

```
Mounted .cache

Mounted LDSR

Mounted BLIP
Mounted Hypernetworks
Mounted VAE
Mounted GFPGAN
Mounted RealESRGAN
Mounted Deepdanbooru
Mounted ScuNET
Mounted .cache
Mounted StableDiffusion
Mounted embeddings
Mounted ESRGAN
Mounted config.json
Mounted SwinIR
Mounted MiDaS
Mounted ui-config.json
Mounted BSRGAN
Mounted Codeformer
Mounted extensions
+ python3 -u webui.py --listen --port 7860 --no-half --precision full
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
Removing empty folder: /stable-diffusion-webui/models/BSRGAN
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [cc6cb27103] from /stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
exited with code 137

```

**Which UI**

 auto-cpu 

**Hardware / Software**

- OS:  Linux
- OS version: Linux 6.0.0-0.deb11.6-amd64
- WSL version (if applicable): -
- Docker Version: <5:20.10.22~3-0~debian-bullseye>
- Docker compose version: Compose version v2.14.1
- Repo version:  from master
- RAM: 16GB
- GPU/VRAM: No GPU -> (Intel NUC10i7FNK)

**Steps to Reproduce**

1. Run `docker compose --profile auto-cpu  up --build`

**Comment by DevilaN** [comment]
Hi!
Exit code 137 in most cases means not enough RAM (Out Of Memory Kill)
Your linux box shares RAM with docker. What is your RAM usage when not using docker? Please run `LANG=C free` command and paste results here.

**Comment by eggplants** [comment]
In my environment, same error has resolved with increasing memory.

If you are using Docker Desktop, adjust from `Settings > Resources > Memory`.
