### ISSUE TITLE
[AUTO] Instalation of transformers >=4.24 not handled properly in Dockerfile

### ISSUE THREAD

**Issue by DevilaN** [AbdBarho/stable-diffusion-webui-docker#301]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

My cat is still intact, but I've found out that there is file `'=4.24'` in `/` directory of image.
This is probably due to bad syntax with pip command in Dockerfile:
`pip install -U opencv-python-headless transformers>=4.24` redirects output to `=4.24` file.

**Which UI**

auto, auto-cpu

**Hardware / Software**

Does not matter.

**Steps to Reproduce**

1. `docker exec  [RUNNING_CONTAINER_ID] ls -alh /`
2. See `=4.24` file created by error

**Additional context**
None that is relevant to current situation.

**Comment by AbdBarho** [comment]
Neat! I never noticed this.

Would you be willing to contribute a fix? I assume just adding quotes would fix the problem.

I think something similar is used in all images so that the `transformers` cache is always the same version.

**Comment by DevilaN** [comment]
Sure, but on Monday (can't test building right now).
It seems that it is installing 4.25 right now anyway replacing old 4.19 installed in previous layers.
