### ISSUE TITLE
unable to run the auto UI. getting error: unknown instruction CAT 

### ISSUE THREAD

**Issue by shreya-dama-Crafty-Apes-VFX** [AbdBarho/stable-diffusion-webui-docker#304]
**Has this issue been opened before?**

- [Y] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [Y] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Got the following error while trying to run "docker compose --profile auto up --build"

Sending build context to Docker daemon  2.734kB
1 error occurred:
        * Error response from daemon: dockerfile parse error line 8: unknown instruction: CAT

**Which UI**

auto or auto-cpu or invoke or sygil? autoo

**Comment by AbdBarho** [comment]
See https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ#dockerfile-parse-error

if that does not fix your problem, please fill out the bug template so I can help.

**Comment by shreya-dama-Crafty-Apes-VFX** [comment]
I have already checked out the link, but it has not helped with the issue.

Hardware / Software

OS: Ubuntu 22.04.01 LTS

Steps to Reproduce
docker compose --profile auto up --build

Error obtained: Error response from daemon: dockerfile parse error line 8: unknown instruction: CAT

Already tried out solutions: 
https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ#dockerfile-parse-error
https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/276

**Comment by AbdBarho** [comment]
@shreya-dama-Crafty-Apes-VFX can you tell me this info?
```

- OS: [e.g. Windows 10 / Ubuntu 22.04]
- OS version: <!--  on windows, use the command `winver` to find out, on ubuntu `lsb_release -d`  -->
- WSL version (if applicable): <!-- get using `wsl -l -v` -->
- Docker Version: <!--  get using `docker version` -->
- Docker compose version: <!--  get using `docker compose version` -->
- Repo version: <!-- tag, commit sha, or "from master" -->
- RAM:
- GPU/VRAM:

```

**Comment by shreya-dama-Crafty-Apes-VFX** [comment]
- OS: Ubuntu 22.04
- OS version:Ubuntu 22.04.1 LTS
- Docker Version:   20.10.22
- Docker compose version:  v2.3.3
- Repo version:  5.0.0
- GPU/VRAM: Quadro RTX 5000 16GB

**Comment by AbdBarho** [comment]
@shreya-dama-Crafty-Apes-VFX and you  tried this and it did not work?

```
DOCKER_BUILDKIT=1 docker compose --profile auto up --build
```

**Comment by shreya-dama-Crafty-Apes-VFX** [comment]
I keep getting this error:

=> ERROR [download 3/8] RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 2426893  0.4s
 => CANCELED [stage-2  2/14] RUN PIP_NO_CACHE_DIR=1 pip install torch==1.13.1+cu117 torchvision --extra-index-url https  0.4s
------
 > [download 3/8] RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6   && rm -rf data assets **/*.ipynb:
#20 0.299 + . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6
#20 0.299 /bin/sh: .: line 0: can't open '/clone.sh': No such file or directory
------
failed to solve: executor failed running [/bin/sh -ceuxo pipefail . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6   && rm -rf data assets **/*.ipynb]: exit code: 2

**Comment by AbdBarho** [comment]
this is very weird, can you show me the entire output of this command:
```
DOCKER_BUILDKIT=1 docker compose --profile auto build --progress plain
```

**Comment by shreya-dama-Crafty-Apes-VFX** [comment]
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 32B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 resolve image config for docker.io/docker/dockerfile:1
#3 DONE 0.3s

#4 docker-image://docker.io/docker/dockerfile:1@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc
#4 CACHED

#6 [internal] load .dockerignore
#6 DONE 0.0s

#5 [internal] load build definition from Dockerfile
#5 DONE 0.0s

#9 [internal] load metadata for docker.io/library/alpine:3.17
#9 DONE 0.3s

#7 [internal] load metadata for docker.io/library/python:3.10.9-slim
#7 DONE 0.2s

#8 [internal] load metadata for docker.io/alpine/git:2.36.2
#8 DONE 0.3s

#18 [download 1/8] FROM docker.io/alpine/git:2.36.2@sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c713fa5e1c75dea84
#18 DONE 0.0s

#14 [xformers 1/3] FROM docker.io/library/alpine:3.17@sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a
#14 DONE 0.0s

#15 [xformers 2/3] RUN apk add --no-cache aria2
#15 CACHED

#19 [download 2/8] RUN <<EOF (cat <<'EOE' > /clone.sh...)
#19 CACHED

#16 [xformers 3/3] RUN aria2c -x 5 --dir / --out wheel.whl 'https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/download/4.1.0/xformers-0.0.16.dev421-cp310-cp310-manylinux2014_x86_64.whl'
#16 CACHED

#10 [stage-2  1/14] FROM docker.io/library/python:3.10.9-slim@sha256:e04bc5390a13e6e910980715f1156552fbd3deddf7668e1892575989f9504c70
#10 CACHED

#32 [internal] load build context
#32 transferring context: 123B done
#32 DONE 0.0s

#11 [stage-2  2/14] RUN PIP_NO_CACHE_DIR=1 pip install torch==1.13.1+cu117 torchvision --extra-index-url https://download.pytorch.org/whl/cu117
#11 ...

#20 [download 3/8] RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6   && rm -rf data assets **/*.ipynb
#20 0.431 + . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6
#20 0.431 /bin/sh: .: line 0: can't open '/clone.sh': No such file or directory
#20 ERROR: executor failed running [/bin/sh -ceuxo pipefail . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6   && rm -rf data assets **/*.ipynb]: exit code: 2

#11 [stage-2  2/14] RUN PIP_NO_CACHE_DIR=1 pip install torch==1.13.1+cu117 torchvision --extra-index-url https://download.pytorch.org/whl/cu117
#11 0.577 runc run failed: container process is already dead
#11 CANCELED
------
 > [download 3/8] RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6   && rm -rf data assets **/*.ipynb:
#20 0.431 + . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6
#20 0.431 /bin/sh: .: line 0: can't open '/clone.sh': No such file or directory
------
failed to solve: executor failed running [/bin/sh -ceuxo pipefail . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6   && rm -rf data assets **/*.ipynb]: exit code: 2

**Comment by AbdBarho** [comment]
this is still very weird and unexplainable to me, you can try a final time without a cache:
```
DOCKER_BUILDKIT=1 docker compose --profile auto build --progress plain --no-cache
```
If this does not work, I honestly have no idea what the problem is.

**Comment by DevilaN** [comment]
Show us your `/etc/docker/daemon.json` file. There is probably something fishy there.
Last time i was fighting similar heisenbug was wen there was `COMPOSE_DOCKER_CLI_BUILD` variable involved with build process and cached things from "no buildkit build" was leaking to buildkit builds causing weird errors.

**Comment by shreya-dama-Crafty-Apes-VFX** [comment]
the new updates on the repository helped resolve the issue. thank you
