### ISSUE TITLE
M1 Mac issue - PackagesNotFoundError: The following packages are not available from current channels: pytorch==1.11.0

### ISSUE THREAD

**Issue by sw-yx** [AbdBarho/stable-diffusion-webui-docker#31]
i checked that this issue has not been reported before.

**Describe the bug**

`docker-compose up` produces this: 

```bash
 => => transferring context: 4.20kB                                        0.0s
 => ERROR [ 2/12] RUN conda install python=3.8.5 && conda clean -a -y      3.0s
------
 > [ 2/12] RUN conda install python=3.8.5 && conda clean -a -y:
#0 0.241 + conda install python=3.8.5
#0 0.430 Collecting package metadata (current_repodata.json): ...working... done
#0 1.315 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#0 1.316 Collecting package metadata (repodata.json): ...working... done
#0 2.806 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#0 2.807
#0 2.807 PackagesNotFoundError: The following packages are not available from current channels:
#0 2.807
#0 2.807   - python=3.8.5
#0 2.807
#0 2.807 Current channels:
#0 2.807
#0 2.807   - https://repo.anaconda.com/pkgs/main/linux-aarch64
#0 2.807   - https://repo.anaconda.com/pkgs/main/noarch
#0 2.807   - https://repo.anaconda.com/pkgs/r/linux-aarch64
#0 2.807   - https://repo.anaconda.com/pkgs/r/noarch
#0 2.807
#0 2.807 To search for alternate channels that may provide the conda package you're
#0 2.807 looking for, navigate to
#0 2.807
#0 2.807     https://anaconda.org
#0 2.807
#0 2.807 and use the search bar at the top of the page.
#0 2.807
#0 2.807
------
failed to solve: executor failed running [/bin/bash -ceuxo pipefail conda install python=3.8.5 && conda clean -a -y]: exit code: 1
```

**Steps to Reproduce**

![image](https://user-images.githubusercontent.com/6764957/188305900-6c002578-a4e5-4600-8ccf-4268b2c5bc9e.png)

**Hardware / Software:**
 - OS: macos 12.5.1
 - GPU: m1 max, macbook pro

**Comment by sw-yx** [comment]
adding conda forge in the dockerfile seems to have solved it

![image](https://user-images.githubusercontent.com/6764957/188305993-82a9eb52-dbe1-40ca-b716-e3b5d1b14039.png)

**Comment by sw-yx** [comment]
mm more errors...

```
#0 20.74 PackagesNotFoundError: The following packages are not available from current channels:
#0 20.74 
#0 20.74   - pytorch==1.11.0
#0 20.74   - torchvision==0.12.0
```

**Comment by sw-yx** [comment]
seems i am not alone https://saoyan.github.io/blog/2022-06-10-pytorch-apple-m

**Comment by AbdBarho** [comment]
@sw-yx the problem is that these libraries are not available for macos.

If I am not mistaken, cuda can not be used under macos because of the different GPU architecture, so even if the libraries were installed, it is highly likely that the application would crash on startup.

However, there is another repo that claims to support macs https://github.com/lstein/stable-diffusion maybe you would have better luck there.

Related #5

**Comment by sw-yx** [comment]
understood. yes i did get the lstein one working, i just wanted to test the limits of the various forks because i wanted to write a tutorial for other folks.. and of course docker is a great way to distribute software. thanks for the quick response

**Comment by AbdBarho** [comment]
@sw-yx I managed to get the lstein fork to run in a docker container for linux

https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/32/files

if you are willing to adapt it to macos, I will gladly add it to the repo.

Starting point could be https://github.com/lstein/stable-diffusion/blob/main/README-Mac-MPS.md

**Comment by sw-yx** [comment]
@AbdBarho thanks for being so proactive! unfortunately there are [a lot of things to get right](https://github.com/lstein/stable-diffusion/blob/main/README-Mac-MPS.md) and my dockerfu skills are not strong. probably someone else who knows this stuff well should do this.

i tried out #32 but ran into the same issue with `pytorch==1.11.0` not being available for m1 macs. i have no idea what the lstein people did to get it to work.
