### ISSUE TITLE
Stopping container takes 10 seconds

### ISSUE THREAD

**Issue by nonnonstop** [AbdBarho/stable-diffusion-webui-docker#319]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

The container takes 10 seconds to exit because webui does not recognize SIGTERM.
This time can be reduced by changing the stop signal to SIGINT.

**Which UI**

auto

**Hardware / Software**

- OS: Windows 10
- OS version: 21H2
- WSL version: 2 (Ubuntu 22.04)
- Docker Version: 20.10.18
- Docker compose version: 2.10.2
- Repo version: 15e9841860f049ebf18fe64c54ae0e9db86e0071 (master)
- RAM: 32GB
- GPU/VRAM: GTX1080 8GB

**Steps to Reproduce**

1. Run `docker compose --profile auto up --build`
2. After starting the WebUI, press Ctrl+C to stop the container.
3. Stopping container takes 10 seconds.

```
Gracefully stopping... (press Ctrl+C again to force)
[+] Running 2/2
 ⠿ Container webui-docker-download-1  Stopped   0.0s
 ⠿ Container webui-docker-auto-1      Stopped   10.4s
```

If I add `stop_signal: SIGINT` to docker-compose.yml, the container will exit immediately.

**Comment by AbdBarho** [comment]
Thanks, fixed by #320.
