### ISSUE TITLE
Downloads timeout (errorCode=2)

### ISSUE THREAD

**Issue by omigeot** [AbdBarho/stable-diffusion-webui-docker#322]
**Has this issue been opened before?**

- [X] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched,

The closest I could find is this : https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/270 but it's stale and doesn't seem THAT related.

**Describe the bug**

The "download" profile fails to download several files. It ends up on timeout from aria2.

**Which UI**

Happens without any UI yet.

**Hardware / Software**

- OS: Ubuntu 22.04
- OS version: 22.04
- Docker Version: 23.0.0
- Docker compose version: v2.15.1 
- Repo version: 3c860d6eaa87bf5e4c05e9dccdf2412a49e10333
- RAM: 28G
- GPU/VRAM: 12G

**Steps to Reproduce**

1. sudo docker compose --profile download up --build
2. wait

**Additional context**

```webui-docker-download-1  | 02/03 21:18:15 [ERROR] CUID#7 - Download aborted. URI=https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt
webui-docker-download-1  | Exception: [AbstractCommand.cc:340] errorCode=2 Timeout.
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [ERROR] CUID#8 - Download aborted. URI=https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt
webui-docker-download-1  | Exception: [AbstractCommand.cc:340] errorCode=2 Timeout.
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [ERROR] CUID#9 - Download aborted. URI=https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/main/sd-v1-5-inpainting.ckpt
webui-docker-download-1  | Exception: [AbstractCommand.cc:340] errorCode=2 Timeout.
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [ERROR] CUID#10 - Download aborted. URI=https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth
webui-docker-download-1  | Exception: [AbstractCommand.cc:340] errorCode=2 Timeout.
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [ERROR] CUID#11 - Download aborted. URI=https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth
webui-docker-download-1  | Exception: [AbstractCommand.cc:340] errorCode=2 Timeout.
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [NOTICE] Download GID#a35af6914ae20efb not complete: /data/StableDiffusion/v1-5-pruned-emaonly.ckpt
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [NOTICE] Download GID#aadb4d137c8f6e35 not complete: /data/VAE/vae-ft-mse-840000-ema-pruned.ckpt
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [NOTICE] Download GID#9fbbda9aaae28fbc not complete: /data/StableDiffusion/sd-v1-5-inpainting.ckpt
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [NOTICE] Download GID#299e144a7f453f58 not complete: /data/GFPGAN/GFPGANv1.4.pth
webui-docker-download-1  | 
webui-docker-download-1  | 02/03 21:18:15 [NOTICE] Download GID#961df5e0f0ba1255 not complete: /data/RealESRGAN/RealESRGAN_x4plus.pth```

**Comment by AbdBarho** [comment]
@omigeot can you try again? I imagine it is an internet problem on your side.

**Comment by AbdBarho** [comment]
@omigeot this is weird.

Can you try downloading any of the links here manually without docker?

https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/services/download/links.txt

If the download works, then the problem is with the docker network. It not, the problem is in the internet connection.

**Comment by omigeot** [comment]
They do download normaly from outside docker. The weird thing is, re-running the download profile from the docker-compose afterwards tries (and fails) to re-download the same files.

**Comment by mikethemaker** [comment]
Hey there, just chiming in to say I just encountered the same exact issue. The downloads seem to work through my browser but not through docker compose. I've been attempting to run this on a new Ubuntu Server 22.04 LTS install.

**Comment by mikethemaker** [comment]
I'm back with good news this time. After purging docker with both apt and snap, I reinstalled it via [Nvidia's guide](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker).

After running docker compose again, all of the data downloaded successfully!

**Comment by omigeot** [comment]
That's what I did too, and yes it worked. I didn't use snap, but my docker install was somehow broken (at least for those containers).
