### ISSUE TITLE
I switch Model.ckpt,but ram continued overlay 

### ISSUE THREAD

**Issue by horoabb** [AbdBarho/stable-diffusion-webui-docker#326]
run webui,I switch Model.ckpt,but ram continued overlay.its dont drop

Ubuntu 22.04.1 LTS
Docker Compose version v2.14.1

i use aws to g5.2xlarge(gpu:24G ram:32G)

1.no docker: ram use 3609mb
2.start docker to webui :ram use:8583mb
3. fast switch Model(ckpt): ram use:22141mb
4. second switch : ram use:28738mb
5. three : ram use:30236mb

ram dont drop,so possible docker Out of memory
![0](https://user-images.githubusercontent.com/124558563/217712949-89b2f3e8-65c8-417e-ae04-6f9d4ba34a3c.PNG)

![1](https://user-images.githubusercontent.com/124558563/217712964-abe97edb-3733-4f9e-9913-d51785a10cf7.PNG)

![fast](https://user-images.githubusercontent.com/124558563/217712994-58aa49bc-8a1b-40d3-b498-85f007294932.PNG)

![seond](https://user-images.githubusercontent.com/124558563/217713000-19682a40-bea3-4cb4-9b0c-39d5bd58f452.PNG)

![three](https://user-images.githubusercontent.com/124558563/217713012-6a50defd-7b46-4b87-a1a1-f005209a1f47.PNG)

**Comment by DevilaN** [comment]
Memory leaks are somewhat normal in A1111. I don't know if this is a case in other webui's, but you have not specified which ui your bug report is refering to. Maybe it would be better if you fill in details in bug form, so we could help you better?

From my perspective, using ckpt leaks memory in A1111 greatly. This was main reason I switched to safetensor model format. Now I am happy. Models are loading much faster, and there are some minor leaks comparing to ckpt format.

**Comment by horoabb** [comment]
i use https://github.com/AbdBarho/stable-diffusion-webui-docker/

**Comment by horoabb** [comment]
how to use safetensor model

**Comment by horoabb** [comment]
auto

**Comment by DevilaN** [comment]
So I can suggest installing this extension: https://github.com/arenatemp/stable-diffusion-webui-model-toolkit
It will provide new tab with toolkit that converts models from ckpt to safetensor format and also removes data that do not contribute to model at all.

**Comment by horoabb** [comment]
ok,i try it, thanks

**Comment by Alfred-Duncan** [comment]
Yeah, when u use the a11 webui in docker, there will be memory leak. But sometimes if u only use that on the original linux, it still there.
I met this peoblem last week, and I back the version of gradio then fix it on the ori-linux. But in docker I failed, maybe safetensor can work, I'll try it later......

**Comment by DevilaN** [comment]
@Alfred-Duncan: any details of you fix? Maybe somebody else could find a way to fix memory leaks starting with your info.

**Comment by patlamontagne** [comment]
Some solutions are being shared in this issue of the main repo https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6850

**Comment by nonnonstop** [comment]
Just create `data/config/auto/startup.sh` as following.

```bash
# Workaround for memory leak
if [[ ! -L "/usr/lib/x86_64-linux-gnu/libtcmalloc.so" ]]; then
  apt-get -y install libgoogle-perftools-dev
fi
export LD_PRELOAD=libtcmalloc.so
```

**Comment by horoabb** [comment]
where in join export LD_PRELOAD=libtcmalloc.so

**Comment by DevilaN** [comment]
@nonnonstop Your solution works wonders! Probably it should be incorporated into image as memory leaks are very annoying thing in A1111 (@AbdBarho ?).
Thanks one more time!

**Comment by horoabb** [comment]
> 只需要創建`data/config/auto/startup.sh`如下。
> 
> ```shell
> # Workaround for memory leak
> if [[ ! -L "/usr/lib/x86_64-linux-gnu/libtcmalloc.so" ]]; then
>   apt-get -y install libgoogle-perftools-dev
> fi
> export LD_PRELOAD=libtcmalloc.so
> ```

this (data/config/auto/startup.sh) is to linux or stable-diffusion-webui

**Comment by patlamontagne** [comment]
@horoabb the `data` directory is in your `stable-diffusion-webui-docker` directory

**Comment by horoabb** [comment]
> @horoabb該`data`目錄在您的`stable-diffusion-webui-docker`目錄中

but ,i try to here (stable-diffusion-webui-docker/data/config/auto/startup.sh), no effect

**Comment by horoabb** [comment]
![1](https://user-images.githubusercontent.com/124558563/220534641-c1a9068b-c0db-4c7e-8bba-be8a43ffd7cc.PNG)
![2](https://user-images.githubusercontent.com/124558563/220534646-f589505f-e23f-4764-99f5-9db40e3dcd99.PNG)

**Comment by AbdBarho** [comment]
I did not see any benefits on my side, but I will add this nonetheless, not sure if it has any side effects that we are not aware of.
