### ISSUE TITLE
Docker container does not start

### ISSUE THREAD

**Issue by zedred79** [AbdBarho/stable-diffusion-webui-docker#327]
Everything worked until today, but when I reissued the command docker compose --profile auto up --build there is a exit wth code 1

Running on local URL:  http://0.0.0.0:7860
webui-docker-auto-1  |
webui-docker-auto-1  | To create a public link, set `share=True` in `launch()`.
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 278, in <module>
webui-docker-auto-1  |     webui()
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 232, in webui
webui-docker-auto-1  |     app.add_middleware(GZipMiddleware, minimum_size=1000)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 135, in add_middleware
webui-docker-auto-1  |     raise RuntimeError("Cannot add middleware after an application has started")
webui-docker-auto-1  | RuntimeError: Cannot add middleware after an application has started
webui-docker-auto-1 exited with code 1

**Comment by xtr3m3nerd** [comment]
I also have same issue, currently working around by using a different UI profile as it looks like the issue is based in the AUTOMATIC1111 UI:

docker compose --profile sygil up --build

**Comment by misebox** [comment]
This issue is related this. 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7714

A temporary workaround is inserting a line into `services/AUTOMATIC1111/Dockerfile` like following
```
@@ -85,6 +85,7 @@ mv ${ROOT}/style.css ${ROOT}/user.css
 # one of the ugliest hacks I ever wrote
 sed -i 's/in_app_dir = .*/in_app_dir = True/g' /usr/local/lib/python3.10/site-packages/gradio/routes.py
 EOF
+RUN pip install fastapi==0.90.1
 
 WORKDIR ${ROOT}
 ENV CLI_ARGS=""
```

next, build and up
```
$ docker compose --profile auto up --build
```

**Comment by AbdBarho** [comment]
I added the hotfix from @misebox, can you try again from the latest master?

**Comment by zedred79** [comment]
I downloaded the new version with the fix and now everything is working properly again.
A thousand thanks.
