### ISSUE TITLE
Image to image generates an error

### ISSUE THREAD

**Issue by reslip1** [AbdBarho/stable-diffusion-webui-docker#33]
**Has this issue been opened before? Check the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Main), the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=is%3Aissue) and in [the issues in the WebUI repo](https://github.com/hlky/stable-diffusion-webui)**

**Describe the bug**
Img 2 img generates an error. 
Traceback (most recent call last):
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
stable-diffusion-webui-docker-model-1  |     output = await app.blocks.process_api(
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
stable-diffusion-webui-docker-model-1  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
stable-diffusion-webui-docker-model-1  |     processed_input.append(block.preprocess(raw_input[i]))
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/components.py", line 1546, in preprocess
stable-diffusion-webui-docker-model-1  |     x, mask = x["image"], x["mask"]
stable-diffusion-webui-docker-model-1  | TypeError: string indices must be integers

**Steps to Reproduce**
1. Go to img 2 img unified and enter a sample image in img2img and a prompt
2. Click on generate
3. Look in docker log

**Hardware / Software:**
 - OS: Windows 10 - WSL2 - Ubuntu 
 - GPU: Nvidia 2070 Super
 - Version Built 9/4/2022

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by AbdBarho** [comment]
Bug in main Repo https://github.com/hlky/stable-diffusion-webui/issues/610

I will update once its fixed

**Comment by AbdBarho** [comment]
@reslip1 the problem should be fixed now, can you try again from latest master?

**Comment by reslip1** [comment]
Rebuilt using latest repo and tried crop and mask and they both worked. Thanks!
