### ISSUE TITLE
Got this error when trying to run docker compose download

### ISSUE THREAD

**Issue by keith0305** [AbdBarho/stable-diffusion-webui-docker#333]
I'm on Windows 10 with latest update.
Have WSL2 installed, latest docker desktop.

Got this error when running:
`docker compose --profile download up --build`

```
[+] Building 0.5s (3/3) FINISHED
 => [internal] load build definition from Dockerfile
0.1s  => => transferring dockerfile: 32B
0.0s  => [internal] load .dockerignore
0.1s  => => transferring context: 2B
0.0s  => ERROR [internal] load metadata for docker.io/library/bash:alpine3.15
0.3s ------
 > [internal] load metadata for docker.io/library/bash:alpine3.15:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0:
failed to create LLB definition:
failed to do request: Head "https://registry-1.docker.io/v2/library/bash/manifests/alpine3.15": EOF
```

**Comment by AbdBarho** [comment]
it seems your docker cannot connect to the internet?

can you try this?
```
docker pull docker.io/library/bash:alpine3.15 
```

**Comment by keith0305** [comment]
Got this.

```
Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF
```

**Comment by AbdBarho** [comment]
Ok, this confirms my hypothesis, docker cannot connect to the internet. is the internet working in your wsl installation? maybe you need a restart?

**Comment by keith0305** [comment]
I restarted and it did not help.
Thanks for finding the problem, I'll look into solution myself as well.
In the meantime, anything else you can suggest me to try? Any more info you need?

I tried turning VPN on/off, changing my DNS to automatic, Google's 8.8.8.8, Cloudflare's 1.1.1.1. Nothing works.

**Comment by keith0305** [comment]
Nvm, turning off Windows Firewall is the solution. Got it to work. Thank you!
