### ISSUE TITLE
start invoke ui failed with openai/clip-vit-large-patch14 loading failed

### ISSUE THREAD

**Issue by cszhz** [AbdBarho/stable-diffusion-webui-docker#337]
I use AWS g5.xlarge instance with CUDA 11.7 to build this repo,  meet the following issue when start **invoke** web ui.  

**Has this issue been opened before?**

- [Y] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [N] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.
https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/97
I searched above issue, but seem it does not help.

**Describe the bug**

**Which UI**

 invoke 

**Hardware / Software**

- OS: [Ubuntu 22.04]
- OS version: AWS DL AMI 
- WSL version (if applicable): 
- Docker Version: 23.0.1
- Docker compose version: v2.16.0
- Repo version: from master
- RAM: 
- GPU/VRAM: A10

**Steps to Reproduce**

git clone https://github.com/AbdBarho/stable-diffusion-webui-docker/
cd stable-diffusion-webui-docker/
docker compose --profile download up --build
----error when execute below command
docker compose --profile invoke up --build

**Additional context**
OSError: openai/clip-vit-large-patch14 does not appear to have a file named
pytorch_model.bin but there is a file for TensorFlow weights. Use `from_tf=True`
to load this model from those weights.

**Comment by AbdBarho** [comment]
@cszhz this is probably a cache problem, can you try deleting the folder: `data/.cache/huggingface/hub/models--openai--clip-vit-large-patch14` and try again?

**Comment by cszhz** [comment]
Thank you for your instant response.
Finally I download model files manually and it works.
Please close it.

**Comment by leoterry-ulrica** [comment]
> Thank you for your instant response. Finally I download model files manually and it works. Please close it.

Where do I put the downloaded model files？

**Comment by lipeng1109** [comment]
> Thank you for your instant response. Finally I download model files manually and it works. Please close it.

Where do I put the downloaded model files？

**Comment by Yeeeeeee123** [comment]
` \data\.cache\huggingface\hub` in this folder i only have a txt file named version.txt,how can i solve this problem?
