### ISSUE TITLE
No file or directory for latent-diffusion

### ISSUE THREAD

**Issue by Marcus-Arcadius** [AbdBarho/stable-diffusion-webui-docker#34]
![image](https://user-images.githubusercontent.com/78793842/188538101-e415de36-1399-415a-83fd-ebdbdf2c3653.png)

```
stable-diffusion-webui-docker-model-1  | /docker/mount.sh: line 25: /latentdiffusion/experiments/pretrained_models/project.yaml: No such file or directory 
stable-diffusion-webui-docker-model-1 exited with code 1
```

EDIT: Fixed the issue in the hlky mount.sh file by removing the # from the project.yaml line but now facing this issue

![image](https://user-images.githubusercontent.com/78793842/188540105-25e4e4bc-ba25-4534-9e58-8c0d2118b0ef.png)

```
stable-diffusion-webui-docker-model-1  |  Error loading LDSR
stable-diffusion-webui-docker-model-1  |  Loading model from /models/model.ckpt
stable-diffusion-webui-docker-model-1  |  Traceback (most recent call last):
stable-diffusion-webui-docker-model-1  |  File "scripts/webui.py", line 382, in try_loading_LDSR
stable-diffusion-webui-docker-model-1  |  LDSR = load_LDSR(checking=True) # TODO: Should try to load both models before giving up
stable-diffusion-webui-docker-model-1  |  File "scripts/webui.py", line 297, in load_LDSR
stable-diffusion-webui-docker-model-1  |  raise Exception("LDSR model not found at path "+model_path)
stable-diffusion-webui-docker-model-1  |  Exception: LDSR model not found at path /latent diffusion/experiments/pretrained_models/model.ckpt  

stable-diffusion-webui-docker-model-1  | Global Step: 470000
stable-diffusion-webui-docker-model-1  | UNet: Running in eps-prediction mode
stable-diffusion-webui-docker-model-1 exited with code 137
```

**Comment by AbdBarho** [comment]
@Marcus-Arcadius did you download the LDSR model and its configuration like written in the readme? or you don't want to use LDSR?

**Comment by Marcus-Arcadius** [comment]
@AbdBarho I did download the model and configuration file and renamed them, but the docker container for some reason couldn't find them in the model's folder?

**Comment by AbdBarho** [comment]
@Marcus-Arcadius this is very weird, can you show me the contents of the `models` folder?
`ls -l models` or `tree models/`?

**Comment by Marcus-Arcadius** [comment]
@AbdBarho this is whats inside the models folder which should be correct?
![image](https://user-images.githubusercontent.com/78793842/188574138-77c4899f-98a4-4a6d-9211-7c49c4c6975f.png)

**Comment by Marcus-Arcadius** [comment]
@AbdBarho so I got it to work with wsl2 Ubuntu but I'm encountering an error where it just randomly exits?

![image](https://user-images.githubusercontent.com/78793842/188577761-7fd3b318-3cf7-4d5a-8e78-d495eda0beb1.png)

**Comment by AbdBarho** [comment]
@Marcus-Arcadius how did you manage to get it running in wsl?
can you tell me your system specification? os / ram / gpu / vram? I assume the model is assuming too much memory and crashing?

**Comment by Marcus-Arcadius** [comment]
@AbdBarho I got it to eventually work by using a .wslconfig file and increasing the resources, my specs are the nvidia 2060 super, 16GB RAM, 8GB VRAM, and windows 11
