### ISSUE TITLE
Extensions that pip install things (like dreambooth) don't get saved on restart

### ISSUE THREAD

**Issue by kelvie** [AbdBarho/stable-diffusion-webui-docker#350]
**Has this issue been opened before?**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Try to install the dreambooth extension in auto, then restart the docker container

**Which UI**

auto 

**Hardware / Software**

(not sure this matters)

- OS: Arch Linux
- OS version: Rolling
- WSL version (if applicable): 
- Docker Version: 23.0.1
- Docker compose version: 2.16.0
- Repo version:  aa69f112302d29d667f20c9ccbe243c10834f6a2

**Steps to Reproduce**

1. Start docker compose
2. Install dreambooth extension
3. (as part of post install it mentions it pip installs a bunch of things)
4. Exit and create a new container
5. Notice that the dependencies are gone (because they're installed in /usr/local and not in a mounted dir)

**Additional context**

Should we persist a venv or something outside the container?

**Comment by AbdBarho** [comment]
you can try to run with `docker compose --profile auto up` without the `--build` parameter, the libs should remain installed.

**Comment by AbdBarho** [comment]
You can also add this to your `startup.sh`

```sh
if [ -f ./extensions/deforum-for-automatic1111-webui/requirements.txt ]; then
  pip install -q -r ./extensions/deforum-for-automatic1111-webui/requirements.txt
  pip install -q --force-reinstall opencv-python-headless 'transformers>=4.24'
fi
```


Or maybe if you want something a bit more general:

```sh

shopt -s nullglob
list=(./extensions/*/requirements.txt)
for req in "${list[@]}"; do
  pip install -q -r "$req"
done
pip install -q --force-reinstall opencv-python-headless 'transformers>=4.24'
```

**Comment by kelvie** [comment]
Right, I have this done locally as well:

https://github.com/kelvie/stable-diffusion-webui-docker/commit/555ae35b43bbae0c1abdd916344e3dc653191f88 (and oops forgot to set nullglob 😁 )

Is this something you think is useful for others? or should I just close this issue?

**Comment by AbdBarho** [comment]
I updated the wiki: https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Usage#extensions

**Comment by dmarx** [comment]
would it maybe make sense to add a step to startup.sh that checks the extensions subdirectories for install.py files and runs them if they exist? or maybe the container could mount a venv, so the state of the python environment would be persistent?
