### ISSUE TITLE
error in  docker compose --profile auto up --build

### ISSUE THREAD

**Issue by edwardelric1202** [AbdBarho/stable-diffusion-webui-docker#355]
when I tried " docker compose --profile auto up --build" on linux, it occurred error seems like internet problem:
 > [stage-2  9/15] RUN --mount=type=cache,target=/root/.cache/pip   pip install pyngrok   git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379   git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1   git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b:
#0 1.074 + pip install pyngrok git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b
#0 1.391 Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
#0 1.391   Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to /tmp/pip-req-build-mz5g_de4
#0 1.395   Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git /tmp/pip-req-build-mz5g_de4
#0 121.7   fatal: unable to access 'https://github.com/TencentARC/GFPGAN.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
#0 121.7   error: subprocess-exited-with-error
#0 121.7   
#0 121.7   × git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git /tmp/pip-req-build-mz5g_de4 did not run successfully.
#0 121.7   │ exit code: 128
#0 121.7   ╰─> See above for output.
#0 121.7   
#0 121.7   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 121.7 error: subprocess-exited-with-error
#0 121.7 
#0 121.7 × git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git /tmp/pip-req-build-mz5g_de4 did not run successfully.
#0 121.7 │ exit code: 128
#0 121.7 ╰─> See above for output.
#0 121.7 
#0 121.7 note: This error originates from a subprocess, and is likely not a problem with pip.
#0 121.7 
#0 121.7 [notice] A new release of pip available: 22.3.1 -> 23.0.1
#0 121.7 [notice] To update, run: pip install --upgrade pip
------
failed to solve: executor failed running [/bin/bash -ceuxo pipefail pip install pyngrok   git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379   git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1   git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b]: exit code: 1

how can I solve this? Thanks.

**Comment by AbdBarho** [comment]
@edwardelric1202 make sure you running from latest master & just try running again.

If the problem persists, I would need more info to debug
