### ISSUE TITLE
NansException: A tensor with all NaNs was produced in Unet.

### ISSUE THREAD

**Issue by Corshi** [AbdBarho/stable-diffusion-webui-docker#364]
This error start occurring immediately after last update of this repo. Before any updates to Automatic1111's repo.
This error is occurring in direct Automatic1111 installation since 10jan for many users, but this Docker version was able to avoid it somehow. Now it is happening.

Error:
```
NansException: A tensor with all NaNs was produced in Unet.
This could be either because there's not enough precision to represent the picture,
or because your video card does not support half type.
Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion
or using the --no-half commandline argument to fix this.
Use --disable-nan-check commandline argument to disable this check.
```

I was starting webui with all the combination of `--xformers`, `--reinstall-xformers`, `--precision full`, `--no-half`, `--no-half-vae`, `--disable-nan-check`. But results are the same. Generation is stopped immediately, or when check is disabled, it generates only black images. If everithing is set for precision, the error message is shorter, but basically the same:
```
NansException: A tensor with all NaNs was produced in Unet.
```

- WebUI: Automatic1111's
- OS: Windows 11
- OS version: 10.0.22000 Build 22000
- WSL version (if applicable): 2 (10.0.22000.652)
- Docker Version: v4.14.1
- Docker compose version: v2.12.2
- Repo version: from master
- RAM: 32GB
- GPU/VRAM: 2070S 8GB

**Comment by AbdBarho** [comment]
can you try removing the container and running again without `--reinstall-xformers`?

The xformers version shipped with the container is different than the one in pip.

Can you give me more info how I can reproduce this? does this happen with the default setting from this repo?

**Comment by Corshi** [comment]
Appeasers that reloading settings was enough.
The `Upcast cross attention layer to float32` did not fix anything, but things like deleting the configuration does. Even just ticking random thing on and off and then saving settings fixes it.

...just don't do any of the suggested fixers from the error message.

I guess some directories changed or names and that was it...

I'm back to my previous setting `- CLI_ARGS=--xformers --deepdanbooru --gradio-img2img-tool color-sketch --api` and it is fine.

So sorry to bother you for no reason.

I'm not sure if this should be closed thou, as `NaNs` errors seem to happen randomly for some people (on the AUTOMATIC1111' repo), so there might be other related problems that some other people might stumble upon.

**Comment by Corshi** [comment]
Sorry for everything, it was my stupid mistake. I had loaded model in wrong format...
