### ISSUE TITLE
Stuck at "Attaching to webui-docker-auto-1"

### ISSUE THREAD

**Issue by FaridSafi** [AbdBarho/stable-diffusion-webui-docker#369]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I used the commands
- `docker compose --profile download up --build`
- `docker compose --profile auto up --build`

Then I am stuck at "Attaching to webui-docker-auto-1"

**Hardware / Software**

- OS: Windows 11
- OS version: 22H2
- WSL version (if applicable): 2
- Docker Version: 20.10.23
- Docker compose version: 2.15.1
- Repo version: master
- RAM: 32
- GPU/VRAM: Nvidia 4090 rtx / 24gb

**Comment by Reshaflame** [comment]
I have the same issue. 
I HAD a working webui, don't know what I was thinking - I downloaded everything again (taught maybe there was an update?) and built it again - and I'm stuck at  'Attaching to webui-docker-auto-1' 

Tried doing everything a new (made a new folder) and the same thing...

Not my day ;_;

**Comment by AbdBarho** [comment]
have you tried removing the container and running again?

you can delete it from docker desktop since you are on windows.

**Comment by Reshaflame** [comment]
I can add mine:
Hardware / Software

OS: Windows 11
OS version: 22H2
WSL version (if applicable): 1.1.3.0
Docker Version: 20.10.23
Docker compose version: 2.15.1
Repo version: master
RAM: 32
GPU/VRAM: Nvidia 3060 rtx / 12gb

**Comment by AbdBarho** [comment]
I managed to reproduce the problem.

I will report back to you

**Comment by AbdBarho** [comment]
This is a bug in docker desktop 4.17.1

I downgraded to 4.17.0 and everything worked

https://docs.docker.com/desktop/release-notes/#4170

**Comment by Reshaflame** [comment]
> This is a bug in docker desktop 4.17.1
> 
> I downgraded to 4.17.0 and everything worked
> 
> https://docs.docker.com/desktop/release-notes/#4170

worked for me :) 
uninstalled docker desktop and installed 4.17.0 from this link. 
when there'll be a newer version then 4.17.1 I'll try and post here.

**Comment by FaridSafi** [comment]
Thank you @AbdBarho, it works with 4.17.0

**Comment by amirhjalali** [comment]
> This is a bug in docker desktop 4.17.1
> 
> I downgraded to 4.17.0 and everything worked
> 
> https://docs.docker.com/desktop/release-notes/#4170

Thanks! This was the issue!

**Comment by weihao** [comment]
+1

**Comment by wiktorkowalski** [comment]
just checked on the updated docker desktop [4.18](https://www.docker.com/blog/docker-desktop-4-18/) and it works just fine.
Updated from 4.17.1, hope it works for y'all

**Comment by AbdBarho** [comment]
4.18 worked for me and was not stuck, but it caused a load of other problems, mainly that it swallows my entire RAM even though no containers are running, I will be sticking to 4.17 for now.
