### ISSUE TITLE
How to add control net model?

### ISSUE THREAD

**Issue by rainbowechoes** [AbdBarho/stable-diffusion-webui-docker#371]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

I add control net extension, but no control net model.

![image](https://user-images.githubusercontent.com/38370475/227169119-73e43f64-1ae5-4918-b9ae-c0ecd8543547.png)

I create a directory 'ControlNet' in data dir and move model into it, but still not found the model

**Which UI**

auto

**Hardware / Software**

- OS: win11

**Comment by cutlass90** [comment]
@rainbowechoes 
Just add this line of code to services/AUTOMATIC1111/entrypoint.sh to MOUNTS section ()
`MOUNTS["${ROOT}/models/ControlNet"]="/data/ControlNet"`
then restart docker

**Comment by AbdBarho** [comment]
you can add this to your `startup.sh`, no need to modify the container.

**Comment by rainbowechoes** [comment]
thanks you!
