### ISSUE TITLE
Failure to send image to lab

### ISSUE THREAD

**Issue by hughk** [AbdBarho/stable-diffusion-webui-docker#38]
This seems to have been functioningearlier in the week week but no longer. The expected behavior is to bring the image up in the image lab tab.

**Describe the bug**

stable-diffusion-webui-docker-model-1  | Traceback (most recent call last):
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
stable-diffusion-webui-docker-model-1  |     output = await app.blocks.process_api(
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
stable-diffusion-webui-docker-model-1  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
stable-diffusion-webui-docker-model-1  |     processed_input.append(block.preprocess(raw_input[i]))
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/components.py", line 1270, in preprocess
stable-diffusion-webui-docker-model-1  |     return self.choices.index(x)
stable-diffusion-webui-docker-model-1  | ValueError: [['frankfurt in the rain moody lighting\n', None], ['seed:', '4146656096'], [' ', None], ['width:', '768'], [' ', None], ['height:', '384'], [' ', None], ['steps:', '50'], [' ', None], ['cfg_scale:', '7.5'], [' ', None], ['sampler:', 'k_lms'], ['', None]] is not in list

**Steps to Reproduce**
1. Change size to 384x768
2.  Prompt string: frankfurt in the rain moody lighting
3. Click on Generate
4. Wait for images to be generated (*4)
5. Select one image
6. Click on "Send to Lab"
7. Attempt to view in image lab. Nothing there.

**Hardware / Software:**
OS: Windows 11/WSL2
Docker version: v20.10.17
GPU: Nvidia 3090
Docker version: v20.10.17

**Additional context**

**Comment by AbdBarho** [comment]
@hughk  which model are you using?

**Comment by hughk** [comment]
@AbdBarho I believe it is the default (hlky). Nothing yet selected in the lab.

**Comment by AbdBarho** [comment]
@hughk I tried it with the latest version and it should work, can you pull from master and try again?

**Comment by hughk** [comment]
@AbdBarho Did a git pull and then a docker compose up --build, I am getting the same error.

**Comment by AbdBarho** [comment]
It seems like I am missing something because I cannot reproduce the problem



https://user-images.githubusercontent.com/24505302/188957182-32e89da5-3906-4af2-9eb0-457cfa1f1726.mp4

**Comment by hughk** [comment]
@AbdBarho The problem seems to be in the Image Lab too. Tried to load a jpeg for upscaling and I get:

stable-diffusion-webui-docker-model-1  | Traceback (most recent call last):
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
stable-diffusion-webui-docker-model-1  |     output = await app.blocks.process_api(
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
stable-diffusion-webui-docker-model-1  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
stable-diffusion-webui-docker-model-1  |     processed_input.append(block.preprocess(raw_input[i]))
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/components.py", line 1087, in preprocess
stable-diffusion-webui-docker-model-1  |     return [self.choices.index(choice) for choice in x]
stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/components.py", line 1087, in <listcomp>
stable-diffusion-webui-docker-model-1  |     return [self.choices.index(choice) for choice in x]
stable-diffusion-webui-docker-model-1  | ValueError: 'd' is not in list

**Comment by hughk** [comment]
@AbdBarho: I will try to revert to the version from the beginning of the week.

**Comment by AbdBarho** [comment]
@hughk  Or you can try the [AUTOMATIC1111 Fork](https://github.com/AbdBarho/stable-diffusion-webui-docker/tree/master/AUTOMATIC1111) it has less bugs than the main one.

**Comment by hughk** [comment]
@AbdBarho Problem between seat and keyboard. It was my fault as I tried to merge  the outputs from before. The files are called grid-00000-_<parameters>_ If you have two grid-00000 files there even with different parameters, it will break the code. The workaround is that when you copy, you always ensure that the files are uniquely numbered and in sequence. Thx again for your help.
