### ISSUE TITLE
Installer Failing

### ISSUE THREAD

**Issue by kmadaras** [AbdBarho/stable-diffusion-webui-docker#381]
Trying to use the installer, the first step works fine, the second step appears to be broken.

```
0 32.33   Attempting uninstall: numpy
#0 32.33     Found existing installation: numpy 1.24.2
#0 32.48     Uninstalling numpy-1.24.2:
#0 32.57 ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: '/usr/local/lib/python3.10/site-packages/numpy-1.24.2.dist-info/'
#0 32.57 
#0 32.58 
#0 32.58 [notice] A new release of pip available: 22.3.1 -> 23.0.1
#0 32.58 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/bash -ceuxo pipefail git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git\ncd stable-diffusion-webui\ngit reset --hard d7aec59c4eb02f723b3d55c6f927a42e97acd679\npip install -r requirements_versions.txt\n" did not complete successfully: exit code: 1

```

**Which UI**

Auto

**Hardware / Software**

- OS: Debian 11  in a privilvged LXC w/o App
- Docker Version:23.0.2, build 569dd73
- Docker compose version: Docker Compose version v2.17.2
- Repo version: Master
- RAM: 8 gigs
- GPU/VRAM: 3 cards,  T4 and 2x P40

**Steps to Reproduce**

1. Per install instructions, execute docker compose --profile download up --build,.
2. This works with Exit code 0docker compose 
3. Per instructions: docker compose --profile auto  up --build
4. Process starts, about a minute in it throws the error above and dies.

**Additional context**
I tried this on Ubuntu and Debian, both stop at the same place.  Apparmor is disabled in the container.

**Comment by AbdBarho** [comment]
I am unfamiliar with LXC so I cannot tell what consequences this has, I think it should have no effect, but maybe?

Maybe pip is having a hard time resolving or installing the correct numpy wheel for your system through the virtualizations.

**Comment by kmadaras** [comment]
OK,we
