### ISSUE TITLE
No CUDA GPUs are available

### ISSUE THREAD

**Issue by SunyiUborka** [AbdBarho/stable-diffusion-webui-docker#389]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Sorry, my English is not the best.

After i run ```docker compose --profile auto up --build```  I got the next error ```Warning: caught exception 'No CUDA GPUs are available', memory monitor disabled```. I tried invoke frontend and worked. And if I use [AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui) repository without docker its working.

**Which UI**

auto 

**Hardware / Software**

- OS: Fedora
- OS version: 37
- Docker Version: 23.0.2
- Docker compose version: v2.17.2
- Repo version: 063665eae162dee89bd18c894e423a04676a1ddd
- RAM: 24GB
- GPU/VRAM: GTX 1080 TI 11GB

**Steps to Reproduce**

1. Just run docker compose --profile auto up --build

**Additional context**
Docker respond
```bash
Attaching to webui-docker-auto-1
webui-docker-auto-1  | Mounted .cache
webui-docker-auto-1  | Mounted LDSR
webui-docker-auto-1  | Mounted BLIP
webui-docker-auto-1  | Mounted Hypernetworks
webui-docker-auto-1  | Mounted VAE
webui-docker-auto-1  | Mounted GFPGAN
webui-docker-auto-1  | Mounted RealESRGAN
webui-docker-auto-1  | Mounted Deepdanbooru
webui-docker-auto-1  | Mounted ScuNET
webui-docker-auto-1  | Mounted .cache
webui-docker-auto-1  | Mounted StableDiffusion
webui-docker-auto-1  | Mounted embeddings
webui-docker-auto-1  | Mounted ESRGAN
webui-docker-auto-1  | Mounted config.json
webui-docker-auto-1  | Mounted SwinIR
webui-docker-auto-1  | Mounted Lora
webui-docker-auto-1  | Mounted MiDaS
webui-docker-auto-1  | Mounted ui-config.json
webui-docker-auto-1  | Mounted BSRGAN
webui-docker-auto-1  | Mounted Codeformer
webui-docker-auto-1  | Mounted extensions
webui-docker-auto-1  | + python -u webui.py --listen --port 7860 --allow-code --medvram --xformers --enable-insecure-extension-access --api
webui-docker-auto-1  | Warning: caught exception 'No CUDA GPUs are available', memory monitor disabled
webui-docker-auto-1  | Removing empty folder: /stable-diffusion-webui/models/BSRGAN
webui-docker-auto-1  | Loading weights [c6bbc15e32] from /stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt
webui-docker-auto-1  | Creating model from config: /stable-diffusion-webui/configs/v1-inpainting-inference.yaml
webui-docker-auto-1  | LatentInpaintDiffusion: Running in eps-prediction mode
webui-docker-auto-1  | DiffusionWrapper has 859.54 M params.
webui-docker-auto-1  | loading stable diffusion model: RuntimeError
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 136, in initialize
webui-docker-auto-1  |     modules.sd_models.load_model()
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 445, in load_model
webui-docker-auto-1  |     sd_hijack.model_hijack.hijack(sd_model)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_hijack.py", line 172, in hijack
webui-docker-auto-1  |     self.optimization_method = apply_optimizations()
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_hijack.py", line 42, in apply_optimizations
webui-docker-auto-1  |     if cmd_opts.force_enable_xformers or (cmd_opts.xformers and shared.xformers_available and torch.version.cuda and (6, 0) <= torch.cuda.get_device_capability(shared.device) <= (9, 0)):
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
webui-docker-auto-1  |     prop = get_device_properties(device)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 371, in get_device_properties
webui-docker-auto-1  |     _lazy_init()  # will define _get_device_properties
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
webui-docker-auto-1  |     torch._C._cuda_init()
webui-docker-auto-1  | RuntimeError: No CUDA GPUs are available
webui-docker-auto-1  |
webui-docker-auto-1  |
webui-docker-auto-1  | Stable diffusion model failed to load, exiting
webui-docker-auto-1 exited with code 1
```

nvidia-container-cli info
```bash
NVRM version:   525.105.17
CUDA version:   12.0

Device Index:   0
Device Minor:   0
Model:          NVIDIA GeForce GTX 1080 Ti
Brand:          GeForce
GPU UUID:       GPU-3d585cfb-f22d-fb77-5b7d-0be1b407c832
Bus Location:   00000000:29:00.0
Architecture:   6.1
```

docker run --privileged --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
```bash
Mon Apr  3 18:16:28 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:29:00.0 Off |                  N/A |
|  0%   26C    P8    10W / 250W |     33MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by julianst** [comment]
Try adding the following line to the environment in the compose file:
`- NVIDIA_VISIBLE_DEVICES=all`

should look something like this:
```yaml
  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:51
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
      - NVIDIA_VISIBLE_DEVICES=all
```

**Comment by akeryuuth** [comment]
I have essentially the same setup and have encountered this issue as well. 
Adding ```- NVIDIA_VISIBLE_DEVICES=ALL``` does not work, it still returns the same error :
```Attaching to webui-docker-auto-1
webui-docker-auto-1  | Mounted .cache
webui-docker-auto-1  | Mounted openpose
webui-docker-auto-1  | Mounted LDSR
webui-docker-auto-1  | Mounted BLIP
webui-docker-auto-1  | Mounted Hypernetworks
webui-docker-auto-1  | Mounted VAE
webui-docker-auto-1  | Mounted GFPGAN
webui-docker-auto-1  | Mounted RealESRGAN
webui-docker-auto-1  | Mounted Deepdanbooru
webui-docker-auto-1  | Mounted ScuNET
webui-docker-auto-1  | Mounted ControlNet
webui-docker-auto-1  | Mounted .cache
webui-docker-auto-1  | Mounted StableDiffusion
webui-docker-auto-1  | Mounted embeddings
webui-docker-auto-1  | Mounted ESRGAN
webui-docker-auto-1  | Mounted config.json
webui-docker-auto-1  | Mounted SwinIR
webui-docker-auto-1  | Mounted Lora
webui-docker-auto-1  | Mounted MiDaS
webui-docker-auto-1  | Mounted ui-config.json
webui-docker-auto-1  | Mounted BSRGAN
webui-docker-auto-1  | Mounted Codeformer
webui-docker-auto-1  | Mounted extensions
webui-docker-auto-1  | + python -u webui.py --listen --port 7860 --allow-code --medvram --xformers --enable-insecure-extension-access --api
webui-docker-auto-1  | Warning: caught exception 'No CUDA GPUs are available', memory monitor disabled
webui-docker-auto-1  | Removing empty folder: /stable-diffusion-webui/models/BSRGAN
webui-docker-auto-1  | Calculating sha256 for /stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt: cc6cb27103417325ff94f52b7a5d2dde45a7515b25c255d8e396c90014281516
webui-docker-auto-1  | Loading weights [cc6cb27103] from /stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
webui-docker-auto-1  | Creating model from config: /stable-diffusion-webui/configs/v1-inference.yaml
webui-docker-auto-1  | LatentDiffusion: Running in eps-prediction mode
webui-docker-auto-1  | DiffusionWrapper has 859.52 M params.
webui-docker-auto-1  | loading stable diffusion model: RuntimeError
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 136, in initialize
webui-docker-auto-1  |     modules.sd_models.load_model()
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 445, in load_model
webui-docker-auto-1  |     sd_hijack.model_hijack.hijack(sd_model)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_hijack.py", line 172, in hijack
webui-docker-auto-1  |     self.optimization_method = apply_optimizations()
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_hijack.py", line 42, in apply_optimizations
webui-docker-auto-1  |     if cmd_opts.force_enable_xformers or (cmd_opts.xformers and shared.xformers_available and torch.version.cuda and (6, 0) <= torch.cuda.get_device_capability(shared.device) <= (9, 0)):
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
webui-docker-auto-1  |     prop = get_device_properties(device)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 371, in get_device_properties
webui-docker-auto-1  |     _lazy_init()  # will define _get_device_properties
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
webui-docker-auto-1  |     torch._C._cuda_init()
webui-docker-auto-1  | RuntimeError: No CUDA GPUs are available
webui-docker-auto-1  | 
webui-docker-auto-1  | 
webui-docker-auto-1  | Stable diffusion model failed to load, exiting
webui-docker-auto-1 exited with code 1
```
I have not tried using another ui though.

**Comment by AbdBarho** [comment]
Is this a linux problem? it seems that a lot of GPU related issues have started to pop up recently #406  [#397](https://github.com/AbdBarho/stable-diffusion-webui-docker/discussions/397)

Was there a new release of the nvidia-container-toolkit or similar that might have cause this? or maybe the drivers?

**Comment by akeryuuth** [comment]
Unclear where the issue comes from:
I tried (and gave up) setting up AUTOMATIC's webui a couple months ago. There has since been a new version of the drivers, docker and probably a new version of nvidia-container-toolkit, and the same issue still occurs.
I don't really know if the issue stems solely from linux, but it looks like PyTorch can't detect nvidia GPUs (with or without docker).
When I have time, I'll try on windows just to make sure it works fine with my setup and I'll try with a fresh debian install (could be related to fedora packages ?).

**Comment by akeryuuth** [comment]
Works as expected on Windows(11) and works just as well on a fresh Ubuntu install, which leads me to believe there's something wrong with the Fedora packages or the way they interface with each-other.
I'll try again from scratch on Fedora while following the [nvidia-container-toolkit for CentOS8 documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installing-on-centos-7-8) (since the packages aren't directly available for Fedora but are still compatible).
In the meantime I'll just use Ubuntu to run the webui.

**Comment by AbdBarho** [comment]
@akeryuuth  thank you for debugging this!

**Comment by akeryuuth** [comment]
After rebooting the ubuntu setup no long works, but I'm willing to admit it's been a long time I haven't used ubuntu and that installing it on an old external hdd wasn't the smartest idea.
On another note I managed to make it work on fedora by following the instructions in this [nvidia-docker issue](https://github.com/NVIDIA/nvidia-docker/issues/706).
I'll reboot and we'll see if I can make it run again.

**Comment by akeryuuth** [comment]
> Is this a linux problem? it seems that a more than usual GPU related issues have started to pop up recently #406 [#397](https://github.com/AbdBarho/stable-diffusion-webui-docker/discussions/397)
> 
> Was there a new release of the nvidia-container-toolkit or similar that might have cause this? or maybe the drivers? maybe the latest docker version?

Sidenote:
I ran into #406 before when I tried to run the webui using docker-desktop, which to my understanding, uses rootless containers by default.

**Comment by RedTopper** [comment]
In addition to my above comment, using `privileged: true` might not be a good security practice for some people. I left some instructions here https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/352#issuecomment-1517133811 for some of the Fedora users in this thread to try and get it working with rootless podman and no extra privileges. It's a bit more involved than just adding `privileged: true` in a yml file, but I wanted to give people another option.

**Comment by gitwittidbit** [comment]
> I'm getting this error on a Ubuntu 20.04 LTS Virtual Machine. CUDA works form NVIDIA containers or directly in the VM from python and with pytorch 2.0.1 and cuda 11.8 (same config as in the container). Therefore I'm sure the base OS works correctly and the issue is related to the container.
> 
> EDIT:
> 
> Note that I'm using an A100 with NVIDIA grid driver. not sure if this requires special setting inside the container?
> 
> SOLUTION: For A100 GPU on Ubuntu:
> 
> in the docker-compose.yml for the base-service, change capabilites to `["compute", "utility"]` from `["gpu"]`:
> 
> ```
> x-base_service: &base_service
>     ports:
>       - "7860:7860"
>     volumes:
>       - &v1 ./data:/data
>       - &v2 ./output:/output
>     stop_signal: SIGINT
>     deploy:
>       resources:
>         reservations:
>           devices:
>               - driver: nvidia                
>                 capabilities: ["compute", "utility"]
> ```
> 
> This makes the device available. This is probably due to the A100 not really being a gpu.

Unfortunately, this doesn't work for my A6000.

Has anybody else got this to work again?
