### ISSUE TITLE
Port Already Allocated on Auto

### ISSUE THREAD

**Issue by M4X40** [AbdBarho/stable-diffusion-webui-docker#390]
**Has this issue been opened before?**

- [X] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

This is the first time I am using this, and docker as a whole, and I am trying to run it with `auto` and i was getting `Error response from daemon: driver failed programming external connectivity on endpoint webui-docker-auto-1: Bind for 0.0.0.0:7860 failed: port is already allocated`. I have checked `netstat -aon` and port 7860 was not listed there.

**Which UI**

`auto`

**Hardware / Software**

- OS: Windows 11
- OS version: 22H2 (Build 22624.1537)
- WSL version (if applicable): 2
- Docker Version: v4.17.1
- Docker compose version: v2.15.1
- Repo version: from master
- RAM: 32
- GPU/VRAM: Zotac RTX 3060ti 8gb

**Additional context**
I used the invoke ui, got the `Stuck at "Attaching to webui-docker-auto-1` bug, and tried auto, got this after. Also getting this in a new directory and only running auto ui.

**Comment by AbdBarho** [comment]
Downgrade docker desktop https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/369
