### ISSUE TITLE
Container is up but got ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by skycat2216** [AbdBarho/stable-diffusion-webui-docker#396]
**Has this issue been opened before?**

- [Y] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [Y] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.(Technically, I have no idea for which keyword I should use, so maybe it's already been fixed but I missed it.)

**Describe the bug**

Container is up but Broser returns ERR_EMPTY_RESPONSE

**Which UI**

auto

**Hardware / Software**

- OS:Windows 11 Pro Workstation
- OS version: 22621.1413
- WSL version： 1.1.6.0
- WSL subsystem version :  2
- Core version： 5.15.90.1
- WSLg version： 1.0.50
- MSRDC version： 1.2.3770
- Direct3D version： 1.608.2-61064218
- DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp

- Docker Version:
- Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:43:10 2023
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.1 (101757)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
- Docker compose version:  v2.15.1
- Repo version: Up to Date
- RAM:32GiB
- GPU/VRAM:Gigabyte 2060S 

**Steps to Reproduce**

"Clone the project"
"Use docker compose to make the image"
"Run the container with image"
"Try to connect localhost:[port I assigned]"
"Broser returns ERR_EMPTY_RESPONSE"
"Feel worse than got dominate by outcast in The Division 2"

**Additional context**

**Comment by AbdBarho** [comment]
make you also expose the port, if you are using a custom one

https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/d2c1e551d70bdde109040af991816e77f21418f6/docker-compose.yml#L4-L5

**Comment by skycat2216** [comment]
> make you also expose the port, if you are using a custom one
> 
> https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/d2c1e551d70bdde109040af991816e77f21418f6/docker-compose.yml#L4-L5

Still got ERR_EMPTY_RESPONSE, Already exposed port 7860

**Comment by AbdBarho** [comment]
yes but you mentioned that you changed the port, so you need to expose the new port.

**Comment by skycat2216** [comment]
I changed it back to default
So that wouldn't be a problem anymore

**Comment by AbdBarho** [comment]
what is the output when you run the container? can you show me the logs?

**Comment by skycat2216** [comment]
I think container is working,I opened another port and run webui.py with that port in container's terminal.
This is what I got: 
`Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
No module 'xformers'. Proceeding without it.
Removing empty folder: /stable-diffusion-webui/models/BSRGAN
Loading weights [6ce0161689] from /stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: /stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 1.6s (create model: 0.4s, apply weights to model: 0.9s, apply half(): 0.3s).
Running on local URL:  http://0.0.0.0:9052

To create a public link, set `share=True` in `launch()`.
Startup time: 5.3s (import gradio: 1.7s, import ldm: 0.5s, other imports: 0.8s, load scripts: 0.3s, load SD checkpoint: 1.7s, create ui: 0.2s).`
I think problem is on my firewall and browser,The former rejected the localhost link to ports, The latter thinks 0.0.0.0 is an invalid address
