### ISSUE TITLE
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = dockerfile parse error on line 8: unknown instruction: cat (did you mean cmd?)

### ISSUE THREAD

**Issue by shxiq01** [AbdBarho/stable-diffusion-webui-docker#399]
excute " docker compose --profile auto up --build " is failed

 `[+] Building 15.5s (6/6) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                        15.3s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cf  0.0s
 => [internal] load build definition from Dockerfile                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = dockerfile parse error on line 8: unknown instruction: cat (did you mean cmd?)`

**Comment by AbdBarho** [comment]
https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ#dockerfile-parse-error

**Comment by shxiq01** [comment]
same problem，because I used windows system？

**Comment by AbdBarho** [comment]
please fill the bug template so we can see whats the problem

https://raw.githubusercontent.com/AbdBarho/stable-diffusion-webui-docker/master/.github/ISSUE_TEMPLATE/bug.md

**Comment by shxiq01** [comment]
docker compose --profile auto up --build
[+] Building 15.5s (6/6) FINISHED
 => [internal] load build definition from Dockerfile                                                   0.0s
 => => transferring dockerfile: 32B                                                                    0.0s
 => [internal] load .dockerignore                                                                      0.0s
 => => transferring context: 2B                                                                        0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                            15.3s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0e  0.0s
 => [internal] load .dockerignore                                                                      0.0s
 => [internal] load build definition from Dockerfile                                                   0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = dockerfile parse error on line 8: unknown instruction: cat (did you mean cmd?)




- OS:  Windows 10
- OS version： 19045.2728
- WSL version ：docker-desktop-data    Running         2
- Docker compose version： Docker Compose version v2.17.2
- Repo version：master
- RAM：16G
-  GPU/VRAM：NVIDIA

**Comment by shxiq01** [comment]
> please fill the bug template so we can see whats the problem
> 
> https://raw.githubusercontent.com/AbdBarho/stable-diffusion-webui-docker/master/.github/ISSUE_TEMPLATE/bug.md

My English is terrible，content has been added，tks

**Comment by shxiq01** [comment]
> please fill the bug template so we can see whats the problem
> 
> https://raw.githubusercontent.com/AbdBarho/stable-diffusion-webui-docker/master/.github/ISSUE_TEMPLATE/bug.md

I tried changing “# syntax=docker/dockerfile:1” to “# syntax=docker/dockerfile:1.3-labs” and it worked properly.

**Comment by etbox** [comment]
> > please fill the bug template so we can see whats the problem
> > https://raw.githubusercontent.com/AbdBarho/stable-diffusion-webui-docker/master/.github/ISSUE_TEMPLATE/bug.md
> 
> I tried changing “# syntax=docker/dockerfile:1” to “# syntax=docker/dockerfile:1.3-labs” and it worked properly.

It Works!

**Comment by AbdBarho** [comment]
all docker files should be OCI compliant now, this should not be a problem any more #408
