### ISSUE TITLE
unable to setup 'download' or 'auto' (I made a workaround for 'download')

### ISSUE THREAD

**Issue by gargolito** [AbdBarho/stable-diffusion-webui-docker#402]
**Has this issue been opened before?**

- [ x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

docker compose --profile download up --build
fails with:
`> [2/4] RUN apk add parallel aria2:`
`#0 0.216 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz`
`#0 5.221 ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)`
`#0 5.221 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: No such file or directory`
`#0 5.221 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz`
`#0 10.22 ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)`
`#0 10.22 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: No such file or directory`
`#0 10.22 ERROR: unable to select packages:`
`#0 10.22 aria2 (no such package):`
`#0 10.22 required by: world[aria2]`
`#0 10.22 parallel (no such package):`
`#0 10.22 required by: world[parallel]`
`------`
`failed to solve: executor failed running [/bin/sh -c apk add parallel aria2]: exit code: 2`

I get a similar failure for **auto**
`> [3/4] RUN apk add parallel aria2:`
`#0 0.298 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz`
`#0 5.302 ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)`
`#0 5.302 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: No such file or directory`
`#0 5.302 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz`
`#0 10.31 ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)`
`#0 10.31 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: No such file or directory`
`#0 10.31 ERROR: unable to select packages:`
`#0 10.31 aria2 (no such package):`
`#0 10.31 required by: world[aria2]`
`#0 10.31 parallel (no such package):`
`#0 10.31 required by: world[parallel]`
`------`
`failed to solve: executor failed running [/bin/sh -c apk add parallel aria2]: exit code: 2`

**Which UI**
first step of build according to [https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Setup](Setupl)

**Hardware / Software**

- OS:  Ubuntu 22.04
- OS version: Description:	Ubuntu 22.04.2 LTS
- Docker Version: Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2
- Docker compose version: docker-compose version 1.29.2
- Repo version: "from master"
- RAM: `Memory:
  RAM: total: 31.19 GiB used: 6.4 GiB (20.5%)
  Array-1: capacity: 64 GiB slots: 4 EC: None
  Device-1: Controller0-ChannelA-DIMM0 size: No Module Installed
  Device-2: Controller0-ChannelA-DIMM1 size: 16 GiB speed: spec: 2133 MT/s
    actual: 3200 MT/s
  Device-3: Controller0-ChannelB-DIMM0 size: No Module Installed
  Device-4: Controller0-ChannelB-DIMM1 size: 16 GiB speed: spec: 2133 MT/s
    actual: 3200 MT/s`
- GPU/VRAM: `Graphics:
  Device-1: NVIDIA GA106 [GeForce RTX 3060 Lite Hash Rate] driver: nvidia
    v: 525.60.11
  Display: server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia gpu: nvidia
    resolution: 1: 2560x1440~60Hz 2: 2560x1440~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
    v: 4.6.0 NVIDIA 525.60.11
`

**Steps to Reproduce**

1. clone repo and cd into directory
2. run "docker compose --profile download up --build"
3. after download workaround described below, run "docker compose --profile auto up --build"

**Additional context**
I was able to get around it adding `apk add aria2 parallel` at the top `services/download/download.sh`, and commenting out/removing `RUN apk add aria2 parallel` from `services/download/Dockerfile`
This doesn't work for **auto** since there so much stuff going on before the entrypoint runs.

**Comment by AbdBarho** [comment]
This is weird, but probably a temporary internet error, what happens if you  `docker pull bash:alpine3.15` and try running again?

The image gets built as part of the CI so everything should be available.

**Comment by gargolito** [comment]
I actually tried that before I opened the bug, should have added it to the ticket. The _download_ service works, I am not sure that this is a network issue.

**Comment by gargolito** [comment]
No, I get the same problem with 2
```
docker compose version
Docker Compose version v2.12.2
```

FYI: I had AUTOMATIC1111 working properly until a few days ago when I did a git pull and the thing broke (before I tried your repo). Before that, it was working fine using my GPU properly. When it broke I couldn't get it back so I decided to look elsewhere and found your repo. Although I was able to build your setup using the network workaround, when it tries to launch auto, it fails here: 
```
 => => naming to docker.io/library/sd-auto:51                                                               0.0s
Attaching to webui-docker-auto-1
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]
```

**Comment by AbdBarho** [comment]
regarding the last error message you sent, maybe this helps:

https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ#linux

**Comment by gargolito** [comment]
I have the toolkit and i was running automatic's interface properly with GPU until i updated my local repo. They introduced some big that doesn't let me run it anymore which is why I tried this repo instead in the hopes that you didn't have the same issues.

**Comment by jfcolomer** [comment]
Hi all,
I am facing the same error.
@gargolito where should I add `network: host` as a workaround to make it work?
Thanks in advance.

**Comment by jfcolomer** [comment]
Thanks @yume-chan would you be able to specify where are you adding the `network: host` bit

**Comment by gargolito** [comment]
> Hi all, I am facing the same error. @gargolito where should I be adding `network: host` as a workaround to make it work? Thanks in advance.
In docker-compose.yml, see: https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/402#issuecomment-1503843205

**Comment by WeileiZeng** [comment]
I got an issue in the same place but with this message
```
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/main: network error (check Internet connection and firewall)
```
I figure out it is due to access ailpine resource in China, and got fixed by adding the following line in `Dockfile` right before `RUN apk add --no-cache aria2`
```
sed -i 's/https\:\/\/dl-cdn.alpinelinux.org/https\:\/\/mirrors.ustc.edu.cn/g' /etc/apk/repositories
```
This changes to use Tsinghua mirror instead, [read more](https://blog.csdn.net/weixin_37551036/article/details/114482730)

This solution might be unrelated to the issue, but I put it here in case others need it.

**Comment by Geil** [comment]
Solved with rewriting the DNS settings in docker.
Proceed to `/etc/default/docker` file, open it and uncomment the section following:
`#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"`, also I've changed it to CloudFlare ones (`1.1.1.1`, `1.0.0.1`) instead of Google presetted defaults, and it works.
Correctly downloaded.
But it causes the external access issues to the working services, so need to comment it back anyway after downloading will be finished, or going deeper to solve it, but I don't want to.

**Comment by lupwei** [comment]
> @gargolito @jfcolomer Solved with rewriting the DNS settings in docker. Proceed to `/etc/default/docker` file, open it and uncomment the section following: `#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"`, also I've changed it to CloudFlare ones (`1.1.1.1`, `1.0.0.1`) instead of Google presetted defaults, and it works (maybe will need to reboot the instance). Correctly downloaded. But it causes the external access issues to the working services, so need to comment it back anyway after downloading will be finished, or going deeper to solve it, but I don't want to (don't forget to reboot if needed).

Windows users can modify the DNS settings by add   "dns": ["1.1.1.1"]   in Settings--Docker Engine. It works in my case.

**Comment by ioddevs** [comment]
resolved following lupwei
