### ISSUE TITLE
(root) Additional property name is not allowed

### ISSUE THREAD

**Issue by nfyn** [AbdBarho/stable-diffusion-webui-docker#404]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

**Which UI**

auto or auto-cpu or invoke or sygil?

**Hardware / Software**

- OS: [e.g. Windows 10 / Ubuntu 22.04]
- OS version: 
- WSL version (if applicable): 
- Docker Version: 
- Docker compose version: 
- Repo version: 
- RAM:
- GPU/VRAM:

**Steps to Reproduce**

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by AbdBarho** [comment]
Please fill out the bug report so we can better debug this
