### ISSUE TITLE
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1

### ISSUE THREAD

**Issue by jan-polivka** [AbdBarho/stable-diffusion-webui-docker#406]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

When I run `docker compose --profile auto up --build`, I get the following error, stuff gets downloaded and then docker tries to run the composition but I get the following output:

[+] Running 1/1
 ✔ Container webui-docker-auto-1  Created                                                                       0.1s 
Attaching to webui-docker-auto-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

**Which UI**

auto but I tried invoke as well and it is the same issue

**Hardware / Software**

- OS: Pop!_OS 22.04 LTS
- OS version: Pop!_OS 22.04 LTS
- Docker Version: Docker Desktop 4.18.0
- Docker compose version: Docker Compose version v2.17.2
- Repo version: from master, pulled today
- RAM: 16GB, Docker limited to 8GB
- GPU/VRAM: GeForce GTX 980, Dedicated video memory: 4096 MB

**Steps to Reproduce**

Run `docker compose --profile download up --build` 
Run `docker compose --profile auto up --build`

**Additional context**
These two issues are similar but don't seem to help
https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/129
https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/48

**Comment by AbdBarho** [comment]
Just for info 8GB is not enough for `auto`. But I don't think that's the problem.

Do you have the nvidia container toolkit & nvidia drivers installed?

**Comment by jan-polivka** [comment]
How much is good for `auto`?

Yes and yes, I believe, see below

nvidia-container-toolkit -version -> `NVIDIA Container Runtime Hook version 1.12.1`

nvidia-smi ->
```+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   51C    P5    21W / 196W |    727MiB /  4096MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2660      G   /usr/lib/xorg/Xorg                243MiB |
|    0   N/A  N/A      2769      G   /usr/bin/gnome-shell               64MiB |
|    0   N/A  N/A      3419      G   ...in,WebAssemblyTrapHandler      183MiB |
|    0   N/A  N/A     11122      G   ...veSuggestionsOnlyOnDemand       31MiB |
|    0   N/A  N/A     18484      G   ...e/Steam/ubuntu12_32/steam       39MiB |
|    0   N/A  N/A     18585      G   ...ef_log.txt --shared-files      120MiB |
|    0   N/A  N/A     45933      G   ...RendererForSitePerProcess        9MiB |
|    0   N/A  N/A     64405      G   ...local/kitty.app/bin/kitty        2MiB |
+-----------------------------------------------------------------------------+

**Comment by AbdBarho** [comment]
Might be related https://github.com/NVIDIA/nvidia-docker/issues/1711

[sudo problems](https://forums.developer.nvidia.com/t/nvidia-container-cli-initialization-error-load-library-failed-libnvidia-ml-so-1/237759)

[Docker bug](https://stackoverflow.com/q/74064263)

**Comment by jan-polivka** [comment]
Yeah, I think that might have worked. I couldn't initially run docker with sudo because I think I didn't install properly initially but I didn't care until now because things worked. I can generate pictures now, thank you :)
