### ISSUE TITLE
error during setup in a cloud docker envoiroment

### ISSUE THREAD

**Issue by Bitbitti** [AbdBarho/stable-diffusion-webui-docker#414]
if I try to run the command: docker compose --profile auto-cpu up --build in a docker cloud environment, I get the error: ERROR [stage-2 2/15] RUN --mount=type=cache,target=/root/.cache/pip pip install torch==1.13.1+cu117 torchvision --extra-index-url https://download.pytorch.org/whl/cu117

**Comment by AbdBarho** [comment]
please fill out the bug report
