### ISSUE TITLE
Blank web ui(s)

### ISSUE THREAD

**Issue by toynbeeidea16** [AbdBarho/stable-diffusion-webui-docker#431]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Launched using either auto or invoke, looks successful, but get a blank white page for the UI in Firefox.

**Which UI**

auto, invoke

**Hardware / Software**

- OS: Manjaro
- OS version: n/a, rolling
- WSL version 
- Docker Version: 23.0.3
- Docker compose version: 2.17.2
- Repo version: 
- RAM: 32gb
- GPU/VRAM:  Nvidia a4500/20gb

**Steps to Reproduce**

1. docker compose --profile auto up --build
2. Navigate to localhost:7860 or 127.0.0.1:7860
3. blank white page

**Comment by AbdBarho** [comment]
what is the output in the console?
