### ISSUE TITLE
Where to put styles.csv?

### ISSUE THREAD

**Issue by M0ebiu5** [AbdBarho/stable-diffusion-webui-docker#435]
I would like to use styles - how can i import them?

UI: auto
OS: Ubuntu 22

**Comment by AbdBarho** [comment]
It is a known problem, fix should be coming soon.

https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/386

**Comment by AbdBarho** [comment]
If you pull now from master, you should be able to find the file in `data/config/auto/styles.csv`, but the UI will handle all of this anyway.

**Comment by M0ebiu5** [comment]
Great, thanks!
