### ISSUE TITLE
AUTO API docs not found

### ISSUE THREAD

**Issue by miRemid** [AbdBarho/stable-diffusion-webui-docker#448]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

cannot open the swagger api page according to the auto [wiki](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API)

**Which UI**

auto
**Hardware / Software**

- OS: Ubuntu
- OS version: Ubuntu 18.04.6 LTS
- Docker Version: 23.0.5
- Docker compose version: v2.17.3
- Repo version: latest
- RAM: 256G
- GPU/VRAM: 8 NVIDIA 3090

**Steps to Reproduce**
1. `docker compose --profile auto up -d`
2. open the docker-ip:7860/docs, returns `{"detail":"Not Found"}` 404

**Additional context**
Want:
![image](https://user-images.githubusercontent.com/35894052/236603100-dac027f8-083e-4a9c-98fe-00fcb307762d.png)
Get:
![image](https://user-images.githubusercontent.com/35894052/236603092-d6ceb5e3-94a9-4b5e-898e-3aa30b8f2348.png)

**Comment by AbdBarho** [comment]
I think this a cli flags that is missing, do you know which one?

**Comment by miRemid** [comment]
according to wiki: `First, of course, is to run web ui with --api commandline argument
example in your "webui-user.bat": set COMMANDLINE_ARGS=--api`

but in the current [docker-compose](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/7fb8b97b90aa7fd849c7d59eeed5a43e875af67a/docker-compose.yml#LL27C3-L33C92), already add the '--api' flag🧐

**Comment by AbdBarho** [comment]
:/

**Comment by LEv145** [comment]
![изображение](https://user-images.githubusercontent.com/40071054/236626355-fdca3cd0-7126-44d0-a26c-99ccf0ca938d.png)

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10109

**Comment by miRemid** [comment]
add a `nowebui` flag get the docs back (but cannot use the webui anymore, sad), [https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10136](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10136#issuecomment-1537157278)
![image](https://user-images.githubusercontent.com/35894052/236653744-ab3bdc5a-15f9-4200-8050-72c2ce183299.png)

**Comment by miRemid** [comment]
> I have same issue, any one can help

if you don't need webui, you can try to add a `nowebui` flag in the [environment](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/71f4abb2dbf233cd78a1ba32187310adb193cb88/docker-compose.yml#LL33C20-L33C20) fileds

**Comment by zhongzishi** [comment]
> I have same issue, any one can help

This one got fixed in AUTOMATIC1111 release 1.2.1 (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/89f9faa63388756314e8a1d96cf86bf5e0663045), just waiting for an update in docker version.

**Comment by AbdBarho** [comment]
Ok I will try to give it a look today

**Comment by AbdBarho** [comment]
This is fixed now on master.

Try again, if the problem still persists then please re-open this issue.
