### ISSUE TITLE
"failed to solve "Error on M2 Mac...

### ISSUE THREAD

**Issue by kittykatattack** [AbdBarho/stable-diffusion-webui-docker#46]
Hello!

I'm trying to get this running on an M2 Mac, and am getting this error... does anyone know what it means or how to solve it?

```
failed to solve: executor failed running [/bin/bash -ceuxo pipefail conda install python=3.8.5 && conda clean -a -y]: exit code: 1
```

Thanks!!

**Comment by AbdBarho** [comment]
Mac is unfortunately not supported, because I don't have a mac. Contributions are welcome.
We can continue the discussion in #35.

**Comment by kittykatattack** [comment]
Thanks so much!
