### ISSUE TITLE
Comfy needs the `data/config/comfy/custom_nodes` directory

### ISSUE THREAD

**Issue by hashworks** [AbdBarho/stable-diffusion-webui-docker#460]
**Has this issue been opened before?**

- [X] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Running `podman-compose --profile comfy --podman-run-args "--dns 8.8.8.8" up --build` gives
```
[...]
[comfy] | Adding extra search path custom_nodes /data/config/comfy/custom_nodes
[comfy] | Traceback (most recent call last):
[comfy] |   File "/stable-diffusion/main.py", line 92, in <module>
[comfy] |     init_custom_nodes()
[comfy] |   File "/stable-diffusion/nodes.py", line 1193, in init_custom_nodes
[comfy] |     load_custom_nodes()
[comfy] |   File "/stable-diffusion/nodes.py", line 1183, in load_custom_nodes
[comfy] |     possible_modules = os.listdir(custom_node_path)
[comfy] | FFileNotFoundError: [Errno 2] No such file or directory: '/data/config/comfy/custom_nodes'
```

**Which UI**

comfy

**Hardware / Software**

- OS: Arch Linux
- OS version: rolling
- Podman Version: 4.5.0
- Podman compose version: 1.0.7
- Repo version: c836f419219811a60007757b1ba7af9e87a8882a

**Steps to Reproduce**

1. `podman-compose --profile download --podman-run-args --dns 8.8.8.8 up --build`
2. `podman-compose --profile comfy --podman-run-args "--dns 8.8.8.8" up --build`

**Additional context**

Creating the `data/config/comfy/custom_nodes` dir fixes it.

**Comment by AbdBarho** [comment]
Thanks, this should be fixed now.

There are still some mounts that are missing
https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/71f4abb2dbf233cd78a1ba32187310adb193cb88/services/comfy/extra_model_paths.yaml#L21-L25
If you find a use case please open a new issue or PR!
