### ISSUE TITLE
Run on CPU

### ISSUE THREAD

**Issue by isapir** [AbdBarho/stable-diffusion-webui-docker#47]
Hello, how can I run this without GPU support?

I disabled the deploy resources section 
```
    # environment:
    #   - CLI_ARGS=--extra-models-cpu --optimized-turbo
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #           - driver: nvidia
    #             device_ids: ['0']
    #             capabilities: [gpu]
```

But I am still getting an error when trying to run:

> stable-diffusion-webui-docker-model-1  | Traceback (most recent call last):
> stable-diffusion-webui-docker-model-1  |   File "scripts/webui.py", line 453, in <module>
> stable-diffusion-webui-docker-model-1  |     model, device,config = load_SD_model()
> stable-diffusion-webui-docker-model-1  |   File "scripts/webui.py", line 444, in load_SD_model
> stable-diffusion-webui-docker-model-1  |     model = load_model_from_config(config, opt.ckpt)
> stable-diffusion-webui-docker-model-1  |   File "scripts/webui.py", line 159, in load_model_from_config
> stable-diffusion-webui-docker-model-1  |     model.cuda()
> stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 127, in cuda
> stable-diffusion-webui-docker-model-1  |     return super().cuda(device=device)
> stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in cuda
> stable-diffusion-webui-docker-model-1  |     return self._apply(lambda t: t.cuda(device))
> stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
> stable-diffusion-webui-docker-model-1  |     module._apply(fn)
> stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
> stable-diffusion-webui-docker-model-1  |     module._apply(fn)
> stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
> stable-diffusion-webui-docker-model-1  |     module._apply(fn)
> stable-diffusion-webui-docker-model-1  |   [Previous line repeated 1 more time]
> stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
> stable-diffusion-webui-docker-model-1  |     param_applied = fn(param)
> stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in <lambda>
> stable-diffusion-webui-docker-model-1  |     return self._apply(lambda t: t.cuda(device))
> stable-diffusion-webui-docker-model-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
> stable-diffusion-webui-docker-model-1  |     torch._C._cuda_init()
> stable-diffusion-webui-docker-model-1  | RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
> stable-diffusion-webui-docker-model-1 exited with code 1

Thank you

**Comment by AbdBarho** [comment]
@isapir I am working on a big refactor that should include cpu-support, It should hopefully be finished today.

**Comment by isapir** [comment]
Thanks @AbdBarho!  That's awesome!

**Comment by AbdBarho** [comment]
@isapir can you try out the new branch with cpu support?

```bash
git fetch
git checkout unify
docker compose --profile auto-cpu up --build
```

**Comment by isapir** [comment]
@AbdBarho What is the docker command now? I tried:

```
docker compose up automatic1111-cpu 
```
I get an error that the model is not in the right place.  I'm not sure where it should be on the host:

> webui-docker-automatic1111-cpu-1  | FileNotFoundError: [Errno 2] No such file or directory: '/stable-diffusion-webui/repositories/stable-diffusion/models/ldm/stable-diffusion-v1/model.ckpt'

**Comment by isapir** [comment]
Looks like this command got deleted in the Edit: 
```bash
docker compose --profile auto-cpu up --build
```
But I'm still not sure where the model file is expected to be at on the host filesystem.

**Comment by isapir** [comment]
This is from https://github.com/AUTOMATIC1111/stable-diffusion-webui#automatic-installationlaunch but I'm not sure where to put it with your directory structure.

![image](https://user-images.githubusercontent.com/885907/189559799-2dfb6cb1-4b01-491d-b061-1894f2788e7c.png)

**Comment by AbdBarho** [comment]
As stated in [the release](https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/tag/1.0.0), the `models` folder should be moved to `cache/models`

**Comment by isapir** [comment]
Sorry, I missed that, but even there it's not working for me:

> webui-docker-automatic1111-cpu-1  | FileNotFoundError: [Errno 2] No such file or directory: '/stable-diffusion-webui/repositories/stable-diffusion/models/ldm/stable-diffusion-v1/model.ckpt'
webui-docker-automatic1111-cpu-1 exited with code 1

I tried both `cache/models/model.ckpt` and `cache/models/ldm/stable-diffusion-v1/model.ckpt`

**Comment by AbdBarho** [comment]
@isapir Ok, lets debug this:

Can you show me the full log from the docker command until the error? At the beginning you should see one of 
```
Mounted model.ckpt
or
Skipped model.ckpt
```
If you see the first one, it means there is a problem in the container that I have to fix, if you see the second, it means the folders where the data is stored is not correct.

Can you confirm that the `cache/models` folder looks [like this](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Setup#manual-download)?
```
cache/models/
├── model.ckpt
└── GFPGANv1.3.pth
```
Its not a problem if you have more files than this, but at least these should be available.

Finally, if all else fails, you can run 
```
docker compose --profile download up --build
```
which will re-download all of the required files into the correct folder, and then you can start the UI.

**Comment by isapir** [comment]
It said "Skipping model.ckpt".

I ran the download profile but it broke with some error, so I started over in a new directory and it works well.

Thank you very much!

I can confirm that it runs with CPU-only.
