### ISSUE TITLE
docker compose --profile auto up --build fails with apt-get update

### ISSUE THREAD

**Issue by dekolla** [AbdBarho/stable-diffusion-webui-docker#470]
> (base) root@VM-0-6-ubuntu:/data/stable-diffusion-webui-docker# docker compose --profile auto up --build -d
[+] Building 1.8s (14/32)                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                   0.0s
 => => transferring dockerfile: 4.12kB                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/python:3.10.9-slim                                                                                                                  0.7s
 => [internal] load metadata for docker.io/library/alpine:3.17                                                                                                                         0.7s
 => [internal] load metadata for docker.io/alpine/git:2.36.2                                                                                                                           0.7s
 => [internal] load build context                                                                                                                                                      0.0s
 => => transferring context: 4.23kB                                                                                                                                                    0.0s
 => [xformers 1/3] FROM docker.io/library/alpine:3.17@sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126                                                          0.0s
 => CACHED [stage-2  1/15] FROM docker.io/library/python:3.10.9-slim@sha256:76dd18d90a3d8710e091734bf2c9dd686d68747a51908db1e1f41e9a5ed4e2c5                                           0.0s
 => [download 1/8] FROM docker.io/alpine/git:2.36.2@sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c713fa5e1c75dea84                                                            0.0s
 => CACHED [xformers 2/3] RUN apk add --no-cache aria2                                                                                                                                 0.0s
 => ERROR [stage-2  2/15] RUN apt-get update && apt-get install fonts-dejavu-core rsync git jq moreutils aria2 -y && apt-get clean                                                     0.7s
 => CANCELED [xformers 3/3] RUN aria2c -x 5 --dir / --out wheel.whl 'https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/download/5.0.3/xformers-0.0.20.dev528-cp310-c  0.8s
 => CACHED [download 2/8] COPY clone.sh /clone.sh                                                                                                                                      0.0s
 => CANCELED [download 3/8] RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6   && rm -rf data assets *  1.0s
------                                                                                                                                                                                      
 
**the error：**

> [stage-2  2/15] RUN apt-get update && apt-get install fonts-dejavu-core rsync git jq moreutils aria2 -y && apt-get clean:                                                                
#0 0.545 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]                                                                                                                     
#0 0.557 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]                                                                                                  
#0 0.558 Err:1 http://deb.debian.org/debian bullseye InRelease                                                                                                                              
#0 0.558   Couldn't create temporary file /tmp/apt.conf.Fpvi3a for passing config to apt-key                                                                                                
#0 0.558 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]                                                                                                            
#0 0.559 Err:2 http://deb.debian.org/debian-security bullseye-security InRelease                                                                                                            
#0 0.559   Couldn't create temporary file /tmp/apt.conf.KvDEJh for passing config to apt-key                                                                                                
#0 0.560 Err:3 http://deb.debian.org/debian bullseye-updates InRelease                                                                                                                      
#0 0.560   Couldn't create temporary file /tmp/apt.conf.lDCJCl for passing config to apt-key                                                                                                
#0 0.562 Reading package lists...                                                                                                                                                           
#0 0.568 W: GPG error: http://deb.debian.org/debian bullseye InRelease: Couldn't create temporary file /tmp/apt.conf.Fpvi3a for passing config to apt-key                                   
#0 0.568 E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
#0 0.568 W: GPG error: http://deb.debian.org/debian-security bullseye-security InRelease: Couldn't create temporary file /tmp/apt.conf.KvDEJh for passing config to apt-key
#0 0.568 E: The repository 'http://deb.debian.org/debian-security bullseye-security InRelease' is not signed.
#0 0.568 W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: Couldn't create temporary file /tmp/apt.conf.lDCJCl for passing config to apt-key
#0 0.568 E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
------
#failed to solve: process "/bin/sh -c apt-get update && apt-get install fonts-dejavu-core rsync git jq moreutils aria2 -y && #apt-get clean" did not complete successfully: exit code: 100 

The bug with RUN apt-get update && apt-get install fonts-dejavu-core rsync git jq moreutils aria2 -y && apt-get clean

**Comment by AbdBarho** [comment]
you either have an outdated image, or you are in a region where the access is blocked, try with a proxy or vpn.

**Comment by AbdBarho** [comment]
related #468

**Comment by dekolla** [comment]
> you either have an outdated image, or you are in a region where the access is blocked, try with a proxy or vpn.

thanks, i got . my computer is in Hong Kong.    so，i changed 
> RUN apt-get update && apt-get install fonts-dejavu-core rsync git jq moreutils aria2 -y && apt-get clean
>
to
>RUN chmod 777 /tmp  &&  apt-get update && apt-get install fonts-dejavu-core rsync git jq moreutils aria2 -y && apt-get clean
>
 it is ok and solved the problem

**Comment by AbdBarho** [comment]
Great!
