### ISSUE TITLE
Cannot start docker container (could not select device driver "nvidia" with capabilities: [[gpu]])

### ISSUE THREAD

**Issue by Hanson-Wu** [AbdBarho/stable-diffusion-webui-docker#474]
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

OS: CentOS7

-bash-4.2$ nvidia-smi
Wed May 17 19:58:39 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P4                        Off| 00000000:61:00.0 Off |                    0 |
| N/A   36C    P0               22W /  75W|      0MiB /  7680MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by AbdBarho** [comment]
https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ#linux
