### ISSUE TITLE
docker compose --profile auto up --build  has an error: failed to solve: failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 30: Unknown flag:mount

### ISSUE THREAD

**Issue by JinHisAndy** [AbdBarho/stable-diffusion-webui-docker#475]
failed to solve: failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 30: Unknown flag:mount

**Comment by JinHisAndy** [comment]
Ubuntu18.04
NVIDIA-SMI 525.105.17
Tesla T4

**Comment by AbdBarho** [comment]
I need to know which versions of docker and others you are using.

Please create a new issue and fill the bug report.
