### ISSUE TITLE
ImportError: cannot import name 'auto' from 'tqdm'

### ISSUE THREAD

**Issue by andyoulovexy** [AbdBarho/stable-diffusion-webui-docker#476]
![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/38940994/b6481a39-3149-4e7e-b738-d9498db128dd)

**Comment by AbdBarho** [comment]
probably some extension ovverrode the version of tqdm installed locally.

What extensions are you using, and do you get the same problem with a fresh start without any extensions?

**Comment by larangin** [comment]
@AbdBarho Hey I was able to reproduce it. I installed this extension: https://github.com/CiaraStrawberry/TemporalKit
and as you mentioned, it overrode tqdm version. do you know a way to get tqdm back?

**Comment by larangin** [comment]
@AbdBarho I tried to load extension requirements up from build and got this message
`ImportError: tqdm>=4.27 is required for a normal functioning of this module, but found tqdm==4.11.2.`
so it looks like the moviepy module requires an upper tqdm version. any way to upgrade just tqdm?

**Comment by AbdBarho** [comment]
You can install whatever packages in whatever versions you want in `startup.sh`
https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Usage#extensions

**Comment by Terence131211** [comment]
try to replace tqdm to newer one
