### ISSUE TITLE
Proxmox / LXC: Unable to start docker container, nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1

### ISSUE THREAD

**Issue by shodanx2** [AbdBarho/stable-diffusion-webui-docker#48]
Hi,

When I docker compose up -d

I get the following

```
root@stablediffusion:/opt/stable-diffusion-webui-docker# docker compose up -d
[+] Running 0/1
 ⠹ Container stable-diffusion-webui-docker-model-1  Starting                                                                                                            68.2s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
```

My setup is as follows, I have a x64 computer running latest proxmox 
On it I have created an LXC container with Ubuntu 22.04.1 LTS
This container is updated upgraded, docker-compose initially installed

The initial install failed due to old version 20.10.12 was replaced with 20.10.18

Installed with the following commands

apt remove docker-compose
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh

This didn't work, so I installed nvidia-docker2 as follows

```
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)    && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -    && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
apt-get update
apt-get install -y nvidia-docker2
```

Here are my model files

root@stablediffusion:/opt/stable-diffusion-webui-docker/models# sha1sum *
e5102721808b8f0e421e6c3a8b73248d3b08373f  GFPGANv1.3.pth
60482fe909787328a7bf5a7edffb96e390465915  LDSR.ckpt
f7f8941c3117649042047220b762fe3d8b5f616c  LDSR.yaml
a1b5c65842f69da7c857479b501fb7125022fabf  RealESRGAN_x4plus.pth
d91e1688357e2d2238911253c57a94aeac4625a4  RealESRGAN_x4plus_anime_6B.pth
210783247af4f65a3d23d026490cc37a670964dd  model.ckpt

While writing this issue, I have found one thing I have not yet tried, and I will after posting this.
Hopefully anyone walking in my footsteps will find this and not waste so much time !

apt-add-repository ppa:graphics-drivers/ppa
apt-get install nvidia-370 nvidia-prime

Maybe that will work, the version 370 is probably very old, looks like what we need here is "nvidia-smi" and that may be part of the drivers. I suspect this is going to install a whole X server ...

Also this LXC container is unprivileged so I suspect I will also run into some other problems later down the road and I don't know if I have the IOMMU stuff working at all, this is my first time using the graphics card in this computer (5 year old 1080ti)

-------------

ok installed the nvidia drivers with the following
```
apt install software-properties-common
apt-add-repository ppa:graphics-drivers/ppa
apt install -y nvidia-prime nvidia-driver-515-server
```

The nvidia repository recommends running
apt-get install phoronix-test-suite
phoronix-test-suite default-benchmark openarena xonotic tesseract gputest unigine-valley
However this package is nowhere to be found ( Unable to locate package phoronix-test-suite )

I tried installing only nvidia-prime, it changed nothing, I don't know if this package is required at all

```
root@stablediffusion:/opt/stable-diffusion-webui-docker# docker compose up -d
[+] Running 0/1
 ⠦ Container stable-diffusion-webui-docker-model-1  Starting                                                                                                             1.6s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown
```

Ok, well, on to the next error !

**Comment by AbdBarho** [comment]
@shodanx2 It seems that you are on the right path of debugging.

1080ti should be enough, I am running on a laptop 1060.

370 is not just old but ancient for the deep learning world, I know that docker / nvidia require a least >=418 or something similiar.

Do you have [NVIDIA Container Toolkit](https://github.com/NVIDIA/nvidia-docker#getting-started) installed? and did you restart the machine after install (so the kernel modules get loaded)?

**Comment by shodanx2** [comment]
Hi,

I've run out of time for tonight, excited to continue working on this tomorrow

To be clear I have installed nvidia-docker2 in the ubuntu 22.04 LXC running on promox

I now suspect that I need some stuff on the proxmox host as well. I was really hoping not to have to touch it !
Because I have a ton of active software on it, oh well, time for update

I tried running it using the nvidia container toolkit install instruction but they failed early

```
root@proxmox:~#  distribution=$(. /etc/os-release;echo $ID$VERSION_ID)       && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg       && curl -s -L https://nvidia.github.io/libnvidia-container/experimental/$distribution/libnvidia-container.list |          sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' |          tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
File '/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg' exists. Overwrite? (y/N) y
# Unsupported distribution!
# Check https://nvidia.github.io/libnvidia-container
```

I will have a couple more leads to read through but I'm done for tonight
```

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker
https://stackoverflow.com/questions/64197626/nvidia-docker-initialization-error-nvml-error-driver-not-loaded
https://old.reddit.com/r/Proxmox/comments/s02d66/nvidia_gpu_passthrough_in_lxc_problem/
https://forum.proxmox.com/threads/nvidia-container-runtime-in-lxc-container.57786/
https://github.com/Saberwolf64/Proxmox-Nvidia-LXC-
https://old.reddit.com/r/Proxmox/comments/q4d0w5/gpu_access_in_a_docker_container_in_lxc/
```

**Comment by greycubesgav** [comment]
Hi;
I have a similar setup (Proxmox -> LXC  Ubuntu 22.04.1 LTS -> Docker 20.10.17)
It took a fair amount of careful work to get the GPU passed through all the way to a docker container.

My advice would be focus on one step at a time, i.e. make sure the Nvidia drivers are installer and running fine in the proxmox host, then work on the lxc container, then finally get docker Nvidia runtime working. Also make sure the driver version used in the lxc container match the proxmox host version exactly.

Before trying to run any complex python/ml/stable-diff docker containers make sure you can run nvidia-smi within the nvidia coda docker.

e.g. 
`sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`

I've shared my rough notes to get the Nvidia-runtime working within an LXC container under proxmox here:
https://gist.github.com/greycubesgav/8f77ff3b6411a868bf4a0365c71d064b

The main gotchas I would say are
* Use the exactly same version of nvidia drivers within lxc as in the host
* The lxc.cgroup.devices setting depends on your local group numbers. and may change on reboot
* The no cgroups config option (no-cgroups = true) to allow docker within the LXC to attach to the gfx card

Thanks

**Comment by futhgar** [comment]
I'd like to document this here:

I was getting errors when trying to utilize this repo - the error I was getting was related to cgroups with the following message:

`rror response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown`


Thanks to @greycubesgav response, I was just missing that change in the nvidia config file to uncomment `no-cgroups = true`.

**Comment by charles-cai** [comment]
Document here as well - same as above mentioned by @futhgar: once added `no-cgroups = true.` to `/etc/nvidia-container-runtime/config.toml`, problem solved.  

However I didn't do that at all for my Ubuntu 24.04 LXC on the same Proxmox and it worked without that line.  This one is Ubuntu 22.04.  RTX 2060 on an Intel Nuc i7 Gen11 box.  Note I was not able to run Minikube with GPU support (to test vLLM Production Stack) on either LXC yet due to other eBPF related problems I'm still investigating.

**Comment by RomanKalashnikov** [comment]
привет всем из 2025 и спасибо @greycubesgav за такой замороченный подход к решению проблемы. файл с командами просто сокровище! помог мне прокинуть tesla v100 в докер контейнер !
