### ISSUE TITLE
ERROR [download 2/4] RUN apk add parallel aria2

### ISSUE THREAD

**Issue by sduqlsc** [AbdBarho/stable-diffusion-webui-docker#494]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

libcontainer: container start initialization failed: permission deniedcontainer_linux.go:318: starting container process caused "permission denied"

**Which UI**

auto or auto-cpu or invoke or sygil?

**Hardware / Software**

- OS: CentOS 7
- Docker Version: 24.0.2
- Docker compose version: 2.18.1
- Repo version:  "from master" 
- RAM: 128G
- GPU/VRAM: No

**Steps to Reproduce**

1. git clone repository
2. cd stable-diffusion-webui-docker/
3.  docker-compose --profile download up --build
![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/8055140/a2f5e907-0f76-4348-9489-cee0d3ad372c)

**Comment by AbdBarho** [comment]
`docker-compose` or `docker compose`? is your setup sudoless?

**Comment by sduqlsc** [comment]
> `docker-compose` or `docker compose`? is your setup sudoless?

docker-compose，but hv placed `docker-compose` soft link under docker cli plugins，so it's the same？

what do you mean by sudoless？

**Comment by AbdBarho** [comment]
I see.

By sudoless I mean the docker daemon does not have root access.

Are you in china? you might need to update the mirrors or use proxy / vpn?
