### ISSUE TITLE
Segmentation fault on startup

### ISSUE THREAD

**Issue by Sapp00** [AbdBarho/stable-diffusion-webui-docker#498]
**Describe the bug**

It worked the whole time, only recent changes are the Update of GPU drivers. After that, it stopped working. I rebuilt it and used v7.0, but still crashing on startup.

**Which UI**

Tried auto and invoke.

**Hardware / Software**

- OS: Windows11
- OS version: 22H2
- WSL version (if applicable): not used
- Docker Version: Docker Desktop 4.15.0 (93002) Engine Version:          20.10.21
- Docker compose version: v2.13.0
- Repo version: 6.0/7.0
- RAM: 32
- GPU/VRAM: GTX970

**Steps to Reproduce**

1. docker-compose --profile download up --build --force-recreate
2. docker-compose --profile auto build --no-cache
3. -> error

**Additional context**

Error message:
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Attaching to webui-docker-auto-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 2, stdout: , stderr: fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f346408d3dd]

runtime stack:
runtime.throw({0x52797a, 0x29000003de})
        /usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
runtime.cgocall(0x4f4950, 0xc0000e3968)
        /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0000e3940 sp=0xc0000e3908 pc=0x40521c
github.com/NVIDIA/go-nvml/pkg/dl._Cfunc_dlopen(0x1c88820, 0x1)
        _cgo_gotypes.go:110 +0x4d fp=0xc0000e3968 sp=0xc0000e3940 pc=0x4eeb6d
github.com/NVIDIA/go-nvml/pkg/dl.(*DynamicLibrary).Open(0xc0000e3a40)
        /go/src/nvidia-container-toolkit/vendor/github.com/NVIDIA/go-nvml/pkg/dl/dl.go:55 +0x74 fp=0xc0000e39e0 sp=0xc0000e3968 pc=0x4eed94
gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvinfo.HasNVML()
        /go/src/nvidia-container-toolkit/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvinfo/info.go:34 +0x85 fp=0xc0000e3a78 sp=0xc0000e39e0 pc=0x4ef185
github.com/NVIDIA/nvidia-container-toolkit/internal/info.ResolveAutoMode({0x54e488, 0x63bee0}, {0xc0000161a0, 0x528947})
        /go/src/nvidia-container-toolkit/internal/info/auto.go:40 +0x1a8 fp=0xc0000e3b18 sp=0xc0000e3a78 pc=0x4ef728
main.doPrestart()
        /go/src/nvidia-container-toolkit/cmd/nvidia-container-runtime-hook/main.go:77 +0xdd fp=0xc0000e3f08 sp=0xc0000e3b18 pc=0x4f2efd
main.main()
        /go/src/nvidia-container-toolkit/cmd/nvidia-container-runtime-hook/main.go:176 +0x11e fp=0xc0000e3f80 sp=0xc0000e3f08 pc=0x4f445e
runtime.main()
        /usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc0000e3fe0 sp=0xc0000e3f80 pc=0x436607
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000e3fe8 sp=0xc0000e3fe0 pc=0x460b81: unknown

**Comment by AbdBarho** [comment]
What happens if you revert these changes to the `docker-compose.yml` and try to run again?
https://github.com/AbdBarho/stable-diffusion-webui-docker/commit/660c098da05dd24febee45111b9117c7a75c2ed2

**Comment by Sapp00** [comment]
> What happens if you revert these changes to the `docker-compose.yml` and try to run again? [660c098](https://github.com/AbdBarho/stable-diffusion-webui-docker/commit/660c098da05dd24febee45111b9117c7a75c2ed2)

Hi, which changes? I didn't change anything manually in the docker-compose.yaml - just used the one provided in the releases 6.0.0 and 7.0.0

**Comment by AbdBarho** [comment]
> Hi, which changes? I didn't change anything manually in the docker-compose.yaml - just used the one provided in the releases 6.0.0 and 7.0.0

I know, I was just asking if you can undo the changes that I made and see if it works locally.

i.e. change this
```yml
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
```
to this
```yml
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
```

and run again.

This problem might be related to your GPU because a GTX970 is relatively old.

**Comment by kalebbroo** [comment]
I am having this same issue I'm running a 2080TI. Worked in the past. Only change I made recently was updating the GPU drivers.

`Attaching to webui-docker-auto-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 2, stdout: , stderr: fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f83bd62f3dd]

runtime stack:
runtime.throw({0x5286a1?, 0x29000003de?})
        /usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:802 +0x389

goroutine 1 [syscall]:
runtime.cgocall(0x4f48d0, 0xc000151958)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000151930 sp=0xc0001518f8 pc=0x40523c
github.com/NVIDIA/go-nvml/pkg/dl._Cfunc_dlopen(0x1406820, 0x1)
        _cgo_gotypes.go:113 +0x4d fp=0xc000151958 sp=0xc000151930 pc=0x4ee78d
github.com/NVIDIA/go-nvml/pkg/dl.(*DynamicLibrary).Open(0xc000151a30)
        /go/src/nvidia-container-toolkit/vendor/github.com/NVIDIA/go-nvml/pkg/dl/dl.go:55 +0x74 fp=0xc0001519d0 sp=0xc000151958 pc=0x4ee994
gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvlib/info.(*infolib).HasNvml(0xc0000162a0?)
        /go/src/nvidia-container-toolkit/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvlib/info/info.go:47 +0x85 fp=0xc000151a68 sp=0xc0001519d0 pc=0x4eed85
github.com/NVIDIA/nvidia-container-toolkit/internal/info.ResolveAutoMode({0x54f5c8, 0x6333e0}, {0xc0000181a0?, 0x52974f?})
        /go/src/nvidia-container-toolkit/internal/info/auto.go:42 +0x1bb fp=0xc000151b18 sp=0xc000151a68 pc=0x4ef53b
main.doPrestart()
        /go/src/nvidia-container-toolkit/cmd/nvidia-container-runtime-hook/main.go:77 +0xdd fp=0xc000151f08 sp=0xc000151b18 pc=0x4f2e7d
main.main()
        /go/src/nvidia-container-toolkit/cmd/nvidia-container-runtime-hook/main.go:176 +0x11e fp=0xc000151f80 sp=0xc000151f08 pc=0x4f43de
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000151fe0 sp=0xc000151f80 pc=0x4368d2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000151fe8 sp=0xc000151fe0 pc=0x460981: unknown
PS C:\Users\kaleb\Desktop\projects\stable-diffusion-webui-docker>
`

**Comment by nekrasovdmitriy** [comment]
Having the same issue, after successfully building version 7.0:

```
/docker/entrypoint.sh: line 43:    44 Segmentation fault      (core dumped) invokeai-configure --root ${ROOT} --yes
webui-docker-invoke-1 exited with code 139
```

**Comment by Brensom** [comment]
I have the same problem. What can be done about this?
