### ISSUE TITLE
rsync error - container not starting

### ISSUE THREAD

**Issue by LindezaGrey** [AbdBarho/stable-diffusion-webui-docker#519]
**Has this issue been opened before?**

- [X ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

The container won't start up and gives this error:

```
docker compose --profile auto up

Attaching to webui-docker-auto-1
webui-docker-auto-1  | rsync: [Receiver] mkdir "/data/models/VAE-approx" failed: No such file or directory (2)
webui-docker-auto-1  | rsync error: error in file IO (code 11) at main.c(787) [Receiver=3.2.3]
webui-docker-auto-1 exited with code 11
```

**Which UI**

auto

**Hardware / Software**

- OS: [Windows 10 / WSL]
- WSL version (if applicable): Ubuntu 22.04
- Docker Version: Docker Desktop
- Docker compose version: v2.17.2
- Repo version: master
- RAM: 64GB
- GPU/VRAM: 3080 / 10G

**Steps to Reproduce**

Just clone the repo and launch with docker compose --profile auto up --build

**Comment by AbdBarho** [comment]
should be fixed now, feel free to re-open if not fixed

**Comment by LindezaGrey** [comment]
thank you for your fast support, it works!
