### ISSUE TITLE
Questions about Docker

### ISSUE THREAD

**Issue by Jonseed** [AbdBarho/stable-diffusion-webui-docker#52]
I haven't used Docker before, but I like how you've packaged the best repos together to try and switch between. I'm trying to get multiple repos running on my machine, and this could be the ticket. I have some questions:

How do you update the repos? Does docker update them automatically, or do you run a git pull?

Do the repos share package libraries, or are they all in their separate independent environments?

Is there any memory overhead running them with Docker?

Do the output files land in their regular output folders within the repos on the Windows file system? I read somewhere that WSL2 uses a separate Linux file system and doesn't interoperate with the Windows file system.

Thanks!

**Comment by AbdBarho** [comment]
@Jonseed 
> How do you update the repos? Does docker update them automatically, or do you run a git pull?

I download & build the code from git at a specific sha, when I want to update, I update the sha.
https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/services/hlky/Dockerfile#L15-L21
Docker does not update anything

> Do the repos share package libraries, or are they all in their separate independent environments?

Separate, I wanted to combine them, maybe in the future.

> Is there any memory overhead running them with Docker?

Not much, some megabytes

> Do the output files land in their regular output folders within the repos on the Windows file system?
Yes, I use WSL2 under windows and it works fine with the standard folders.

**Comment by Jonseed** [comment]
@AbdBarho thanks! So if I want to update the repos, do I do a git pull on your repo and then run the docker download again?

**Comment by AbdBarho** [comment]
@Jonseed  almost, you don't need to download the data again, because it is already downloaded, you just need to re-run the container:
```bash
git pull
docker compose --profile auto up --build
# or what ever profile you choose
```

**Comment by Jonseed** [comment]
@AbdBarho cool. Also, if I've already downloaded the models, will those have to download again? Will it download the models three times, once for each repo, or one time and insert them into each repo?

**Comment by AbdBarho** [comment]
@Jonseed No, you won't download the models again, you will have to rebuild the containers for each UI, but the same models are re-used for each repo
