### ISSUE TITLE
code 137

### ISSUE THREAD

**Issue by Kilig1058674225** [AbdBarho/stable-diffusion-webui-docker#530]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.
![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/68159061/08724389-feac-4757-b40a-984f0b81f998)

**Describe the bug**
I encountered error code 137 while setting up stable-diffusion-webui-docker. How can I fix this? Thank you! Here is the run log:

**Which UI**

auto 

**Hardware / Software**

- OS:  Windows 11
- Docker Version: v4.20.1
- GPU:nvdia 3060

**Comment by nviraj** [comment]
Indicates RAM is insufficient.
Check out this similar [issue](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/296#issuecomment-1387018699). Need to increase RAM allocated through Docker Desktop.

**Comment by AbdBarho** [comment]
thanks @nviraj, that's correct.
