### ISSUE TITLE
Gradio sketch crash

### ISSUE THREAD

**Issue by Charmandrigo** [AbdBarho/stable-diffusion-webui-docker#531]
**Has this issue been opened before?**
no

**Describe the bug**
When creating a new canvas on Gradio Sketch (not uploading a pic), it makes the canvas grow so big in a instant that the browser and the sketch addon crash completely
<img width="1457" alt="image" src="https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/30424766/e7205608-49dc-4cf9-9999-57d66e0926a9">
This is a bug described on the official gradio Repo, apparently fixed, but it seems like the fix was not implemented on the Auto UI included in this docker
https://github.com/gradio-app/gradio/issues/3248
https://github.com/gradio-app/gradio/pull/3277

**Which UI**

Automatic1111

**Hardware / Software**

- OS: Linux Lite (Ubuntu 22.04)
- OS version:
- WSL version (if applicable):
- Docker Version: 24.0.2
- Docker compose version: 2.18.1
- Repo version: latest, I just installed it 4 days ago
- RAM: 8GB
- GPU/VRAM: GTX 1080, 8gb

**Steps to Reproduce**

Create a new canvas using a extension that can create a new blank canvas (stable-diffusion-webui-two-shot in this case: https://github.com/ashen-sensored/stable-diffusion-webui-two-shot )

**Additional context**
This claims to be fixed in the current version of Gradio but that's not the case for me, the canvas will crash no matter which browser or device is used (tested chrome, firefox, safari, safari on iphone, chrome on android, they all resulted in the canvas or the entire webpage crashing)

**Comment by AbdBarho** [comment]
There is an update for auto that I haven't merged in yet because of gradio bug https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/507

I am waiting until this bug is fixed, otherwise controlnet would stop working.

Maybe after this update is merged, your issue will be resolved.
