### ISSUE TITLE
rsync chown error - container not starting

### ISSUE THREAD

**Issue by Robonau** [AbdBarho/stable-diffusion-webui-docker#534]
**Has this issue been opened before?**

- [ x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

```
docker compose --profile auto up

webui-docker-auto-1  | rsync: [generator] chown "/data/models/VAE-approx/." failed: Operation not permitted (1)
webui-docker-auto-1  | ./
webui-docker-auto-1  | model.pt
webui-docker-auto-1  | rsync: [receiver] chown "/data/models/VAE-approx/.model.pt.QLv0gb" failed: Operation not permitted (1)
webui-docker-auto-1  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
webui-docker-auto-1 exited with code 23
```

**Which UI**

auto

**Hardware / Software**

- OS: manjaro 23.0.0
- OS version: 23.0.0
- Docker Version: 24.0.0
- Docker compose version: 2.18.1
- Repo version: 8.0.0 (cloning from master has the same issue)
- RAM: 32GB
- GPU/VRAM: 8GB

**Steps to Reproduce**

clean install

**Additional context**
ive been running an older version for a while and decided to upgrade (with a clean install)
the files are on an nfs share but permissions are fine (the old version is also running on the same nfs share)

the `QLv0gb` in  `.model.pt.QLv0gb` seems to change randomly every time

`/models/VAE-approx/` is created and there is a `model.pt` file created before the crash

**Comment by Robonau** [comment]
nvm it was a permissions issue

**Comment by jo8282** [comment]
I did run in the exact same issue today on a fresh install, what permissions did you change?

**Comment by elelelelee1** [comment]
Same for me, fresh install.. Why it was closed?
