### ISSUE TITLE
 (root) Additional property name is not allowed

### ISSUE THREAD

**Issue by StrandingHeart** [AbdBarho/stable-diffusion-webui-docker#535]
$ docker compose --profile download up --build
(root) Additional property name is not allowed

Which version of docker-compose should be used? 

$ docker-compose version
Docker Compose version v2.19.0

I can't run docker-compose.yml in master properly

**Comment by alanextar** [comment]
same issue

**Comment by AbdBarho** [comment]
I am going to close this issue, if it still persists feel free to re-open or create another one
