### ISSUE TITLE
exit with code 1 while trying to stand Invoke AI

### ISSUE THREAD

**Issue by shreya-dama-Crafty-Apes-VFX** [AbdBarho/stable-diffusion-webui-docker#539]
**Has this issue been opened before?**

- [.] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [.] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Tried building the image for invoke using:
DOCKER_BUILDKIT=1 docker compose --profile invoke up --build

Ended up getting the following:
![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/117180689/1d7d6fa5-adcb-4cb8-b828-d446b8881992)

Then, ran the following to see if that would rectify the issue:
docker compose --profile download up --build
DOCKER_BUILDKIT=1 docker compose --profile invoke up --build

Got the following:
![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/117180689/7c6999eb-201e-406e-8695-4135d6d443df)

**Which UI**

auto or auto-cpu or invoke or sygil? Invoke

**Hardware / Software**

- OS: [e.g. Windows 10 / Ubuntu 22.04] Ubuntu 22.04
- OS version:  Description:    Ubuntu 22.04.1 LTS
- WSL version (if applicable):  N.A
- Docker Version:  Docker version 20.10.22, build 3a2c30b
- Docker compose version:  Docker Compose version v2.3.3
- Repo version:  latest version
- RAM: 24GB
- GPU/VRAM: Nvidia RTX A6000 with 48GB VRAM

**Steps to Reproduce**
The commands used were already mentioned above.

**Comment by AbdBarho** [comment]
from the screenshot it seems you were trying to run both the download and invoke simultaneously, this is not what you want, run the download first, wait until it is finished, and then run invoke.
