### ISSUE TITLE
ImportError: cannot import name 'auto' from 'tqdm' (/usr/local/lib/python3.10/site-packages/tqdm/__init__.py)

### ISSUE THREAD

**Issue by bg1avd** [AbdBarho/stable-diffusion-webui-docker#542]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**
When I run command "docker compose --profile auto up --build" to set auto ui docker image, this error pop up.

**Which UI**

auto 

**Hardware / Software**

- OS: Ubuntu 20.04
- Docker version 20.10.22, build 3a2c30b
- docker-compose version 1.29.1, build c34c88b2
- Repo version: "from master" 
- GPU/VRAM: 2080ti/22G

**Steps to Reproduce**
run: docker compose --profile auto up --build

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by bg1avd** [comment]
I try to follow you guide to upgrade tqdm package in docker container. But the error still at here.

**Comment by bg1avd** [comment]
I change some step of yours:

1.  Add in line 33 this  entrypoint: /bin/bash, This will lead to a shell instead of loading webui.
2.  At other terminal run: docker -it exec docker-container-name /bin/bash
3.  run commad : pip uninstall tqdm
4.  pip install tqdm and exit the docker container
5.  Remove the line in the docker-compose.yml file
6.  Start container as usual

**Comment by willcitizen** [comment]
putting pip install -U tqdm in data/config/auto/startup.sh also resolves for now.  I think the culprit may have been txt2video I saw it mentioned in a report elsewhere and it was one of the one's I was trying to install.

**Comment by AbdBarho** [comment]
I see, I will close this as an extension problem, it is almost impossible to not have these sort of issues, if it still persists, feel free to re-open.
