### ISSUE TITLE
FileNotFoundError if "Always save all generated images" is off

### ISSUE THREAD

**Issue by TheTerrasque** [AbdBarho/stable-diffusion-webui-docker#545]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

If "always save all generated images" is turned off, generating image fails with 
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/<tmp file name>.png'

Turning on the option makes it work as normal again.

**Which UI**

auto

**Hardware / Software**

- OS: Windows
- OS version: 
- WSL version (if applicable): 
- Docker Version: Docker Desktop 4.20.1
- Docker compose version: Docker Compose version v2.18.1
- Repo version: latest master / 103e11493b80d5f945eb61902a6ba23409abcd39
- RAM: 48gb
- GPU/VRAM: 10gb

**Steps to Reproduce**

1. Go to Settings
2. Turn off "Always save all generated images"
3. Save settings
4. Generate image
5. Find error in logs

**Full stack trace:**

webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
webui-docker-auto-1  |     output = await app.get_blocks().process_api(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
webui-docker-auto-1  |     data = self.postprocess_data(fn_index, result["prediction"], state)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1260, in postprocess_data
webui-docker-auto-1  |     prediction_value = block.postprocess(prediction_value)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/components.py", line 4461, in postprocess
webui-docker-auto-1  |     file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui_tempdir.py", line 55, in save_pil_to_file
webui-docker-auto-1  |     file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/tempfile.py", line 559, in NamedTemporaryFile
webui-docker-auto-1  |     file = _io.open(dir, mode, buffering=buffering,
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/tempfile.py", line 556, in opener
webui-docker-auto-1  |     fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
webui-docker-auto-1  |     fd = _os.open(file, flags, 0o600)
webui-docker-auto-1  | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/tmpmt6pqpiq.png'

**Comment by mwhaite** [comment]
try this:
```
docker ps
docker exec -it <container> sh
# mkdir /tmp/gradio
# exit
```

then try to run again.  I think this can be snuck into the startup script.
