### ISSUE TITLE
Scripts error on ARM based CPU

### ISSUE THREAD

**Issue by befantasy** [AbdBarho/stable-diffusion-webui-docker#548]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

My cpu is ARM based. When I enter the command "docker compose --profile auto-cpu up --build".

after a while, it report the error log as below:
`16.04 ERROR: torch-2.0.1-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.`

The scripts download the x86_64 package of torch. 

**Which UI**
auto-cpu

**Hardware / Software**

- OS: [RHEL]
- OS version: 8.7
- WSL version (if applicable): 
- Docker Version: 
- Docker compose version: 
- Repo version: 
- RAM:
- GPU/VRAM:

**Steps to Reproduce**

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by AbdBarho** [comment]
is pytorch available for arm cpus? probably because it depends on some SIMD instruction specific to x86 for perf reasons?

Can you run pytorch in general on your cpu and do any computations?

**Comment by befantasy** [comment]
Thanks for your reply.
I don't know much about pytorch, can you teach me how to test it? 
I was thinking, could there be something wrong with the startup script, shouldn't the arm version of torch be executed? 

`16.04 ERROR: torch-2.0.1-cp310-cp310-linux_**x86_64**.whl is not a supported wheel on this platform.`

**Comment by AbdBarho** [comment]
Hi I did a bit of digging and found out that xformers does not yet provide compiled wheels for ARM, all running jobs seem to be x86
https://github.com/facebookresearch/xformers/actions/runs/5654351480

Unfortunately, I cannot do anything here.
