### ISSUE TITLE
Build fails with credentials errors when logged in via SSH on WSL2/Windows

### ISSUE THREAD

**Issue by jasalt** [AbdBarho/stable-diffusion-webui-docker#56]
Had trouble controlling Docker Compose remotely via SSH on Win/WSL2 while there were no errors with  regular Windows desktop session. Seems like logging in via SSH messes up the Docker Desktop's credit store access with WSL somehow where `docker compose --profile hlky up --build`, `docker compose --profile auto restart` or just `docker login` would end with:

```
Error saving credentials: error storing credentials - err: exit status 1, out: `A specified logon session does not exist. It may already have been terminated.`
```

Got it to work by forcing plain text auth creds storage by removing line with "credStore" from `~/.docker/config.json` (in WSL) and then `docker login` and `docker compose` commands worked. Used a read-only access token made on Docker Hub site for safety as a password. Might need to be redone after reboot as config.json file is controlled by Docker Desktop app where some seem to have set that file read-only to keep it from changing with some possible side effects.

There were some open issues on Docker and Docker Compose issue trackers with this workaround but leaving this as a note here, could maybe moved to wiki.

**Comment by AbdBarho** [comment]
@jasalt Thanks! added to the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ#build-fails-with-credentials-errors-when-logged-in-via-ssh-on-wsl2windows).

Do you have links to the issues in Docker or Docker compose issue trackers? maybe we could add them here for reference

**Comment by jasalt** [comment]
Few more or less related issues:

https://github.com/docker/compose/issues/7273
https://github.com/docker/cli/issues/2682
https://github.com/docker/for-win/issues/9061
https://github.com/docker/for-win/issues/11261
https://github.com/docker/for-win/issues/12888
