### ISSUE TITLE
Comfy exited with code 1

### ISSUE THREAD

**Issue by shreya-dama-Crafty-Apes-VFX** [AbdBarho/stable-diffusion-webui-docker#564]
Has this issue been opened before?

[.] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
[.] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

Describe the bug

Tried building the image for comfy using:
DOCKER_BUILDKIT=1 docker compose --profile comfy up --build

It exited with code 1

**Which UI**
comfy

**Hardware / Software**
OS: [e.g. Windows 10 / Ubuntu 22.04] Ubuntu 22.04
OS version: Description: Ubuntu 22.04.1 LTS
WSL version (if applicable): N.A
Docker Version: Docker version 20.10.22, build 3a2c30b
Docker compose version: Docker Compose version v2.3.3
Repo version: latest version
RAM: 24GB
GPU/VRAM: Nvidia RTX A6000 with 48GB VRAM

<img width="704" alt="image" src="https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/117180689/6407c5f5-36c9-4f54-8b34-62e0d20f1aa8">

**Comment by AbdBarho** [comment]
sorry for coming back late for this, I wanted to do an update to comfy soon, maybe your problem would be resolved, because honestly I have no idea what is the problem here.
