### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by nghuy18102** [AbdBarho/stable-diffusion-webui-docker#565]
![Screenshot 2023-08-03 143718](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/115967963/4fc9eb20-1dfd-4b19-bb0d-37c95a59df95)
i try to instal Temporal Kit but it always show me this 
How can i fix this ? Thank You!

**Comment by AbdBarho** [comment]
I don't this is the right repo for the issue you are having, you should check upstream.

Here is the docker container only.
