### ISSUE TITLE
Qeustion: why are there so many deps installed in the Dockerfile?

### ISSUE THREAD

**Issue by dongwangdw** [AbdBarho/stable-diffusion-webui-docker#568]
As I can find Mac is supported by AUTOMATIC1111. And this repos is just a wrapper why there are so many deps installed in the 
Dockerfile? Can I just remove them all?

From [doc](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Installation-on-Apple-Silicon#new-install), it says just run `./webui.sh`.

I try to start this from M1 but failed. 
Thanks.

BTW: there are only two options for the issue. I have to choose bug.

**Comment by DevilaN** [comment]
Maybe you should use discussion thread?

**Comment by AbdBarho** [comment]
Most users of this repo are:
* not proficient in docker / containers (or arguably programming at all)
* want to use the all the new cool extensions which require many external dependencies

In the beginning I recommended everyone to use the `startup.sh` script to install all the packages, but no one would listen and I would just get loads of issues, discussion, and PRs just to add them to the container.

I finally gave up and added them. I am not really happy with that, but the amount of complains went down a lot, so arguably it was worth it, for a peace of mind.

Feel free to get rid of all of them on your local machine, I have split so you can get rid of the ones you might not need
```sh
# we need those
apt-get install -y fonts-dejavu-core rsync git jq moreutils aria2 \
# extensions needs those
ffmpeg libglfw3-dev libgles2-mesa-dev pkg-config libcairo2 libcairo2-dev build-essential
```

the first ones are necessary for the container to work, the rest can be deleted.


Regarding mac support #35, this is still an open issue and I don't have any hardware to test on.

Until we get an official pytorch container for arm64, adding mac support would be hairy.
