### ISSUE TITLE
Fails on run: nvidia-container-cli: container error: cgroup subsystem devices not found: unknown

### ISSUE THREAD

**Issue by rocapp** [AbdBarho/stable-diffusion-webui-docker#571]
## **Has this issue been opened before?**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

## **Describe the bug**

Failed on `Running...` (after second `docker compose` call).

#### Successful Output:

    webui-docker-download-1  | Download Results:
    webui-docker-download-1  | gid   |stat|avg speed  |path/URI
    webui-docker-download-1  | ======+====+===========+=======================================================
    webui-docker-download-1  | a91e5a|OK  |   4.2MiB/s|/data/models/RealESRGAN/RealESRGAN_x4plus.pth
    webui-docker-download-1  | 75525d|OK  |    11MiB/s|/data/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.pth
    webui-docker-download-1  | c88818|OK  |    18MiB/s|/data/models/GFPGAN/GFPGANv1.4.pth
    webui-docker-download-1  | f79ce3|OK  |    14MiB/s|/data/models/VAE/vae-ft-mse-840000-ema-pruned.ckpt
    webui-docker-download-1  | b07466|OK  |    19KiB/s|/data/models/LDSR/project.yaml
    webui-docker-download-1  | 97d034|OK  |    40MiB/s|/data/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
    webui-docker-download-1  | d946f1|OK  |    27MiB/s|/data/models/Stable-diffusion/sd-v1-5-inpainting.ckpt
    webui-docker-download-1  | c75838|OK  |   8.5MiB/s|/data/models/LDSR/model.ckpt
    webui-docker-download-1  | 
    webui-docker-download-1  | Status Legend:
    webui-docker-download-1  | (OK):download completed.
    webui-docker-download-1  | 
    webui-docker-download-1  | Checking SHAs...
    webui-docker-download-1  | /data/models/LDSR/project.yaml: OK
    webui-docker-download-1  | /data/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.pth: OK
    webui-docker-download-1  | /data/models/RealESRGAN/RealESRGAN_x4plus.pth: OK
    webui-docker-download-1  | /data/models/VAE/vae-ft-mse-840000-ema-pruned.ckpt: OK
    webui-docker-download-1  | /data/models/GFPGAN/GFPGANv1.4.pth: OK
    webui-docker-download-1  | /data/models/LDSR/model.ckpt: OK
    webui-docker-download-1  | /data/models/Stable-diffusion/sd-v1-5-inpainting.ckpt: OK
    webui-docker-download-1  | /data/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt: OK
    webui-docker-download-1  | By using this software, you agree to the following licenses:
    webui-docker-download-1  | https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/LICENSE
    webui-docker-download-1  | https://github.com/CompVis/stable-diffusion/blob/main/LICENSE
    webui-docker-download-1  | https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/LICENSE.txt
    webui-docker-download-1  | https://github.com/invoke-ai/InvokeAI/blob/main/LICENSE
    webui-docker-download-1  | And licenses of all UIs, third party libraries, and extensions.
    webui-docker-download-1 exited with code 0

#### Failed Output: 

    [+] Building 304.3s (19/19) FINISHED                                                                                            docker:default
     => [comfy internal] load .dockerignore                                                                                                   0.0s
     => => transferring context: 2B                                                                                                           0.0s
     => [comfy internal] load build definition from Dockerfile                                                                                0.0s
     => => transferring dockerfile: 1.56kB                                                                                                    0.0s
     => [comfy internal] load metadata for docker.io/pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime                                            6.0s
     => [comfy internal] load metadata for docker.io/library/alpine:3.17                                                                      6.2s
     => [comfy internal] load build context                                                                                                   0.0s
     => => transferring context: 2.95kB                                                                                                       0.0s
     => [comfy xformers 1/3] FROM docker.io/library/alpine:3.17@sha256:f71a5f071694a785e064f05fed657bf8277f1b2113a8ed70c90ad486d6ee54dc       1.2s
     => => resolve docker.io/library/alpine:3.17@sha256:f71a5f071694a785e064f05fed657bf8277f1b2113a8ed70c90ad486d6ee54dc                      0.0s
     => => sha256:f71a5f071694a785e064f05fed657bf8277f1b2113a8ed70c90ad486d6ee54dc 1.64kB / 1.64kB                                            0.0s
     => => sha256:7298bd41b8aee1adde2a0a2819f695b5057bfd0234bf250f0e5d9946c7ab38bd 528B / 528B                                                0.0s
     => => sha256:1e0b8b5322fc6afc339bb325d3ec739cba6e87a7f0bb4b7e55b52f7feb965dd3 1.47kB / 1.47kB                                            0.0s
     => => sha256:9398808236ffac29e60c04ec906d8d409af7fa19dc57d8c65ad167e9c4967006 3.38MB / 3.38MB                                            0.9s
     => => extracting sha256:9398808236ffac29e60c04ec906d8d409af7fa19dc57d8c65ad167e9c4967006                                                 0.1s
     => [comfy stage-1  1/10] FROM docker.io/pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime@sha256:82e0d379a5dedd6303c89eda57bcc434c40be11f  150.4s
     => => resolve docker.io/pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime@sha256:82e0d379a5dedd6303c89eda57bcc434c40be11f249ddfadfd5673b843  0.0s
     => => sha256:82e0d379a5dedd6303c89eda57bcc434c40be11f249ddfadfd5673b84351e806 1.37kB / 1.37kB                                            0.0s
     => => sha256:26551f1051e710ecfc62bf6396fc67722f2ae0489be5e8cc6b7fc8de0926866e 4.85kB / 4.85kB                                            0.0s
     => => sha256:99803d4b97f3db529ae9ca4174b0951afac6b309e7deaa8ec3214c584e02b3a8 28.58MB / 28.58MB                                          0.5s
     => => sha256:4ade0a4bc5d597c845bc3c27c47453522019ee188adbc4110029bbea11e5adec 9.99MB / 9.99MB                                            0.6s
     => => sha256:035a286326d65b413051a4c52e7df0037d89f1075f7be98c9586d1c856ace994 3.11GB / 3.11GB                                           41.1s
     => => extracting sha256:99803d4b97f3db529ae9ca4174b0951afac6b309e7deaa8ec3214c584e02b3a8                                                 1.0s
     => => sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B                                                  0.7s
     => => sha256:2185b402c9ca9c9a1e03db5b387fe9a1dc43c1247bf41199b18e901c2e44ff35 99B / 99B                                                  0.7s
     => => extracting sha256:4ade0a4bc5d597c845bc3c27c47453522019ee188adbc4110029bbea11e5adec                                                 0.5s
     => => extracting sha256:035a286326d65b413051a4c52e7df0037d89f1075f7be98c9586d1c856ace994                                                85.0s
     => => extracting sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1                                                 0.0s
     => => extracting sha256:2185b402c9ca9c9a1e03db5b387fe9a1dc43c1247bf41199b18e901c2e44ff35                                                 0.0s  => [comfy xformers 2/3] RUN apk add --no-cache aria2                                                                                     3.5s  => [comfy xformers 3/3] RUN aria2c -x 5 --dir / --out wheel.whl 'https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/do  36.4s  => [comfy stage-1  2/10] RUN apt-get update && apt-get install -y git && apt-get clean                                                  42.0s  => [comfy stage-1  3/10] RUN --mount=type=cache,target=/root/.cache/pip   git clone https://github.com/comfyanonymous/ComfyUI.git /sta  59.1s
     => [comfy stage-1  4/10] RUN --mount=type=cache,target=/root/.cache/pip    --mount=type=bind,from=xformers,source=/wheel.whl,target=/x  26.2s
     => [comfy stage-1  5/10] WORKDIR /stable-diffusion                                                                                       0.9s
     => [comfy stage-1  6/10] RUN --mount=type=cache,target=/root/.cache/pip   git fetch &&   git checkout master &&   git reset --hard 8607  8.5s
     => [comfy stage-1  7/10] COPY . /docker/                                                                                                 0.5s
     => [comfy stage-1  8/10] RUN cp /docker/extra_model_paths.yaml /stable-diffusion                                                         0.5s
     => [comfy stage-1  9/10] RUN chmod u+x /docker/entrypoint.sh                                                                             0.5s
     => [comfy stage-1 10/10] RUN cp /docker/extra_model_paths.yaml /stable-diffusion                                                         0.4s
     => [comfy] exporting to image                                                                                                            8.4s
     => => exporting layers                                                                                                                   8.2s
     => => writing image sha256:51c1c277077fac5ec6876ac9db4c6308d48504b6a51526c762c938a2983c2d49                                              0.1s
     => => naming to docker.io/library/sd-comfy:4                                                                                             0.1s
    [+] Running 1/1
     ✔ Container webui-docker-comfy-1  Created                                                                                                0.7s Attaching to webui-docker-comfy-1
    Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=0 --compute --utility --pid=321689 /var/lib/docker/overlay2/5a771a921a7d8dbd3cafc9be88fb635a509a82c64706aad54f1b9d9bb9977e08/merged]
    nvidia-container-cli: container error: cgroup subsystem devices not found: unknown

#### Failed Output (2):

      [+] Building 788.1s (33/33) FINISHED                                                                                            docker:default
       => [auto internal] load .dockerignore                                                                                                    0.1s
       => => transferring context: 2B                                                                                                           0.0s
       => [auto internal] load build definition from Dockerfile                                                                                 0.1s
       => => transferring dockerfile: 4.28kB                                                                                                    0.0s
       => [auto internal] load metadata for docker.io/library/python:3.10.9-slim                                                                6.5s
       => [auto internal] load metadata for docker.io/alpine/git:2.36.2                                                                         6.4s
       => [auto internal] load metadata for docker.io/library/alpine:3.17                                                                       6.0s
       => [auto internal] load build context                                                                                                    0.1s
       => => transferring context: 9.38kB                                                                                                       0.0s
       => [auto xformers 1/3] FROM docker.io/library/alpine:3.17@sha256:f71a5f071694a785e064f05fed657bf8277f1b2113a8ed70c90ad486d6ee54dc        0.0s
       => [auto stage-2  1/14] FROM docker.io/library/python:3.10.9-slim@sha256:76dd18d90a3d8710e091734bf2c9dd686d68747a51908db1e1f41e9a5ed4e2  7.4s
       => => resolve docker.io/library/python:3.10.9-slim@sha256:76dd18d90a3d8710e091734bf2c9dd686d68747a51908db1e1f41e9a5ed4e2c5               0.2s
       => => sha256:e15bb169d3a85f7e9c0f2d105ce628f13d71aed44b5d3d230b88f9653a9b19d5 1.37kB / 1.37kB                                            0.0s
       => => sha256:343cc23871cfcec31fcf0681d5107e22d4fa214fad76deec63868835ad06849e 7.79kB / 7.79kB                                            0.0s
       => => sha256:76dd18d90a3d8710e091734bf2c9dd686d68747a51908db1e1f41e9a5ed4e2c5 1.86kB / 1.86kB                                            0.0s
       => => sha256:01b5b2efb836d74b8b49da819514eca52e25290d1688db59420ffb9c6b65a03c 31.40MB / 31.40MB                                          1.2s
       => => sha256:5dda314a937ad03f8beac81c714da74e459b6174301368e0903ef586a68ae150 1.08MB / 1.08MB                                            0.4s
       => => sha256:11d639c994a82f2fc3c071bc85b7fa8fb341d4186e1b1c535f8d4147b07f78cd 11.74MB / 11.74MB                                          0.8s
       => => sha256:d1465593fd9b15a8d99135d267721127f140c979a8831c320e1f326b830d2721 233B / 233B                                                0.6s
       => => sha256:4a6d0cbbdb413b71a251597fa3b79f3c0ec3ed7b7c1ee8ae3d4fe4fe053a04a4 3.35MB / 3.35MB                                            1.2s
       => => extracting sha256:01b5b2efb836d74b8b49da819514eca52e25290d1688db59420ffb9c6b65a03c                                                 1.3s
       => => extracting sha256:5dda314a937ad03f8beac81c714da74e459b6174301368e0903ef586a68ae150                                                 0.1s
       => => extracting sha256:11d639c994a82f2fc3c071bc85b7fa8fb341d4186e1b1c535f8d4147b07f78cd                                                 0.4s
       => => extracting sha256:d1465593fd9b15a8d99135d267721127f140c979a8831c320e1f326b830d2721                                                 0.0s
       => => extracting sha256:4a6d0cbbdb413b71a251597fa3b79f3c0ec3ed7b7c1ee8ae3d4fe4fe053a04a4                                                 0.2s
       => [auto download 1/9] FROM docker.io/alpine/git:2.36.2@sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c713fa5e1c75dea84          5.5s
       => => resolve docker.io/alpine/git:2.36.2@sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c713fa5e1c75dea84                        0.2s
       => => sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c713fa5e1c75dea84 2.03kB / 2.03kB                                            0.0s
       => => sha256:a3e645585f160e0589529b8a3ca0fcfdba717ab93507de39ba5a96e207972927 946B / 946B                                                0.0s
       => => sha256:b80d2cac43e471c2bc5cfe547a45104e69e1b194f6f3f15ba1214f5e3020575e 1.85kB / 1.85kB                                            0.0s
       => => sha256:3fd92eeca8f54976c24de929011349e191dc349bf932629be5ac6fdf1d1c25df 99B / 99B                                                  1.5s
       => => sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49 2.81MB / 2.81MB                                            1.5s
       => => sha256:b3b6ac3db031ea7b3607e700555c68707f072c457cb4e5511c12cf529656d437 18.49MB / 18.49MB                                          1.8s
       => => extracting sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49                                                 0.1s
       => => extracting sha256:b3b6ac3db031ea7b3607e700555c68707f072c457cb4e5511c12cf529656d437                                                 0.5s
       => => extracting sha256:3fd92eeca8f54976c24de929011349e191dc349bf932629be5ac6fdf1d1c25df                                                 0.0s
       => CACHED [auto xformers 2/3] RUN apk add --no-cache aria2                                                                               0.0s
       => CACHED [auto xformers 3/3] RUN aria2c -x 5 --dir / --out wheel.whl 'https://github.com/AbdBarho/stable-diffusion-webui-docker/releas  0.0s
       => [auto download 2/9] COPY clone.sh /clone.sh                                                                                           1.1s
       => [auto download 3/9] RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fdd  6.8s
       => [auto stage-2  2/14] RUN --mount=type=cache,target=/var/cache/apt   apt-get update &&   apt-get install -y fonts-dejavu-core rsync  203.9s
       => [auto download 4/9] RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git 47b6b607fdd318  8.2s
       => [auto download 5/9] RUN . /clone.sh CodeFormer https://github.com/sczhou/CodeFormer.git c5b4593074ba6214284d6acd5f1719b6c5d739af   &  2.1s
       => [auto download 6/9] RUN . /clone.sh BLIP https://github.com/salesforce/BLIP.git 48211a1594f1321b00f14c9f7a5b4813144b2fb9              1.5s
       => [auto download 7/9] RUN . /clone.sh k-diffusion https://github.com/crowsonkb/k-diffusion.git c9fe758757e022f05ca5a53fa8fac28889e4f1c  0.7s
       => [auto download 8/9] RUN . /clone.sh clip-interrogator https://github.com/pharmapsychotic/clip-interrogator 2486589f24165c8e3b303f84e  0.9s
       => [auto download 9/9] RUN . /clone.sh generative-models https://github.com/Stability-AI/generative-models 45c443b316737a4ab6e40413d779  1.2s
       => [auto stage-2  3/14] RUN --mount=type=cache,target=/cache --mount=type=cache,target=/root/.cache/pip   aria2c -x 5 --dir /cache --  206.7s
       => [auto stage-2  4/14] RUN --mount=type=cache,target=/root/.cache/pip   git clone https://github.com/AUTOMATIC1111/stable-diffusion-  152.5s
       => [auto stage-2  5/14] RUN --mount=type=cache,target=/root/.cache/pip    --mount=type=bind,from=xformers,source=/wheel.whl,target=/xf  20.1s
       => [auto stage-2  6/14] COPY --from=download /repositories/ /stable-diffusion-webui/repositories/                                        1.8s
       => [auto stage-2  7/14] RUN mkdir /stable-diffusion-webui/interrogate && cp /stable-diffusion-webui/repositories/clip-interrogator/data  0.6s
       => [auto stage-2  8/14] RUN --mount=type=cache,target=/root/.cache/pip   pip install -r /stable-diffusion-webui/repositories/CodeForme  13.8s
       => [auto stage-2  9/14] RUN --mount=type=cache,target=/root/.cache/pip   pip install pyngrok   git+https://github.com/TencentARC/GFPGA  94.6s
       => [auto stage-2 10/14] RUN apt-get -y install libgoogle-perftools-dev && apt-get clean                                                 18.6s
       => [auto stage-2 11/14] RUN --mount=type=cache,target=/root/.cache/pip   cd stable-diffusion-webui &&   git fetch &&   git reset --har  25.5s
       => [auto stage-2 12/14] COPY . /docker                                                                                                   0.5s
       => [auto stage-2 13/14] RUN   python3 /docker/info.py /stable-diffusion-webui/modules/ui.py &&   mv /stable-diffusion-webui/style.css /  0.8s
       => [auto stage-2 14/14] WORKDIR /stable-diffusion-webui                                                                                  0.5s
       => [auto] exporting to image                                                                                                            33.2s
       => => exporting layers                                                                                                                  33.1s
       => => writing image sha256:57934765c9d9600945ef050217059b1080d7c56d9729223e26e2d6a9dd653bee                                              0.1s
       => => naming to docker.io/library/sd-auto:63                                                                                             0.1s
      [+] Running 1/1
       ✔ Container webui-docker-auto-1  Created                                                                                                 1.0s Attaching to webui-docker-auto-1
      Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=0 --compute --utility --pid=368477 /var/lib/docker/overlay2/0c78ddd34f7d53e91dd2e1f4e5331492dd473d01d5a38747b45982c2632df5b2/merged]
      nvidia-container-cli: container error: cgroup subsystem devices not found: unknown

## **Which UI**

auto or auto-cpu or invoke or sygil?

**Tried:** `auto`, `comfy`

**Hardware / Software**

- OS: `Arch Linux`
- OS version: `Linux Z38S 6.4.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 11 Aug 2023 11:03:36 +0000 x86_64 GNU/Linux`
- Docker Version: 

        Client:
         Version:           24.0.5
         API version:       1.43
         Go version:        go1.20.6
         Git commit:        ced0996600
         Built:             Wed Jul 26 21:44:58 2023
         OS/Arch:           linux/amd64
         Context:           default
        
        Server:
         Engine:
          Version:          24.0.5
          API version:      1.43 (minimum version 1.12)
          Go version:       go1.20.6
          Git commit:       a61e2b4c9c
          Built:            Wed Jul 26 21:44:58 2023
          OS/Arch:          linux/amd64
          Experimental:     false
         containerd:
          Version:          v1.7.2
          GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58.m
         runc:
          Version:          1.1.9
          GitCommit:        
         docker-init:
          Version:          0.19.0
          GitCommit:        de40ad0

- Docker compose version: `2.20.3`
- Repo version: `master`
- RAM: `31Gi`
- GPU/VRAM: `4096MB`

### **Additional context**

**Possibly relevant issues:**

Found a few instances of the same error message, but these appear to be for a different version of nvidia & specific to PopOS.
- https://github.com/NVIDIA/nvidia-docker/issues/1660
- https://github.com/NVIDIA/nvidia-docker/issues/1447

**Possibly relevant note:** I use a DisplayLink dock that requires a bunch of extra graphics & display configuration (including a custom EVDI module from AUR).

**Comment by rocapp** [comment]
### Update: Testing possible fix

It turns out the existing issues might be relevant after all...

**When I try:**

`docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 bash -c "ldconfig; nvidia-smi"`

...I get the original error, which is the same error described in the [first issue I linked.](https://github.com/NVIDIA/nvidia-docker/issues/1660#issue-1329086102).

**Suggested fix:** https://gist.github.com/kuang-da/2796a792ced96deaf466fdfb7651aa2e

...Currently trying this. I'll update again shortly.

**Comment by rocapp** [comment]
### No luck with that fix... however I learned a little more about the issue.

I tried running the `invoke` container, giving explicit access to the GPU (and the NVIDIA runtime): 

`docker run --gpus all --runtime nvidia sd-invoke:30`

The error is now different:

      docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:275: applying cgroup configuration for process caused \"mountpoint for devices not found\"": unknown.
      ERRO[0000] error waiting for container: 

...so that still seems to point to a cgroup configuration issue, possibly solvable by switching to a different kernel version.


### Out of curiosity, I also tried running the container without specifying any options:

`docker run sd-invoke:30`

The output points to a completely different issue that makes me wonder if one set of errors might be masking the actual cause of the failure:

    mkdir: created directory '/data/.cache'
    mkdir: created directory '/data/.cache/invoke'
    mkdir: created directory '/data/.cache/invoke/ldm/'
    Mounted ldm
    Mounted .cache
    mkdir: created directory '/data/models'
    mkdir: created directory '/data/models/RealESRGAN/'
    Mounted RealESRGAN
    mkdir: created directory '/data/models/Codeformer/'
    Mounted Codeformer
    mkdir: created directory '/data/models/GFPGAN/'
    Mounted GFPGAN
    Mounted GFPGANv1.4.pth
    Traceback (most recent call last):
      File "/opt/conda/bin/invokeai", line 5, in <module>
        from ldm.invoke.CLI import main
      File "/InvokeAI/ldm/invoke/CLI.py", line 21, in <module>
        from ..generate import Generate
      File "/InvokeAI/ldm/generate.py", line 32, in <module>
        from pytorch_lightning import logging, seed_everything
      File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
        from pytorch_lightning.callbacks import Callback  # noqa: E402
      File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 25, in <module>
        from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
      File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/__init__.py", line 22, in <module>
        from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
      File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/rich_progress.py", line 20, in <module>
        from torchmetrics.utilities.imports import _compare_version
    ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/opt/conda/lib/python3.10/site-packages/torchmetrics/utilities/imports.py)

...Signing off for now. I'll check this again tomorrow with a fresh pair of eyes, as I suspect there's a fairly simple kernel or other dependency-versioning-related fix.

**Comment by DevilaN** [comment]
What's your output from `/usr/share/docker/contrib/check-config.sh` ???

**Comment by rocapp** [comment]
@DevilaN I didn't have the `docker/contrib` extras installed, but I was able to download and run `check-config.sh`-- seemed to work okay... please let me know if I can provide any further relevant info. Thanks!

    info: reading kernel config from /proc/config.gz ...
    
    Generally Necessary:
    - cgroup hierarchy: cgroupv2
      Controllers:
      - cpu: available
      - cpuset: available
      - io: available
      - memory: available
      - pids: available
    - CONFIG_NAMESPACES: enabled
    - CONFIG_NET_NS: enabled
    - CONFIG_PID_NS: enabled
    - CONFIG_IPC_NS: enabled
    - CONFIG_UTS_NS: enabled
    - CONFIG_CGROUPS: enabled
    - CONFIG_CGROUP_CPUACCT: enabled
    - CONFIG_CGROUP_DEVICE: enabled
    - CONFIG_CGROUP_FREEZER: enabled
    - CONFIG_CGROUP_SCHED: enabled
    - CONFIG_CPUSETS: enabled
    - CONFIG_MEMCG: enabled
    - CONFIG_KEYS: enabled
    - CONFIG_VETH: enabled (as module)
    - CONFIG_BRIDGE: enabled (as module)
    - CONFIG_BRIDGE_NETFILTER: enabled (as module)
    - CONFIG_IP_NF_FILTER: enabled (as module)
    - CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
    - CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
    - CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
    - CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
    - CONFIG_NETFILTER_XT_MARK: enabled (as module)
    - CONFIG_IP_NF_NAT: enabled (as module)
    - CONFIG_NF_NAT: enabled (as module)
    - CONFIG_POSIX_MQUEUE: enabled
    - CONFIG_CGROUP_BPF: enabled
    
    Optional Features:
    - CONFIG_USER_NS: enabled
    - CONFIG_SECCOMP: enabled
    - CONFIG_SECCOMP_FILTER: enabled
    - CONFIG_CGROUP_PIDS: enabled
    - CONFIG_MEMCG_SWAP: missing
        (cgroup swap accounting is currently enabled)
    - CONFIG_BLK_CGROUP: enabled
    - CONFIG_BLK_DEV_THROTTLING: enabled
    - CONFIG_CGROUP_PERF: enabled
    - CONFIG_CGROUP_HUGETLB: enabled
    - CONFIG_NET_CLS_CGROUP: enabled (as module)
    - CONFIG_CGROUP_NET_PRIO: enabled
    - CONFIG_CFS_BANDWIDTH: enabled
    - CONFIG_FAIR_GROUP_SCHED: enabled
    - CONFIG_RT_GROUP_SCHED: missing
    - CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
    - CONFIG_IP_VS: enabled (as module)
    - CONFIG_IP_VS_NFCT: enabled
    - CONFIG_IP_VS_PROTO_TCP: enabled
    - CONFIG_IP_VS_PROTO_UDP: enabled
    - CONFIG_IP_VS_RR: enabled (as module)
    - CONFIG_SECURITY_SELINUX: enabled
    - CONFIG_SECURITY_APPARMOR: enabled
    - CONFIG_EXT4_FS: enabled (as module)
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
    - Network Drivers:
      - "overlay":
        - CONFIG_VXLAN: enabled (as module)
        - CONFIG_BRIDGE_VLAN_FILTERING: enabled
          Optional (for encrypted networks):
          - CONFIG_CRYPTO: enabled
          - CONFIG_CRYPTO_AEAD: enabled (as module)
          - CONFIG_CRYPTO_GCM: enabled (as module)
          - CONFIG_CRYPTO_SEQIV: enabled (as module)
          - CONFIG_CRYPTO_GHASH: enabled (as module)
          - CONFIG_XFRM: enabled
          - CONFIG_XFRM_USER: enabled
          - CONFIG_XFRM_ALGO: enabled
          - CONFIG_INET_ESP: enabled (as module)
      - "ipvlan":
        - CONFIG_IPVLAN: enabled (as module)
      - "macvlan":
        - CONFIG_MACVLAN: enabled (as module)
        - CONFIG_DUMMY: enabled (as module)
      - "ftp,tftp client in container":
        - CONFIG_NF_NAT_FTP: enabled (as module)
        - CONFIG_NF_CONNTRACK_FTP: enabled (as module)
        - CONFIG_NF_NAT_TFTP: enabled (as module)
        - CONFIG_NF_CONNTRACK_TFTP: enabled (as module)
    - Storage Drivers:
      - "aufs":
        - CONFIG_AUFS_FS: missing
      - "btrfs":
        - CONFIG_BTRFS_FS: enabled (as module)
        - CONFIG_BTRFS_FS_POSIX_ACL: enabled
      - "devicemapper":
        - CONFIG_BLK_DEV_DM: enabled (as module)
        - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
      - "overlay":
        - CONFIG_OVERLAY_FS: enabled (as module)
      - "zfs":
        - /dev/zfs: missing
        - zfs command: missing
        - zpool command: missing
    
    Limits:
    - /proc/sys/kernel/keys/root_maxkeys: 1000000

**Comment by DevilaN** [comment]
Docker seems to have proper configuration.
From what I understand, there is problem with libnvidia-container not supporting cgroupv2 properly as expected by  your docker instance (based on system configuration). This normally has no impact on regular docker tasks, but seems to be no go for nvidia container toolkit.
Try reverting to v1 like mentioned in this comment: https://github.com/pop-os/tensorman/issues/34#issuecomment-1019347508

**Comment by AbdBarho** [comment]
thanks @DevilaN I think you are on the right track

@rocapp can you try `auto-cpu`? this container does not require a gpu or the nvidia-container-toolkit to run.

if it works, then we know the culprit, if not, we have more digging to do.

**Comment by rocapp** [comment]
@AbdBarho, good thinking! `auto-cpu` does in fact work... the plot thickens...
