### ISSUE TITLE
embeddings ?

### ISSUE THREAD

**Issue by simonmcnair** [AbdBarho/stable-diffusion-webui-docker#572]
I can see the TI embeddings in the ui, but they don't appear to work anymore.  In addition when it used to start it listed all the embeddings and it doesn't any longer.  Just me ?

**Comment by DevilaN** [comment]
Can you provide required info in bug filling form? You didn't even provide name of GUI you are using :/

**Comment by simonmcnair** [comment]
I apologise.  I guess my point was that it was working, and now it isn't.  My config hasn't changed in any way that would stop it from working, but I will try removing all extensions in a minute.  UI is auto

**Comment by simonmcnair** [comment]
So removing the extensions didn't work.  I treid removing all the TI's except one, still doesn't appear to work (i.e. the generated image does not really represent the TI.  I have noticed this though https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0aa8d538e147ba87df36d8196845807c8fa3f4e1

**Comment by simonmcnair** [comment]
Okay, it seems that they do work, but it no longer reports through the logs, or through the webui where it used to say 'used xyz embedding'

**Comment by simonmcnair** [comment]
upstream changes.
