### ISSUE TITLE
Error loading the setting file txt

### ISSUE THREAD

**Issue by kekike00** [AbdBarho/stable-diffusion-webui-docker#576]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I was using deforum, and trying to load a setting file with it's full path. However, there are only errors. This txt file is auto-generated when I used deforum to generate a video. How can I load this txt as settings to deforum again?

**Comment by AbdBarho** [comment]
where is the file generated? did you mount any additional folders?
https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Usage#mounts
