### ISSUE TITLE
Comfy extension for WebUI

### ISSUE THREAD

**Issue by strblr** [AbdBarho/stable-diffusion-webui-docker#589]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Comfy existing as an extension for WebUI, I tried to install it via the interface, but it's trying to load an iframe to access it and it can't:

![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/30187797/7d969c36-54a4-4db5-bb5c-82b8465ffa58)

**Which UI**

auto

**Hardware / Software**

- OS: Manjaro
- OS version: Uranos 23.0.1
- Docker Version: 24.0.5
- Docker compose version: 2.20.3
- Repo version: master
- RAM:
- GPU/VRAM:

**Steps to Reproduce**

1. Install the extension https://github.com/ModelSurge/sd-webui-comfyui via the webui extensions
2. Reload
3. Can't charge the iframe

**Comment by cloudaxes** [comment]
Are you sure this is an issue with @AbdBarho's Docker container?  Can you confirm whether this works correctly or not when using Stable Diffusion without Docker?  If not, you may find better troubleshooting steps from Automatic1111's repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui.

**Comment by AbdBarho** [comment]
I have not tried to install the extension, but I think I have a guess what is happening:

The extension runs it's own server inside the container, lets say on port 3000, this port is only available inside the container, so any requests coming from your browser (which is outside) to localhost:3000 will resolve to nothing

One thing you try is to find the port that is run by the extension and expose it to the outside in docker compose file.
