### ISSUE TITLE
Cannot create directory, permission denied

### ISSUE THREAD

**Issue by Frityet** [AbdBarho/stable-diffusion-webui-docker#592]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

```yaml
❯ docker-compose --profile download up --build
Building download
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  6.656kB
Step 1/5 : FROM bash:alpine3.15
 ---> e6ec45344a58
Step 2/5 : RUN apk add parallel aria2
 ---> Using cache
 ---> cfe1249a580e
Step 3/5 : COPY . /docker
 ---> Using cache
 ---> bcbed565e454
Step 4/5 : RUN chmod +x /docker/download.sh
 ---> Using cache
 ---> 4bdbec4b195d
Step 5/5 : ENTRYPOINT ["/docker/download.sh"]
 ---> Using cache
 ---> 2e316be3d1d8
Successfully built 2e316be3d1d8
Successfully tagged sd-webui_download:latest
Starting sd-webui_download_1 ... done
Attaching to sd-webui_download_1
download_1   | mkdir: can't create directory '/data/.cache': Permission denied
download_1   | mkdir: can't create directory '/data/embeddings': Permission denied
download_1   | mkdir: can't create directory '/data/config/': Permission denied
download_1   | mkdir: can't create directory '/data/models/': Permission denied
download_1   | mkdir: can't create directory '/data/models/': Permission denied
download_1   | mkdir: can't create directory '/data/models/': Permission denied
download_1   | mkdir: can't create directory '/data/models/': Permission denied
download_1   | mkdir: can't create directory '/data/models/': Permission denied
download_1   | mkdir: can't create directory '/data/models/': Permission denied
sd-webui_download_1 exited with code 1
```

**Which UI**

auto or auto-cpu or invoke or sygil?

**Hardware / Software**

- OS: [e.g. Windows 10 / Ubuntu 22.04]
- Fedora Silverblue
- OS version: 
- `Linux node-1w7jr9qutsmwm4wdwy1jtu8ef.ipv6.telus.net 6.4.15-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:25:01 UTC 2023 x86_64 GNU/Linux`
- WSL version (if applicable): 
- Docker Version: 
```yaml
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        %{shortcommit_cli}
 Built:             Sun Aug 27 16:48:05 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       %{shortcommit_moby}
  Built:            Sun Aug 27 16:48:05 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:
 runc:
  Version:          1.1.8
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```
- Docker compose version: 
```yaml
docker-compose version 1.29.2, build unknown
docker-py version: <module 'docker.version' from '/var/home/frityet/.local/lib/python3.11/site-packages/docker/version.py'>
CPython version: 3.11.5
OpenSSL version: OpenSSL 3.0.9 30 May 2023
```
- Repo version: 
master
- RAM:
- GPU/VRAM:

**Steps to Reproduce**

1. clone repo and do `docker-compose --profile download up --build`

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by Frityet** [comment]
@AbdBarho I apologize for ping, but I just cannot get this to work. Even if I use `podman-compose` it does not work

**Comment by AbdBarho** [comment]
try `docker compose` instead of `docker-compose`, also install buildkit like the error tells you, it is worth it.

**Comment by Frityet** [comment]
> try `docker compose` instead of `docker-compose`, also install buildkit like the error tells you, it is worth it.
> 
> 
> 
> `docker-compose` is v1 which is deprecated, you need v2

Will do, thank you

**Comment by mulles** [comment]
The problem is the relative path in docker-compose.yml:   
 ```
volumes:
      - &v1 ./data:/data   
      - &v2 ./output:/output
```

which would like something like this depending on where you git clone: 


 ```
volumes:
      - &v1 ./data:/var/home/-PUTYOURUSERNAMEHERE-/stable-diffusion-webui-docker/data
      - &v2 ./output:/var/home/-PUTYOURUSERNAMEHERE-/stable-diffusion-webui-docker/data/output
```

I might write a pull request to make this work for silverblue and other linux distro user out of the box, but could not figure out how to make relative path work under silverblue, seems to be docker/podman specific. 

See: https://stackoverflow.com/questions/46907558/docker-compose-relative-paths-vs-docker-volume 
For more information how docker compose files handle path.

**Comment by icsy7867** [comment]
I did not have an issue with the relative paths.... however for podman if you are on a selinux enabled system, you do need to add a :z flag which sets the proper selinux context for that folder:

```
volumes:
     - &v1 ./data:/data:z   
     - &v2 ./output:/output:z
```

Also I generally use docker-compose over podman compose if I need it with podman.  You should just be able to install the podman-docker package from dnf:
`dnf install podman-docker`

And this should make a /var/run/docker.sock that is symlinked from /var/run/podman/podman.sock (if running rootful).

And then I install docker-compose manually:
https://docs.docker.com/compose/install/linux/#install-the-plugin-manually
