### ISSUE TITLE
Checkpoints in mapped volume missing after rebuild

### ISSUE THREAD

**Issue by mkarikom** [AbdBarho/stable-diffusion-webui-docker#594]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**
This isn't addressed in the docs but I'm pretty sure I just did something wrong.

Can only see `v1-5-pruned-emaonly.ckpt` and `sd-v1-5-inpainting.ckpt` in the checkpoints chooser for both comfy and auto (haven't tried others).

**Which UI**

auto and comfy

**Hardware / Software**

- OS: [Ubuntu 22.04]
- OS version:  Ubuntu 22.04.2 LTS
- Docker Version: `Version:           24.0.4`
- Docker compose version: `Docker Compose version v2.19.1`
- Repo version: `* master 6a34739 [origin/master] Update Automatic1111 to v1.6.0 (#585)`
- RAM: 64gb
- GPU/VRAM: 12gb

**Steps to Reproduce**

1. sync local with current master branch
2. rebuild `docker compose --profile download up --build`
3. verify that `./data/StableDiffusion/` still contains like 15 different models I was using in 1.5
4. start a new container with auto or comfy e.g. `export WEBUI_PORT=7861 && docker compose --profile comfy up --build -d`
5. notice that only the first two models show up (see screenshot)
6. as a sanity check, make sure that the container actually sees the mounted host directory (e.g. didn't somehow mount some other directory and install a couple checkpoints in it):
```
me@host:~/Containers/stable-diffusion-webui-docker$ docker exec -it sd-webui-auto-1 /bin/bash
root@b27a01c315e8:/stable-diffusion-webui# ls -alvh /data/StableDiffusion
total 97G
drwxrwxrwx  2 1000 1000 4.0K Oct  1 03:19 .
drwxrwxrwx 23 1000 1000 4.0K Oct  1 03:30 ..
...
```

**Additional context**
<img width="383" alt="image" src="https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/335091/80928b83-cf4f-4869-8684-cf4dbf168a4d">

**Comment by AbdBarho** [comment]
I cannot reproduce the problem:

```sh
$ docker exec -it webui-docker-comfy-1 /bin/bash
root@d3acfe767587:/stable-diffusion# cd /data/models/Stable-diffusion/
root@d3acfe767587:/data/models/Stable-diffusion# ls
openjourney-v2.ckpt        sd_xl_base_1.0.safetensors     v1-5-pruned-emaonly.ckpt  
sd-v1-5-inpainting.ckpt    sd_xl_refiner_1.0.safetensors  v1-5-pruned-emaonly.sha256
sd-v1-5-inpainting.sha256  v1-4.ckpt                      v2
root@d3acfe767587:/data/models/Stable-diffusion# 
```

![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/24505302/4fbcd26c-8ca8-439c-936a-0574dc0a42e7)

Are you sure all the models are in the right folder?
