### ISSUE TITLE
Question: does this version also expose the REST api on port 5000?

### ISSUE THREAD

**Issue by StefH** [AbdBarho/stable-diffusion-webui-docker#61]
Does this version also expose the REST api on port 5000? (Just like the normal https://replicate.com/docs/reference/http ?)

**Comment by AbdBarho** [comment]
I am not sure since this depends on the underlying UI, you can add the port to the [docker compose file](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/c1fa2f145731633916a2ab3ade7bf8cad2d7ca71/docker-compose.yml#L5) and try it
```yml
    ports:
      - "7860:7860"
      - "5000:5000"
```

**Comment by StefH** [comment]
I think that the api is not running on port 5000.

When clicking the api-link in the bottom page, I get redirected to this:
![image](https://user-images.githubusercontent.com/249938/190859369-6cd3706d-9e04-4c38-aee5-949c69b73c5d.png)

**Comment by AbdBarho** [comment]
well, I guess the api is running on the same port as the ui

**Comment by rgriffogoes** [comment]
Which UI are you using @StefH ?  did you add something somewhere to enable api?

When I use auto1111, clicking in the api link shows a page informing me it is off, and I would like to have it on.

**Comment by StefH** [comment]
I cloned this project, followed the readme, and started:
```
docker compose --profile auto-cpu up --build
```

Then the UI is running at : http://localhost:7860/

**Comment by rgriffogoes** [comment]
Getting the UI to work is fine on my side, I'm curious about the API. Regardless if I run `auto-cpu` or `auto` clicking on the api-link at the bottom gives me:

![image](https://user-images.githubusercontent.com/1238919/192154149-423b525b-51d7-44fc-b0df-9f9bfdf40745.png)

With my superficial understanding of the code, I would need to either use a parameter (if auto1111 code is prepared for it) or change the code in auto1111 to start gradio with API server.

**Comment by AbdBarho** [comment]
maybe the discussion in #92 could be of some use
