### ISSUE TITLE
Memory leak in sd-auto:68

### ISSUE THREAD

**Issue by DevilaN** [AbdBarho/stable-diffusion-webui-docker#612]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Tried to run app and my RAM usage exploded slowly. I can generate few images 512x78 and each time after generated image is converted from latent space to pixel space RAM usage grows about 1.5GB+ until after few images generated it gets OOMKilled.
There was no such issue with sd-auto:67 image.

**Which UI**

auto

Anyone observing same problems?

**Comment by AbdBarho** [comment]
Oof, I think I know what's the problem
https://github.com/AbdBarho/stable-diffusion-webui-docker/commit/3e67f559d43b53faeb4a32b63c8b89391f0b7248#diff-d1f8091e5f8ecf6a059eb047c5fb0c6fc783a79be8770e595f0859e9950f7226L70-L71

**Comment by Snowflec** [comment]
> Oof, I think I know what's the problem 
Are there any temporary fixes that can be made or a way to rollback to a previous version until this is fixed?

**Comment by DevilaN** [comment]
Bump. I would like to see some advice on how to fix this problem here if @AbdBarho can point out what is the main cause of memory leak. Diff from commit tells me nothing. There are many changes there.

**Comment by NarinderS** [comment]
Temporary workaround is to add these two lines to `services/AUTOMATIC1111/Dockerfile`:

```
RUN apt-get -y install libgoogle-perftools-dev && apt-get clean
ENV LD_PRELOAD=libtcmalloc.so
```

I added them around line 29, after the apt-install steps.

**Comment by DevilaN** [comment]
@NarinderS you are my hero today :)
Instead of changing Dockerfile and rebuilding image I suggest to add in `./data/config/auto/startup.sh`:
```
# RAM LEAK FIX: https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/326#issuecomment-1435698896
# Stubborn pest came back: https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/612#issuecomment-1831120187
if [[ ! -L "/usr/lib/x86_64-linux-gnu/libtcmalloc.so" ]]; then
  apt-get update && apt-get -y install libgoogle-perftools-dev && apt-get clean
fi
export LD_PRELOAD=libtcmalloc.so
```

**Comment by AbdBarho** [comment]
Should be fixed now, sorry for being late, happy new year!
