### ISSUE TITLE
Nvidia container cli error

### ISSUE THREAD

**Issue by MBoutray** [AbdBarho/stable-diffusion-webui-docker#614]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I tried building the auto profile, then the invoke one and I got the same error everytime

that's the log in the console for the auto profile
2023/11/16 18:06:14 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 0.8s (24/24) FINISHED
 => [auto internal] load build definition from Dockerfile
 => => transferring dockerfile: 2.70kB
 => [auto internal] load .dockerignore
 => => transferring context: 2B
 => [auto internal] load metadata for docker.io/pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
 => [auto internal] load metadata for docker.io/alpine/git:2.36.2
 => [auto download 1/8] FROM docker.io/alpine/git:2.36.2@sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c713fa5e1c75dea84
 => [auto internal] load build context
 => => transferring context: 7.71kB
 => [auto stage-1  1/11] FROM docker.io/pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime@sha256:e4aaefef0c96318759160ff971b527ae61ee306a1204c5f6e907c4b45f05b8a3
 => CACHED [auto stage-1  2/11] RUN --mount=type=cache,target=/var/cache/apt   apt-get update &&   apt-get install -y fonts-dejavu-core rsync git jq moreutils aria2   ffmpeg libglfw3-dev libgle
 => CACHED [auto stage-1  3/11] RUN --mount=type=cache,target=/root/.cache/pip   git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git &&   cd stable-diffusion-webui &&   git re
 => CACHED [auto download 2/8] COPY clone.sh /clone.sh
 => CACHED [auto download 3/8] RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf   && rm -rf assets data
 => CACHED [auto download 4/8] RUN . /clone.sh CodeFormer https://github.com/sczhou/CodeFormer.git c5b4593074ba6214284d6acd5f1719b6c5d739af   && rm -rf assets inputs
 => CACHED [auto download 5/8] RUN . /clone.sh BLIP https://github.com/salesforce/BLIP.git 48211a1594f1321b00f14c9f7a5b4813144b2fb9
 => CACHED [auto download 6/8] RUN . /clone.sh k-diffusion https://github.com/crowsonkb/k-diffusion.git ab527a9a6d347f364e3d185ba6d714e22d80cb3c
 => CACHED [auto download 7/8] RUN . /clone.sh clip-interrogator https://github.com/pharmapsychotic/clip-interrogator 2cf03aaf6e704197fd0dae7c7f96aa59cf1b11c9
 => CACHED [auto download 8/8] RUN . /clone.sh generative-models https://github.com/Stability-AI/generative-models 45c443b316737a4ab6e40413d7794a7f5657c19f
 => CACHED [auto stage-1  4/11] COPY --from=download /repositories/ /stable-diffusion-webui/repositories/
 => CACHED [auto stage-1  5/11] RUN mkdir /stable-diffusion-webui/interrogate && cp /stable-diffusion-webui/repositories/clip-interrogator/clip_interrogator/data/* /stable-diffusion-webui/inter
 => CACHED [auto stage-1  6/11] RUN --mount=type=cache,target=/root/.cache/pip   pip install -r /stable-diffusion-webui/repositories/CodeFormer/requirements.txt
 => CACHED [auto stage-1  7/11] RUN --mount=type=cache,target=/root/.cache/pip   pip install pyngrok xformers   git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126
 => CACHED [auto stage-1  8/11] COPY . /docker
 => CACHED [auto stage-1  9/11] RUN   sed -i 's/in_app_dir = .*/in_app_dir = True/g' /opt/conda/lib/python3.10/site-packages/gradio/routes.py &&   git config --global --add safe.directory '*'  
 => CACHED [auto stage-1 10/11] WORKDIR /stable-diffusion-webui
 => [auto] exporting to image
 => => exporting layers
 => => writing image sha256:3e71347335efc4adabdc97cb0ebde59408b9bcbe72d9ee1c5fc8477b7b18df49
 => => naming to docker.io/library/sd-auto:68
[+] Running 1/0
 ✔ Container webui-docker-auto-1  Created
Attaching to webui-docker-auto-1
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container in
it: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: detection error: driver rpc error: failed to process request: unknown

and that's for the invoke profile
2023/11/16 18:06:48 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 1.0s (17/17) FINISHED
 => [invoke internal] load build definition from Dockerfile
 => => transferring dockerfile: 1.99kB
 => [invoke internal] load .dockerignore
 => => transferring context: 2B
 => [invoke internal] load metadata for docker.io/pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
 => [invoke internal] load metadata for docker.io/library/alpine:3.17
 => [invoke stage-1 1/8] FROM docker.io/pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime@sha256:82e0d379a5dedd6303c89eda57bcc434c40be11f249ddfadfd5673b84351e806
 => [invoke xformers 1/3] FROM docker.io/library/alpine:3.17@sha256:f71a5f071694a785e064f05fed657bf8277f1b2113a8ed70c90ad486d6ee54dc
 => [invoke internal] load build context
 => => transferring context: 3.12kB
 => CACHED [invoke stage-1 2/8] RUN --mount=type=cache,target=/var/cache/apt   apt-get update &&   apt-get install make g++ git libopencv-dev -y &&   apt-get clean &&   cd /usr/lib/x86_64-linux
 => CACHED [invoke stage-1 3/8] RUN git clone <https://github.com/invoke-ai/InvokeAI.git> /InvokeAI
 => CACHED [invoke stage-1 4/8] WORKDIR /InvokeAI
 => CACHED [invoke stage-1 5/8] RUN --mount=type=cache,target=/root/.cache/pip   git reset --hard f3b2e02921927d9317255b1c3811f47bd40a2bf9 &&   pip install -e .
 => CACHED [invoke stage-1 6/8] RUN --mount=type=cache,target=/root/.cache/pip   git fetch &&   git reset --hard &&   git checkout main &&   git reset --hard f3b2e02921927d9317255b1c3811f47bd40
 => CACHED [invoke xformers 2/3] RUN apk add --no-cache aria2
 => CACHED [invoke xformers 3/3] RUN aria2c -x 5 --dir / --out wheel.whl '<https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/download/6.0.0/xformers-0.0.21.dev544-cp310-cp310-ma
 => CACHED [invoke stage-1 7/8] RUN --mount=type=cache,target=/root/.cache/pip   --mount=type=bind,from=xformers,source=/wheel.whl,target=/xformers-0.0.21-cp310-cp310-linux_x86_64.whl   pip ins
 => CACHED [invoke stage-1 8/8] COPY . /docker/
 => [invoke] exporting to image
 => => exporting layers
 => => writing image sha256:ec3ebcd1bb230c3cf30679b6b5686c9889b85c660b9c89de98f9f845b8b363aa
 => => naming to docker.io/library/sd-invoke:30
[+] Running 1/
 ✔ Container webui-docker-invoke-1  Created
Attaching to webui-docker-invoke-1
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: detection error: driver rpc error: failed to process request: unknown

**Which UI**

auto and invoke

**Hardware / Software**

- OS: Windows 10
- OS version: Version 22H2 build 19045.3570 
- WSL version (if applicable): 2 
- Docker Version: 24.0.6
- Docker compose version: v2.23.0-desktop.1 
- Repo version: 3e67f55 
- RAM: idk
- GPU/VRAM: idk

**Steps to Reproduce**

execute commands `docker compose --profile auto up --build` or `docker compose --profile invoke up --build`

**Additional context**

**Comment by kropochev** [comment]
I have a similar problem:
docker compose --profile auto up --build
[+] Building 6.2s (26/26) FINISHED                                                                 docker:desktop-linux
 => [auto internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 2.70kB                                                                             0.0s
 => [auto internal] load .dockerignore                                                                             0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [auto internal] load metadata for docker.io/pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime                      5.9s
 => [auto internal] load metadata for docker.io/alpine/git:2.36.2                                                  5.8s
 => [auto auth] pytorch/pytorch:pull token for registry-1.docker.io                                                0.0s
 => [auto auth] alpine/git:pull token for registry-1.docker.io                                                     0.0s
 => [auto internal] load build context                                                                             0.0s
 => => transferring context: 122B                                                                                  0.0s
 => [auto stage-1  1/11] FROM docker.io/pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime@sha256:e4aaefef0c9631875916  0.0s
 => [auto download 1/8] FROM docker.io/alpine/git:2.36.2@sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c7  0.0s
 => CACHED [auto stage-1  2/11] RUN --mount=type=cache,target=/var/cache/apt   apt-get update &&   apt-get instal  0.0s
 => CACHED [auto stage-1  3/11] RUN --mount=type=cache,target=/root/.cache/pip   git clone https://github.com/AUT  0.0s
 => CACHED [auto download 2/8] COPY clone.sh /clone.sh                                                             0.0s
 => CACHED [auto download 3/8] RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stab  0.0s
 => CACHED [auto download 4/8] RUN . /clone.sh CodeFormer https://github.com/sczhou/CodeFormer.git c5b4593074ba62  0.0s
 => CACHED [auto download 5/8] RUN . /clone.sh BLIP https://github.com/salesforce/BLIP.git 48211a1594f1321b00f14c  0.0s
 => CACHED [auto download 6/8] RUN . /clone.sh k-diffusion https://github.com/crowsonkb/k-diffusion.git ab527a9a6  0.0s
 => CACHED [auto download 7/8] RUN . /clone.sh clip-interrogator https://github.com/pharmapsychotic/clip-interrog  0.0s
 => CACHED [auto download 8/8] RUN . /clone.sh generative-models https://github.com/Stability-AI/generative-model  0.0s
 => CACHED [auto stage-1  4/11] COPY --from=download /repositories/ /stable-diffusion-webui/repositories/          0.0s
 => CACHED [auto stage-1  5/11] RUN mkdir /stable-diffusion-webui/interrogate && cp /stable-diffusion-webui/repos  0.0s
 => CACHED [auto stage-1  6/11] RUN --mount=type=cache,target=/root/.cache/pip   pip install -r /stable-diffusion  0.0s
 => CACHED [auto stage-1  7/11] RUN --mount=type=cache,target=/root/.cache/pip   pip install pyngrok xformers   g  0.0s
 => CACHED [auto stage-1  8/11] COPY . /docker                                                                     0.0s
 => CACHED [auto stage-1  9/11] RUN   sed -i 's/in_app_dir = .*/in_app_dir = True/g' /opt/conda/lib/python3.10/si  0.0s
 => CACHED [auto stage-1 10/11] WORKDIR /stable-diffusion-webui                                                    0.0s
 => [auto] exporting to image                                                                                      0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:538d71b70724f204623d7c4061cdb14ca3749a73ddf9e14b9ffd3153b48ea970                       0.0s
 => => naming to docker.io/library/sd-auto:68                                                                      0.0s
Attaching to webui-docker-auto-1
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

**Which UI**
auto and invoke

**Hardware / Software**
- OS: Linux 6.5.0-13-generic Ubuntu 23.10
- Docker version 24.0.7, build afdd53b
- Docker Compose version v2.23.0-desktop.1
- Repo version: https://github.com/AbdBarho/stable-diffusion-webui-docker/commit/3e67f559d43b53faeb4a32b63c8b89391f0b7248
- RAM: 64Gb
- GPU/VRAM: GTX4080 24Gb

**Steps to Reproduce**
execute commands `docker compose --profile auto up --build` or `docker compose --profile invoke up --build`

**Comment by kropochev** [comment]
If commented deploy section
```
version: '3.9'

x-base_service: &base_service
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
    stop_signal: SIGKILL
    tty: true
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #            - driver: nvidia
  #              device_ids: ['0']
  #              capabilities: [compute, utility]
```
and execute `docker compose --profile auto-cpu up --build` then worked.

**Comment by AbdBarho** [comment]
it seems you were trying to run GPU version on a non-GPU machine, which is why you got the error.

The only thing you can use is `auto-cpu`, you don't need to change anything in the code.
