### ISSUE TITLE
Efficiency nodes import failed with ComfyUI

### ISSUE THREAD

**Issue by Stevoo01** [AbdBarho/stable-diffusion-webui-docker#624]
Has this issue been opened before?
I can't say, as I installed the UI for the first time. But there are Rddit posts that also deal with this error. However, the solutions did not work for me. 
https://www.reddit.com/r/comfyui/comments/17n7etb/efficiency_nodes_import_failed/
https://www.reddit.com/r/comfyui/comments/14vjuvi/custom_nodes_import_failed/

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

Describe the bug
I cannot install the efficiency node. The following error occurs when loading:
webui-docker-comfy-1  | Traceback (most recent call last):
webui-docker-comfy-1  |   File "/stable-diffusion/nodes.py", line 1698, in load_custom_node
webui-docker-comfy-1  |     module_spec.loader.exec_module(module)
webui-docker-comfy-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-comfy-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-comfy-1  |   File "/stable-diffusion/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
webui-docker-comfy-1  |     from  .efficiency_nodes import NODE_CLASS_MAPPINGS
webui-docker-comfy-1  |   File "/stable-diffusion/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
webui-docker-comfy-1  |     from .py import smZ_cfg_denoiser
webui-docker-comfy-1  |   File "/stable-diffusion/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
webui-docker-comfy-1  |     from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
webui-docker-comfy-1  | ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (/stable-diffusion/comfy/samplers.py)
webui-docker-comfy-1  |
webui-docker-comfy-1  | Cannot import /stable-diffusion/custom_nodes/efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (/stable-diffusion/comfy/samplers.py)
webui-docker-comfy-1  | ### Loading: ComfyUI-Manager (V1.6.4)
webui-docker-comfy-1  | ### ComfyUI Revision: 1376 [7e941f9f] | Released on '2023-08-30'
webui-docker-comfy-1  | ### Loading: ComfyUI-Impact-Pack (V4.38.2)
webui-docker-comfy-1  | ### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
webui-docker-comfy-1  | WAS Node Suite: OpenCV Python FFMPEG support is enabled
webui-docker-comfy-1  | WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/stable-diffusion/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
webui-docker-comfy-1  | WAS Node Suite: Finished. Loaded 197 nodes successfully.
webui-docker-comfy-1  |
webui-docker-comfy-1  |         "Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill
webui-docker-comfy-1  |
webui-docker-comfy-1  | ### Loading: ComfyUI-Manager (V1.6.4)
webui-docker-comfy-1  | ### ComfyUI Revision: 1376 [7e941f9f] | Released on '2023-08-30'
webui-docker-comfy-1  | Traceback (most recent call last):
webui-docker-comfy-1  |   File "/stable-diffusion/nodes.py", line 1698, in load_custom_node
webui-docker-comfy-1  |     module_spec.loader.exec_module(module)
webui-docker-comfy-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-comfy-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-comfy-1  |   File "/data/config/comfy/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
webui-docker-comfy-1  |     from  .efficiency_nodes import NODE_CLASS_MAPPINGS
webui-docker-comfy-1  |   File "/data/config/comfy/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
webui-docker-comfy-1  |     from .py import smZ_cfg_denoiser
webui-docker-comfy-1  |   File "/stable-diffusion/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
webui-docker-comfy-1  |     from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
webui-docker-comfy-1  | ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (/stable-diffusion/comfy/samplers.py)
webui-docker-comfy-1  |
webui-docker-comfy-1  | Cannot import /data/config/comfy/custom_nodes/efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (/stable-diffusion/comfy/samplers.py)
webui-docker-comfy-1  |
webui-docker-comfy-1  | Import times for custom nodes:
webui-docker-comfy-1  |    0.0 seconds: /stable-diffusion/custom_nodes/ComfyUI_UltimateSDUpscale
webui-docker-comfy-1  |    0.1 seconds (IMPORT FAILED): /stable-diffusion/custom_nodes/efficiency-nodes-comfyui
webui-docker-comfy-1  |    0.1 seconds: /stable-diffusion/custom_nodes/ComfyUI-Manager
webui-docker-comfy-1  |    0.1 seconds: /data/config/comfy/custom_nodes/ComfyUI-Manager
webui-docker-comfy-1  |    0.1 seconds (IMPORT FAILED): /data/config/comfy/custom_nodes/efficiency-nodes-comfyui
webui-docker-comfy-1  |    1.8 seconds: /stable-diffusion/custom_nodes/was-node-suite-comfyui
webui-docker-comfy-1  |    2.0 seconds: /stable-diffusion/custom_nodes/ComfyUI-Impact-Pack
webui-docker-comfy-1  |
webui-docker-comfy-1  | Starting server
webui-docker-comfy-1  |
webui-docker-comfy-1  | To see the GUI go to: http://0.0.0.0:7860

Which UI = comfy with gpu

**Hardware / Software**

- OS: Windows 10
- OS version: Build 19045-3693
- WSL version (if applicable): Version 2
- Docker Version: 4.25.2
- Docker compose version: v2.23.0-desktop.1
- Repo version: 
- RAM: 128 GB
- GPU/VRAM: Tesla p40 with 24GB

I don't know if the bug is correct here. I cannot evaluate whether it is because it is modul version 2 and this no longer harmonizes with the Docker build. 

So here is a request for help.
Thank you for your efforts.

**Comment by Stevoo01** [comment]
Additional comment:
I have tried to install an older version (1.95) from https://civitai.com/models/32342/efficiency-nodes-for-comfyui.

That works. But the error with the new version is still there.

**Comment by FyzzLive** [comment]
@Stevoo01 that version of Efficiency Nodes is no longer maintained, someone else has took on maintaining it :D
You can find it here:
https://github.com/jags111/efficiency-nodes-comfyui

**Comment by AbdBarho** [comment]
I updated the comfy version today #603, maybe the new version works?

**Comment by Bladed3d** [comment]
I installed this... "You can find it here:
https://github.com/jags111/efficiency-nodes-comfyui" but I still get errors when loading workflows that use the efficiency node.  I get an error - "Loading aborted due to error reloading workflow data... This may be due to the following script: /extensions/efficiency-nodes-comfyui/widgethider.js" I tried reinstalling the efficiency node, but still same error. Any suggestions?
