### ISSUE TITLE
Device cuda:0 does not support the torch.fft functions used in the FreeU node, switching to CPU

### ISSUE THREAD

**Issue by jamesmgg** [AbdBarho/stable-diffusion-webui-docker#625]
**Has this issue been opened before?**

- [X] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I'm running the freeU Node in ComfyUI and it's using the CPU when it should be using the GPU. I'm not sure how torch is misconfigured if every other torch function runs well on the GPU. I've only had this issue with these torch fft functions. 

**Which UI**

comfy UI

**Hardware / Software**

- OS: Windows 11
- OS version: 22H@ BUILD 22621.2715
- WSL version (if applicable): WSL version: 1.2.5.0
- Docker Version: 24.0.7
- Docker compose version: v2.23.3-desktop.2
- Repo version: 9b655d4fd72903d33af101177b0cb9576c5babd3
- RAM: 128GB
- GPU/VRAM: RTX 4090 / 24GB VRAM

**Steps to Reproduce**

1. Load a comfy UI workflow using a freeU node
2. Check logs
3. See warning: `Device cuda:0 does not support the torch.fft functions used in the FreeU node, switching to CPU` and slow behavior

**Comment by AbdBarho** [comment]
I did an update today to comfy #603, maybe this problem is now solved?
