### ISSUE TITLE
httpcore and httpx 0.24.1 needed to run latest version.

### ISSUE THREAD

**Issue by fortunefox** [AbdBarho/stable-diffusion-webui-docker#629]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Trying to run Automatic 1111 via docker compose up auto leads to an error ending in
`TypeError: __init__() got an unexpected keyword argument 'socket_options'`

**Which UI**

auto

**Hardware / Software**

- OS: Linux Mint, Kernel 6.6.7
- Docker Version: 24
- Docker compose version: 2.21
- Repo version: 3e67f55 (master)
- RAM: 32 GB
- GPU/VRAM: 8GB (2080 Super)

**Steps to Reproduce**

1. run docker compose up auto on a freshly built image

**Steps to fix**
Adding
```Dockerfile
RUN pip3 install httpcore
RUN pip3 install httpx==0.24.1
```
to the docker file for Automatic and rebuilding fixes the issue.

**Comment by Mic92** [comment]
For me I just had to do a `git pull` and re-run docker-compose. Maybe the issue got sorted in the meantime.

**Comment by AbdBarho** [comment]
I updated the base image for auto today, please try again from latest master if the problem persists.

**Comment by simonmcnair** [comment]
can confirm latest version contains following:
```root@a3d0a5556933:/stable-diffusion-webui# cat requirements_versions.txt
GitPython==3.1.32
Pillow==9.5.0
accelerate==0.21.0
basicsr==1.4.2
blendmodes==2022
clean-fid==0.1.35
einops==0.4.1
fastapi==0.94.0
gfpgan==1.3.8
gradio==3.41.2
httpcore==0.15
inflection==0.5.1
jsonmerge==1.8.0
kornia==0.6.7
lark==1.1.2
numpy==1.23.5
omegaconf==2.2.3
open-clip-torch==2.20.0
piexif==1.1.3
psutil==5.9.5
pytorch_lightning==1.9.4
realesrgan==0.3.0
resize-right==0.0.2
safetensors==0.3.1
scikit-image==0.21.0
timm==0.9.2
tomesd==0.1.3
torch
torchdiffeq==0.2.3
torchsde==0.2.6
transformers==4.30.2
httpx==0.24.1```
