### ISSUE TITLE
After starting the environment, it will stop running immediately.

### ISSUE THREAD

**Issue by Mr-wang68** [AbdBarho/stable-diffusion-webui-docker#637]
`docker compose --profile auto-cpu up --build`
After I execute this command, I cannot access http://localhost:7860/
the **auto-cpu-1** will stop immediately
Container logs show these errors

![7R(9MV7CZ1C ZP(M3%GY9AF](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/50506336/5697f0ef-bf04-4e82-9d28-4dd726925484)

**Comment by AbdBarho** [comment]
I have re-built my container from scratch and found no issues.

Can you try to re-build again with `docker compose build auto-cpu --no-cache` and then run again?
