### ISSUE TITLE
Error with auto and invoke: libnvidia-ml.so.1 (apparently missing)

### ISSUE THREAD

**Issue by abalegno** [AbdBarho/stable-diffusion-webui-docker#640]
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
```

So, this is strange i get the same error with auto or invoke, but I download the original repo from AUTOMATIC11111 and build with python and it's working, the drivers and de toolkit are good:

```
nvidia-smi

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        Off | 00000000:01:00.0  On |                  N/A |
|  0%   34C    P8               6W / 170W |      1MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

If I do a search: `sudo find / -name libnvidia-ml.so*`

```
/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
/usr/local/cuda-12.3/targets/x86_64-linux/lib/stubs/libnvidia-ml.so
```

So No idea at this point, the auto-CPU working good too.

**Hardware / Software**

- OS: [Ubuntu 22.04]
- OS version: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)
- WSL version (if applicable): Wsman Shell commandLine, version 0.2.1
- Docker Version: 24.0.7
- Docker compose version: v2.21.0
- Repo version: master
- RAM: 16GB
- GPU/VRAM: 12GB

**Steps to Reproduce**

docker compose --profile auto up --build

**Comment by schott12521** [comment]
I was only able to do this after the following, though I'm not sure what exactly fixed the issue:

- Reinstalled docker + docker compose latest versions
- Setup rootless docker
- Reinstalled and setup nvidia latest drivers (for Ubuntu Server 23.04), setup nvidia toolkit
- Updated LD_Library_Path in ~/.bashrc location
- Setup this project using sudo before all docker commands

It feels like a really sloppy install but it works 🤷

**Comment by AbdBarho** [comment]
Do you have `nvidia-container-toolkit` installed?

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
