### ISSUE TITLE
it cant start auto image and stuck at " removing nvidia-cudnn-cu11"

### ISSUE THREAD

**Issue by NicoNicoNico123** [AbdBarho/stable-diffusion-webui-docker#648]
When start a1111 images it's stuck on this code over 30mins

auto-1  | Requirement already satisfied: nvidia-cublas-cu11 in /opt/conda/lib/python3.10/site-packages (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (11.11.3.6)
auto-1  | Requirement already satisfied: nvidia-cuda-nvrtc-cu11 in /opt/conda/lib/python3.10/site-packages (from nvidia-cudnn-cu11->tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (runtime-cu11, tensorrt_libs, tensorrt
auto-1  | Successfully installed nvidia-cuda-runtime-cu11-11.8.89 tensorrt-9.0.1.post11.dev4 tensorrt_bindings-9.0.1.post11.dev4 tensorrt_libs-9.0.1.post11.dev4
auto-1  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
auto-1  | removing nvidia-cudnn-cu11

**Comment by bablat** [comment]
This is still occurring, I tried installing TensorRT and hit the same issue:

```
Installing extension dependencies (if any)
TensorRT is not installed! Installing...
Installing nvidia-cudnn-cu11
Installing tensorrt
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting tensorrt==9.0.1.post11.dev4
  Downloading https://pypi.nvidia.com/tensorrt/tensorrt-9.0.1.post11.dev4.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorrt_libs==9.0.1.post11.dev4 (from tensorrt==9.0.1.post11.dev4)
  Downloading https://pypi.nvidia.com/tensorrt-libs/tensorrt_libs-9.0.1.post11.dev4-py2.py3-none-manylinux_2_17_x86_64.whl (1060.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 GB 60.0 MB/s eta 0:00:00
Collecting tensorrt_bindings==9.0.1.post11.dev4 (from tensorrt==9.0.1.post11.dev4)
  Downloading https://pypi.nvidia.com/tensorrt-bindings/tensorrt_bindings-9.0.1.post11.dev4-cp310-none-manylinux_2_17_x86_64.whl (956 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 956.2/956.2 kB 193.1 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu11 (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4)
  Downloading nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 875.6/875.6 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: nvidia-cudnn-cu11 in /opt/conda/lib/python3.10/site-packages (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (8.9.4.25)
Requirement already satisfied: nvidia-cublas-cu11 in /opt/conda/lib/python3.10/site-packages (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (11.11.3.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11 in /opt/conda/lib/python3.10/site-packages (from nvidia-cudnn-cu11->tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (11.8.89)
Building wheels for collected packages: tensorrt
  Building wheel for tensorrt (setup.py) ... done
  Created wheel for tensorrt: filename=tensorrt-9.0.1.post11.dev4-py2.py3-none-any.whl size=17623 sha256=74c167e0bfd94c700d2ef86c55202f22c554a633d505f74d42aeb699b426bbee
  Stored in directory: /tmp/pip-ephem-wheel-cache-dsbc6ml_/wheels/d1/6d/71/f679d0d23a60523f9a05445e269bfd0bcd1c5272097fa931df
Successfully built tensorrt
Installing collected packages: tensorrt_bindings, nvidia-cuda-runtime-cu11, tensorrt_libs, tensorrt
Successfully installed nvidia-cuda-runtime-cu11-11.8.89 tensorrt-9.0.1.post11.dev4 tensorrt_bindings-9.0.1.post11.dev4 tensorrt_libs-9.0.1.post11.dev4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
removing nvidia-cudnn-cu11
```
The last line never returns, stuck forever, nothing in logs.

**Comment by timetheonce** [comment]
So any update about this issue? 

> This is still occurring, I tried installing TensorRT and hit the same issue:
> 
> ```
> Installing extension dependencies (if any)
> TensorRT is not installed! Installing...
> Installing nvidia-cudnn-cu11
> Installing tensorrt
> Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
> Collecting tensorrt==9.0.1.post11.dev4
>   Downloading https://pypi.nvidia.com/tensorrt/tensorrt-9.0.1.post11.dev4.tar.gz (18 kB)
>   Preparing metadata (setup.py) ... done
> Collecting tensorrt_libs==9.0.1.post11.dev4 (from tensorrt==9.0.1.post11.dev4)
>   Downloading https://pypi.nvidia.com/tensorrt-libs/tensorrt_libs-9.0.1.post11.dev4-py2.py3-none-manylinux_2_17_x86_64.whl (1060.6 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 GB 60.0 MB/s eta 0:00:00
> Collecting tensorrt_bindings==9.0.1.post11.dev4 (from tensorrt==9.0.1.post11.dev4)
>   Downloading https://pypi.nvidia.com/tensorrt-bindings/tensorrt_bindings-9.0.1.post11.dev4-cp310-none-manylinux_2_17_x86_64.whl (956 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 956.2/956.2 kB 193.1 MB/s eta 0:00:00
> Collecting nvidia-cuda-runtime-cu11 (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4)
>   Downloading nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 875.6/875.6 kB 1.4 MB/s eta 0:00:00
> Requirement already satisfied: nvidia-cudnn-cu11 in /opt/conda/lib/python3.10/site-packages (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (8.9.4.25)
> Requirement already satisfied: nvidia-cublas-cu11 in /opt/conda/lib/python3.10/site-packages (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (11.11.3.6)
> Requirement already satisfied: nvidia-cuda-nvrtc-cu11 in /opt/conda/lib/python3.10/site-packages (from nvidia-cudnn-cu11->tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (11.8.89)
> Building wheels for collected packages: tensorrt
>   Building wheel for tensorrt (setup.py) ... done
>   Created wheel for tensorrt: filename=tensorrt-9.0.1.post11.dev4-py2.py3-none-any.whl size=17623 sha256=74c167e0bfd94c700d2ef86c55202f22c554a633d505f74d42aeb699b426bbee
>   Stored in directory: /tmp/pip-ephem-wheel-cache-dsbc6ml_/wheels/d1/6d/71/f679d0d23a60523f9a05445e269bfd0bcd1c5272097fa931df
> Successfully built tensorrt
> Installing collected packages: tensorrt_bindings, nvidia-cuda-runtime-cu11, tensorrt_libs, tensorrt
> Successfully installed nvidia-cuda-runtime-cu11-11.8.89 tensorrt-9.0.1.post11.dev4 tensorrt_bindings-9.0.1.post11.dev4 tensorrt_libs-9.0.1.post11.dev4
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> removing nvidia-cudnn-cu11
> ```
> 
> The last line never returns, stuck forever, nothing in logs.

**Comment by NicoNicoNico123** [comment]
> So any update about this issue? The problem happens again for me, see attached below:
> 
> ![image](https://private-user-images.githubusercontent.com/49587703/324879043-2ef530e8-a037-4ac8-a173-030448c87c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDMxODMsIm5iZiI6MTcxNTMwMjg4MywicGF0aCI6Ii80OTU4NzcwMy8zMjQ4NzkwNDMtMmVmNTMwZTgtYTAzNy00YWM4LWExNzMtMDMwNDQ4Yzg3YzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAxMDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwN2IyMWQ1MWQ0YzlkNmRlZDI2NDFkNTE5YTJiNzk2MTk3NTFkNTI5OWI5NjA3MDFlNmJhZWUyMDBmMTYwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IAncBR9DjaRMTS5pW0jInmZvDk3ijUArlpgwTAMiZaQ)
> 
> > This is still occurring, I tried installing TensorRT and hit the same issue:
> > ```
> > Installing extension dependencies (if any)
> > TensorRT is not installed! Installing...
> > Installing nvidia-cudnn-cu11
> > Installing tensorrt
> > Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
> > Collecting tensorrt==9.0.1.post11.dev4
> >   Downloading https://pypi.nvidia.com/tensorrt/tensorrt-9.0.1.post11.dev4.tar.gz (18 kB)
> >   Preparing metadata (setup.py) ... done
> > Collecting tensorrt_libs==9.0.1.post11.dev4 (from tensorrt==9.0.1.post11.dev4)
> >   Downloading https://pypi.nvidia.com/tensorrt-libs/tensorrt_libs-9.0.1.post11.dev4-py2.py3-none-manylinux_2_17_x86_64.whl (1060.6 MB)
> >      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 GB 60.0 MB/s eta 0:00:00
> > Collecting tensorrt_bindings==9.0.1.post11.dev4 (from tensorrt==9.0.1.post11.dev4)
> >   Downloading https://pypi.nvidia.com/tensorrt-bindings/tensorrt_bindings-9.0.1.post11.dev4-cp310-none-manylinux_2_17_x86_64.whl (956 kB)
> >      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 956.2/956.2 kB 193.1 MB/s eta 0:00:00
> > Collecting nvidia-cuda-runtime-cu11 (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4)
> >   Downloading nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)
> >      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 875.6/875.6 kB 1.4 MB/s eta 0:00:00
> > Requirement already satisfied: nvidia-cudnn-cu11 in /opt/conda/lib/python3.10/site-packages (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (8.9.4.25)
> > Requirement already satisfied: nvidia-cublas-cu11 in /opt/conda/lib/python3.10/site-packages (from tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (11.11.3.6)
> > Requirement already satisfied: nvidia-cuda-nvrtc-cu11 in /opt/conda/lib/python3.10/site-packages (from nvidia-cudnn-cu11->tensorrt_libs==9.0.1.post11.dev4->tensorrt==9.0.1.post11.dev4) (11.8.89)
> > Building wheels for collected packages: tensorrt
> >   Building wheel for tensorrt (setup.py) ... done
> >   Created wheel for tensorrt: filename=tensorrt-9.0.1.post11.dev4-py2.py3-none-any.whl size=17623 sha256=74c167e0bfd94c700d2ef86c55202f22c554a633d505f74d42aeb699b426bbee
> >   Stored in directory: /tmp/pip-ephem-wheel-cache-dsbc6ml_/wheels/d1/6d/71/f679d0d23a60523f9a05445e269bfd0bcd1c5272097fa931df
> > Successfully built tensorrt
> > Installing collected packages: tensorrt_bindings, nvidia-cuda-runtime-cu11, tensorrt_libs, tensorrt
> > Successfully installed nvidia-cuda-runtime-cu11-11.8.89 tensorrt-9.0.1.post11.dev4 tensorrt_bindings-9.0.1.post11.dev4 tensorrt_libs-9.0.1.post11.dev4
> > WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> > removing nvidia-cudnn-cu11
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The last line never returns, stuck forever, nothing in logs.

Me too, any fix?
