### ISSUE TITLE
Windows 10: pytorch error on build

### ISSUE THREAD

**Issue by Euph1** [AbdBarho/stable-diffusion-webui-docker#649]
**Has this issue been opened before?**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

When building the auto container, the following error occurs:

OSError: /opt/conda/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

[docker build error.txt](https://github.com/AbdBarho/stable-diffusion-webui-docker/files/14117017/docker.build.error.txt)

**Which UI**

auto or auto-cpu or invoke or comfy?

auto

**Hardware / Software**

- OS: Windows 10
- OS version: 22H2 OS Build 19045.3930
- WSL version: WSL version: 2.0.9.0
- Docker Version: 24.0.7
- Docker compose version: Docker Compose version v2.23.3-desktop.2
- Repo version: 8.2.0
- RAM: 64GB
- GPU/VRAM: NVIDIA GTX 1080 / 8GB

**Steps to Reproduce**

1. Clone Repo
2. Navigate to Dir
3. docker compose --profile download up --build
4. docker compose --profile auto up --build

**Additional context**
Attached in "Describe the Bug" is the entirety of the output from running the build command

**Comment by KenwoodFox** [comment]
Im having almost the exact same issue but, on arch linux, and mine says
```
auto-1  | OSError: /opt/conda/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE
```

**Comment by SteveyBoros** [comment]
Exact same issue, which is odd because it worked 2 days ago. I rebuilt the docker image today and it's now failing as above.

**Comment by yokaimeow** [comment]
Exact same issue

**Comment by Euph1** [comment]
My quick and stupid solution was to just edit the dockerfile and use the latest pytorch image.

in ~stable-diffusion-webui-docker\services\AUTOMATIC1111\Dockerfile:

 changed line 18:

"FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime" 

to 

"FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime"

**Comment by SteveyBoros** [comment]
Sound like a solid solution to me, can't believe I missed this. I knew this was an issue with pytorch as they release 2.2 only yesterday I believe. I had though the package versions were locked though to prevent his. Cheers @Euph1

**Comment by xiaoxinmiao** [comment]
@Euph1 Thank you very much for your solution, it has started normally.

**Comment by AbdBarho** [comment]
Thanks @Euph1.

Turns out that the latest version of `xformers` was forcing the download of `pytoch-2.2.0` which is not what the container was intended to support.

For now I have pinned the xformers version and would probably bump the container version soon.
