### ISSUE TITLE
Undefined Symbol Error

### ISSUE THREAD

**Issue by mateus2k2** [AbdBarho/stable-diffusion-webui-docker#656]
**Describe the bug**

Undefined Symbol Error when running the GUI

**Which UI**
auto

**Hardware / Software**

- OS: Windows 11
- OS version: Windows 11 pro
- WSL version: WSL2. Ubuntu-22.04
- Docker Version: 25.0.2
- Docker compose version: v2.24.3-desktop.1
- Repo version: from master
- RAM: 16GB
- GPU/VRAM: 8GB

**Steps to Reproduce**

1. Run "docker compose --profile download up --build"
2. Run "docker compose --profile auto up --build"

![image](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/24702324/3fb13915-3d24-4a27-934b-6cff53635173)

**Comment by AbdBarho** [comment]
What GPU are you using? if you are running in WSL, did you install nvidia container toolkit?
