### ISSUE TITLE
can not download stablediffusion.git

### ISSUE THREAD

**Issue by fazz-old-programer** [AbdBarho/stable-diffusion-webui-docker#657]
docker compose --profile auto up --build

[+] Building 0.0s (0/0)  docker:default
[+] Building 62.1s (9/24)                                                                                                                                 docker:default
 => [auto internal] load build definition from Dockerfile                                                                                                           0.0s
 => => transferring dockerfile: 2.94kB                                                                                                                              0.0s
 => [auto internal] load metadata for docker.io/pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime                                                                       3.4s
 => [auto internal] load metadata for docker.io/alpine/git:2.36.2                                                                                                   2.7s
 => [auto internal] load .dockerignore                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                     0.0s
 => [auto download 1/8] FROM docker.io/alpine/git:2.36.2@sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c713fa5e1c75dea84                                    0.0s
 => [auto internal] load build context                                                                                                                              0.0s
 => => transferring context: 122B                                                                                                                                   0.0s
 => CANCELED [auto stage-1  1/12] FROM docker.io/pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime@sha256:3387e598cb94fc248d82e712a65b10931a990cea3a2e76362ca30d135f5  58.7s
 => => resolve docker.io/pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime@sha256:3387e598cb94fc248d82e712a65b10931a990cea3a2e76362ca30d135f565de4                      0.0s
 => => sha256:3387e598cb94fc248d82e712a65b10931a990cea3a2e76362ca30d135f565de4 1.37kB / 1.37kB                                                                      0.0s
 => => sha256:96d3e8fcea30561fe213e97aa46543d0daf78d2c59f981ba972964fd9db2539a 4.40kB / 4.40kB                                                                      0.0s
 => => sha256:30ecab32a3b65c6ec04c63a65b90e627b49d1297d8793896ed50b656377d8a06 28.58MB / 28.58MB                                                                   23.8s
 => => sha256:36bd8c5480de13567d1a20742a03183621f79ece3e60791a9b5f0421aea997cc 15.14MB / 15.14MB                                                                    8.6s
 => => sha256:4fc93add8a06dc2e19f91ff5dba9b8e20609c6da30abc2ebf6dbd17d61edbb33 121.63MB / 3.44GB                                                                   58.7s
 => => sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B                                                                            8.9s
 => => sha256:613276d556e20f60e60286ee3af7c545857b4d827c7576beb937e87604db6c04 99B / 99B                                                                            9.1s
 => => extracting sha256:30ecab32a3b65c6ec04c63a65b90e627b49d1297d8793896ed50b656377d8a06                                                                           0.8s
 => => extracting sha256:36bd8c5480de13567d1a20742a03183621f79ece3e60791a9b5f0421aea997cc                                                                           0.5s
 => CACHED [auto download 2/8] COPY clone.sh /clone.sh                                                                                                              0.0s
 => ERROR [auto download 3/8] RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git cf1d67a6fd5ea1aa600c4df58e5b47da4  58.6s
------
 > [auto download 3/8] RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf   && rm -rf assets data/**/*.png data/**/*.jpg data/**/*.gif:
0.294 + mkdir -p /repositories/stable-diffusion-stability-ai
0.294 + cd /repositories/stable-diffusion-stability-ai
0.294 + git init
0.295 hint: Using 'master' as the name for the initial branch. This default branch name
0.295 hint: is subject to change. To configure the initial branch name to use in all
0.295 hint: of your new repositories, which will suppress this warning, call:
0.295 hint:
0.295 hint:     git config --global init.defaultBranch <name>
0.295 hint:
0.295 hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
0.295 hint: 'development'. The just-created branch can be renamed via this command:
0.295 hint:
0.295 hint:     git branch -m <name>
0.296 Initialized empty Git repository in /repositories/stable-diffusion-stability-ai/.git/
0.296 + git remote add origin https://github.com/Stability-AI/stablediffusion.git
0.298 + git fetch origin cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf '--depth=1'
58.61 error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
58.61 error: 1915 bytes of body are still expected
58.61 fetch-pack: unexpected disconnect while reading sideband packet
58.61 fatal: early EOF
58.61 fatal: fetch-pack: invalid index-pack output
------
failed to solve: process "/bin/sh -c . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf   && rm -rf assets data/**/*.png data/**/*.jpg data/**/*.gif" did not complete successfully: exit code: 128

**Comment by dustinjoe** [comment]
same error encountered

**Comment by xiaoxixiao** [comment]
我设法解决了这个问题，请将版本库中 /services/AUTOMATIC1111/Dockerfile 文件中的第一个 FROM 基础镜像切换为最新版本或 2.43.0，也就是将第一行改为 FROM alpine/git:2.43.0

I managed to fix the problem, please switch the first FROM base image in the /services/AUTOMATIC1111/Dockerfile file in the repository to the latest version or 2.43.0, i.e. change the first line to FROM alpine/git:2.43.0

**Comment by dustinjoe** [comment]
> 我设法解决了这个问题，请将版本库中 /services/AUTOMATIC1111/Dockerfile 文件中的第一个 FROM 基础镜像切换为最新版本或 2.43.0，也就是将第一行改为 FROM alpine/git:2.43.0
> 
> I managed to fix the problem, please switch the first FROM base image in the /services/AUTOMATIC1111/Dockerfile file in the repository to the latest version or 2.43.0, i.e. change the first line to FROM alpine/git:2.43.0

working now thanks!

**Comment by Brensom** [comment]
> 我设法解决了这个问题，请将版本库中 /services/AUTOMATIC1111/Dockerfile 文件中的第一个 FROM 基础镜像切换为最新版本或 2.43.0，也就是将第一行改为 FROM alpine/git:2.43.0
> 
> I managed to fix the problem, please switch the first FROM base image in the /services/AUTOMATIC1111/Dockerfile file in the repository to the latest version or 2.43.0, i.e. change the first line to FROM alpine/git:2.43.0

Not work for me

**Comment by fazz-old-programer** [comment]
Unfortunately, the same error occurred again in my environment.

**Comment by GIKAS123** [comment]
Same error here even after the fix

**Comment by fazz-old-programer** [comment]
Thank you for your help.
However, the first line of the dockerfile is already the string you suggested.

**Comment by Brensom** [comment]
what needs to be done to make it work?

**Comment by fazz-old-programer** [comment]
OK, I found the solution.
I was able to resolve the issue with the following steps:

1. Delete everything. Delete all the files obtained by git clone along with the directory, and delete the container and image from Docker Disktop.

2. Run git clone.

3. Modify the first line of /services/AUTOMATIC1111/Dockerfile as follows.
FROM alpine/git:2.43.0 as download

4.Run docker compose --profile download up --build

5.Run docker compose --profile auto up --build

**Comment by Brensom** [comment]
> OK, I found the solution. I was able to resolve the issue with the following steps:
> 
>     1. Delete everything. Delete all the files obtained by git clone along with the directory, and delete the container and image from Docker Disktop.
> 
>     2. Run git clone.
> 
>     3. Modify the first line of /services/AUTOMATIC1111/Dockerfile as follows.
>        FROM alpine/git:2.43.0 as download
> 
> 
> 4.Run docker compose --profile download up --build
> 
> 5.Run docker compose --profile auto up --build

I do everything exactly like this, but I still get this error:

```
1.265 + git remote add origin https://github.com/Stability-AI/stablediffusion.git
1.266 + git fetch origin cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf '--depth=1'
65.63 error: 4128 bytes of body are still expected
65.63 fetch-pack: unexpected disconnect while reading sideband packet
65.63 fatal: early EOF
65.63 fatal: fetch-pack: invalid index-pack output

```

**Comment by Brensom** [comment]
Very strange. But after rebooting my PC, this error completely disappeared.

**Comment by AbdBarho** [comment]
I was not able to re-produce the problem. This might be related to network error, are any of you using a proxy? or maybe in some region where there are some restrictions?

**Comment by Shoshele** [comment]
Couldn't get any of these to work, so I just went to bed and let the computer brute force it overnight with until sudo docker compose --profile auto up --build; do; done

**Comment by merelendor** [comment]
I had same problem on WSL, tried all above solutions, without success. I tried rise `git config http.postBuffer` up to 8GB, with the same result. On retries i noticed that all failures happened with one task, which download in parallel, about 3.44GB, so i put `sleep 180s` (for have twice as needed time to complete task on my gigabit channel, if you have slow connection increase this timeout) into `/services/AUTOMATIC1111/clone.sh` just after `git init`, and all installed good. The drawback of this is that all clone operations will be with that timeout.

So: 
add `sleep 180s` into `/services/AUTOMATIC1111/clone.sh`

**Comment by mrAnomalyy** [comment]
It shouldn't be closed, problem is still there. Messing with it on WSL inside Win11.

**Comment by moda20** [comment]
This is still an issue, i downloaded 300GB of PyTorch and still didn't get this build command to finish.
could we instead of closing the project just download it as a zip ?

**Comment by DevilaN** [comment]
Why the heck you need to download 300GB on any stage? This seems ultra wrong.

@AbdBarho, I know that you've got a lot of other things to do and you didn't want to publish ready to use image of Auto because of licensing issues, but please consider preparing base image with all dependencies and requirements installed, ready just to copy SD repo code locally as a part of build process. This would make it far more easier for many people to start with regarding all those "cannot download from X site or Y site because of unknown China firewall issues."

**Comment by moda20** [comment]
@DevilaN i had to redownload pytorch eachtime since the clone error appeared before that was finished and cached. 

i was able to finally make it work, by combining multiple clones into one RUN command. the issue is clearly parralelization of git clones when using RUN, so putting them in sequence solved the issue.

**Comment by brqd** [comment]
After adding `cd ../..` at the end of services/AUTOMATIC1111/clone.sh it works for me.

```
#!/bin/bash

set -Eeuox pipefail

git config --global core.compression 0

mkdir -p /repositories/"$1"
cd /repositories/"$1"
git init
git remote add origin "$2"
git fetch origin "$3" --depth=1
git reset --hard "$3"
rm -rf .git
cd ../..
```

**Comment by topherbuckley** [comment]
I got it working after manually pulling the pytorch image prior to trying to build. i.e. `docker pull pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime`, then rerunning `docker compose --profile auto up --build`. Might have something to do with memory/cache allocation limits between docker and git...not sure.  I was just sick of waiting for the pytorch image to download every time I tried to debug this.

**Comment by OisinHick** [comment]
this seems to be occuring with the auto CPU option also?

**Comment by Ingener74** [comment]
Adding sleep 1000s to the end of the file clone.sh worked for me. In general, you need to play with this sleep so that the file shown in the screenshot can download.

![Image](https://github.com/user-attachments/assets/a4b6dc9a-7907-4608-a9a1-966e2fa581ca)
