### ISSUE TITLE
Turn off automatic download

### ISSUE THREAD

**Issue by TheCarpetMerchant** [AbdBarho/stable-diffusion-webui-docker#659]
When running `docker compose --profile auto up`, the script automatically starts downloading Stable Diffusion 1.5.
I don't want it to do that, I already have the models I want to use. How can I turn off this automatic download ?

**Comment by Brensom** [comment]
Yes, here we need a 1.5 vs sdxl switch

**Comment by AbdBarho** [comment]
I think this is the default for auto, if there is an option to turn it off there, then you can probably change the run args to not download the model.

**Comment by simonmcnair** [comment]
I found if you remove sd 1.5 using --no-download-sd-model then it won't find the weights and it falls over.
