### ISSUE TITLE
'docker' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by WaifuPlapper** [AbdBarho/stable-diffusion-webui-docker#665]
**Has this issue been opened before?**

- [Y] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [Y] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I open the terminal in the stable-diffusion-webui-docker-master folder.
I paste docker compose --profile download up --build in the terminal.
The terminal tells me this:
```
docker : The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ docker compose --profile download up --build
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Hardware / Software**

- OS: Windows 11
- OS version: 23H2 OS Build 22631.3155
- Docker Version: I don't know I can't install it
- Docker compose version: I don't know I can't install it
- Repo version: from master I guess?
- RAM: 16
- GPU/VRAM: 12

**Steps to Reproduce**

1. Open the terminal in the stable-diffusion-webui-docker-master folder.
2. Paste docker compose --profile download up --build in the terminal.
3. See error (on my PC).

**Additional context**
I downloaded and extracted the zip because I don't know how to clone a repo and I don't know what a git is.

![WindowsTerminal_mTlTURFylu](https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/161373934/44746809-2ef7-4646-95da-eb1b9881f8c9)

**Comment by schott12521** [comment]
Did you follow the [setup guide](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Setup#make-sure-you-have-the-latest-version-of-docker-and-docker-compose-installed)? Most importantly, you don't have docker installed, and your WSL is telling you that when you try to paste the command.

> Docker Version: I don't know I can't install it
Docker compose version: I don't know I can't install it

Wdym you can't install it? Did you try Docker's [install guide](https://docs.docker.com/desktop/install/windows-install/)?

> I downloaded and extracted the zip because I don't know how to clone a repo and I don't know what a git is.

Its fine if you want to do this, (git)[https://en.wikipedia.org/wiki/Git] is one of the most ubiquitous tools in Software Engineering, I'd highly suggest becoming familiar with it if you're interested in understanding what is going on.

**Comment by WaifuPlapper** [comment]
Thanks for your help, it works perfectly now!

I'll try to get into git.

**Comment by AbdBarho** [comment]
@schott12521 thanks for your support on this!
