### ISSUE TITLE
ComfyUI Out of Date

### ISSUE THREAD

**Issue by dhelgerson** [AbdBarho/stable-diffusion-webui-docker#676]
**Has this issue been opened before?**

- [ X] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ X] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Whenever I install the docker container and use the comfy preset, and install comfyui-manager. it complains about bing out of date and things don't work right

**Which UI**

comfy

**Hardware / Software**

- OS: [debian]
- OS version: bullseye
- Docker Version: 25.0.4
- Docker compose version: 2.24.7
- Repo version: 015c2ec829c28d08ed122ad02b3fda84d9608dca
- RAM: 16GB ddr3
- GPU/VRAM: GTX 1070 SC

**Steps to Reproduce**

1. install necessary runtimes
2. clone repo
3. docker compose --profile download up --build
4. docker compose --profile comfy up --build
5. git clone comfyui-manager into custom_nodes
6. restart comfyui
7. click manager

**Comment by yelban** [comment]
Comment out this, it should be applicable to the current version, just not sure if there will be other issues?

**./services/comfy/Dockerfile**
```
ENV ROOT=/stable-diffusion
RUN --mount=type=cache,target=/root/.cache/pip \
  git clone https://github.com/comfyanonymous/ComfyUI.git ${ROOT} && \
  cd ${ROOT} && \
  git checkout master && \
  # git reset --hard d1f3637a5a944d0607b899babd8ff11d87100503 && \
  pip install -r requirements.txt
```

**Comment by dhelgerson** [comment]
that works. also doesn't seem to have any issues. would it be possible to get the change int he gh or at least updating the commit it looks for?

**Comment by timetheonce** [comment]
> that works. also doesn't seem to have any issues. would it be possible to get the change int he gh or at least updating the commit it looks for?

Hello, happy to see you solved the problem. However on my site even commented that line and rebuild the container, problem remains. Could you share your step-by-step operation?
