### ISSUE TITLE
Updating auto1111

### ISSUE THREAD

**Issue by simonmcnair** [AbdBarho/stable-diffusion-webui-docker#683]
If you want a more up to date version of A1111 here are the steps:

docker exec -it webui-docker-auto-1 /bin/bash
git pull
pip install -r requirements.txt
#if needed
cd repositories
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git
exit

docker stop webui-docker-auto-1
docker start webui-docker-auto-1

If it fails for any reason just rebuild the container using the standard process of docker compose --profile auto up --build

It might be an idea to add an update a1111 script so that auto1111 can be updated independent of the releases

**Comment by harpy2** [comment]
thx
