### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._custom_ops'

### ISSUE THREAD

**Issue by bluenevus** [AbdBarho/stable-diffusion-webui-docker#704]
**Has this issue been opened before?**

no

**Describe the bug**

ModuleNotFoundError: No module named 'torch._custom_ops'

**Which UI**

infoke

**Hardware / Software**

Latest docker

**Steps to Reproduce**

It built just fine when I used auto but when tried invoke I get this error.  I did remove and do a new pull with fresh images to make sure it wasn't using anything cached

**Additional context**
<img width="582" alt="image" src="https://github.com/AbdBarho/stable-diffusion-webui-docker/assets/3675043/a464662b-bb91-4bbc-87d4-564c33cbbf6e">

**Comment by halida** [comment]
Same issue.
Ubuntu 22.04, nvidia 4060ti, Driver Version: 545.29.06    CUDA Version: 12.3
Run:
docker compose --profile invoke up

**Comment by iorlas** [comment]
Same here

**Comment by AbdBarho** [comment]
Hey, sorry, invoke is not being actively maintained anymore by my side, I am sorry for this confusion, I will take time today to clean this up.
