### ISSUE TITLE
SD upscale limited to 1024x1024?

### ISSUE THREAD

**Issue by JoeMojoJones** [AbdBarho/stable-diffusion-webui-docker#71]
Hello, firstly thank you for this great webui.

I've been playing about using auto-cpu on an Epyc CPU.

I had reached memory limitations (32gb) when trying to upscale images past 896x896 and found the improvements form Doggettx (https://github.com/basujindal/stable-diffusion/pull/117) and applied this.

The improvements now let me scale images at higher resolutions but when using img2img and the "SD upscale" option anything over 1024x1024 gets ignored (although upon completion it reports the resolution chosen).

Using "Redraw whole image" is fine at higher image sizes until I run out of memory again.

Is there a limit set somewhere or am I using the wrong options somewhere?

**Comment by AbdBarho** [comment]
This repo only contains the docker images, the actual implementation and features of the auto UI is in https://github.com/AUTOMATIC1111/stable-diffusion-webui Please open this issue there.
