### ISSUE TITLE
lstein tokenizer error

### ISSUE THREAD

**Issue by tehgringe** [AbdBarho/stable-diffusion-webui-docker#72]
**Has this issue been opened before? Check the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Main), the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=is%3Aissue)**

https://github.com/lstein/stable-diffusion/issues/34
Running into this error, how would this be resolved in your setup?

**Describe the bug**

**Which UI**

hlky or auto or auto-cpu or lstein?

**Steps to Reproduce**

**Hardware / Software:**
 - OS: [e.g. Windows / Ubuntu and version]
 - RAM:
 - GPU: [Nvidia 1660 / No GPU]
 - VRAM:
 - Docker Version, Docker compose version
 - Release version [e.g. 1.0.1]

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by AbdBarho** [comment]
@tehgringe how to reproduce

**Comment by lamafab** [comment]
See https://github.com/AbdBarho/stable-diffusion-webui-docker/pull/79#issuecomment-1250381890

**Comment by AbdBarho** [comment]
@lamafab my bad, I forget to document this feature!
