### ISSUE TITLE
NSFW Filter

### ISSUE THREAD

**Issue by OmicronXNor** [AbdBarho/stable-diffusion-webui-docker#8]
It's unclear to me whether or not this build has the NSFW filter option activated or not. Regardless of the default, it would be good if this could be toggled within the webUI so that users can decide whether or not they would like to generate those sorts of images. Is that an easy thing to do?

**Comment by AbdBarho** [comment]
TLDR: No NSFW filter, not yet at least.

This repo provides the [WebUI](https://github.com/hlky/stable-diffusion-webui) as a docker container, and does not add any features. So, the NSFW filter should be implemented there.

Looking through the discussions [here](https://github.com/hlky/stable-diffusion-webui/discussions/218) and [here](https://github.com/hlky/stable-diffusion-webui/issues/160), it seems that this is not implemented. Feel free to contribute to the linked discussions, and if this feature gets added in the WebUI, I will gladly update!
