### ISSUE TITLE
Docker fails to start  with a no such file or directory

### ISSUE THREAD

**Issue by hughk** [AbdBarho/stable-diffusion-webui-docker#80]
This was working with the version pulled on Friday and stopped working this morning

Building the container works. Starting the container fails (again) with the following message:

docker compose --profile download up
[+] Running 1/0
 ⠿ Container webui-docker-automatic1111-1  Created                                                                                  0.0s
Attaching to webui-docker-automatic1111-1, webui-docker-download-1, webui-docker-hlky-1
webui-docker-download-1       | Downloading...
webui-docker-download-1       | - GFPGANv1.3.pth exists
webui-docker-download-1       | - RealESRGAN_x4plus.pth exists
webui-docker-download-1       | - LDSR.ckpt exists
webui-docker-download-1       | - LDSR.yaml exists
webui-docker-download-1       | - RealESRGAN_x4plus_anime_6B.pth exists
webui-docker-download-1       | - model.ckpt exists
webui-docker-download-1       | Checking SHAs...
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/0c85a38b66f627aacc67ce658a895bc6a612c6eba2cb018c2750e2a2332febb0" to rootfs at "/stable-diffusion-webui/config.json": mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/0c85a38b66f627aacc67ce658a895bc6a612c6eba2cb018c2750e2a2332febb0:/stable-diffusion-webui/config.json (via /proc/self/fd/14), flags: 0x5000: no such file or directory: unknown

Steps to Reproduce

docker compose --profile download up
[error...]

Hardware / Software:

OS: Windows 11/WSL2
Docker version
GPU: [Nvidia 3090]
Docker version: v20.10.17

**Comment by AbdBarho** [comment]
`docker compose --profile download up --build`
and this will only download the data, for whatever reason, it is starting the automatic1111 ui in your case. you should try `docker compose down` beforehand.

if you want to start the UI
`docker compose --profile auto up --build`

**Comment by hughk** [comment]
Yes, I had done that. It appears that it might have been a docker issue. I have restarted and it is working.
