### ISSUE TITLE
[Request] Add --allow-code to auto's ui Dockerfile

### ISSUE THREAD

**Issue by dathide** [AbdBarho/stable-diffusion-webui-docker#85]
Thanks for this great use of docker! The --allow-code flag allows custom code to be run in auto's ui, and I don't see a reason why it shouldn't be enabled by default. I just changed the last line of the Dockerfile from
`python3 -u ../../webui.py --listen --port 7860 --hide-ui-dir-config --ckpt-dir /cache/custom-models --ckpt /cache/models/model.ckpt ${CLI_ARGS}`
to
`python3 -u ../../webui.py --allow-code --listen --port 7860 --hide-ui-dir-config --ckpt-dir /cache/custom-models --ckpt /cache/models/model.ckpt ${CLI_ARGS}`
and the feature becomes enabled.

**Comment by AbdBarho** [comment]
@dathide you don't have to change the dockerfile for that, you can directly change the [docker compose cli args variable](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/docker-compose.yml#L42) which is created specifically for this purpose.

**Comment by dathide** [comment]
Thanks, I didn't know that. Yeah, I probably should have said default behavior. I'm of course fine with the testing, that makes sense.

**Comment by AbdBarho** [comment]
It is added now
