### ISSUE TITLE
Unnecessary redownload of model_base_caption_capfilt_large.pth

### ISSUE THREAD

**Issue by DevilaN** [AbdBarho/stable-diffusion-webui-docker#88]
**Has this issue been opened before? Check the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Main), the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=is%3Aissue)**

**Describe the bug**
Each time new version of auto service has been build old files from cache/torch/hub/checkpoints are being ignored and running img2img interrogate option ends up with redownloading files.

**Which UI**
I play only with auto, so I can confirm it for auto.

**Steps to Reproduce**
1. Go to img2img
2. Upload image and click Interrogate
3. Wait for necessary models to download
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth
 21%|████████▏                              | 187M/890M [01:34<05:29, 2.24MiB/s]
4. Ctrl+C or other mean to stop docker compose.
5. Remove container with docker compose rm
6. docker compose --profile=auto up # spin up everything once again
7. Repeat steps from 1 and see file being downloaded again despite having it in cache/torch/hub/checkpoints/ directory which is mounted as volume &v1.

**Hardware / Software:**
Does not matter

**Additional context**
N/A

**Comment by AbdBarho** [comment]
It seems that this problem was a bug in the latest transformers version, I downgraded.

can you try again from latest master? Unfortunately, you are going to have to re-download the entire cache.

**Comment by DevilaN** [comment]
After pulling latest version I can confirm, that it redownloaded everything, but still same effect.
Take a look onto full log with my comments, so you can easily reproduce it by yourself.
[error.txt](https://github.com/AbdBarho/stable-diffusion-webui-docker/files/9636299/error.txt)

**Comment by AbdBarho** [comment]
Just to summarize my findings:
* the logs in the console are misleading, the model that gets re-downloaded again is clip vit, not `model_base_caption_capfilt_large.pth`
* the cache folder defaults to `~/.cache` which is not mounted in the container [link](https://github.com/openai/CLIP/blob/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1/clip/clip.py#L94)
* the calling function does not provide another default location [link](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/410bef0853b61771729dd30f2f2df7a2906a1d4a/modules/interrogate.py#L55)

I have now hacked the solution in, ideally, CLIP and others should define some env variable which determines the caching location.

@DevilaN can you try again from latest master? you will have to download the 800mb one last time (hopefully 😅), if you want to, you can manually download the [file](https://github.com/openai/CLIP/blob/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1/clip/clip.py#L38) and save it under `cache/weights/ViT-L-14.pt`

**Comment by DevilaN** [comment]
Fixed! :)
Thank you very much!
