### ISSUE TITLE
Automatic1111 docker image throwing error when upscaling using Gfp-gan in extras

### ISSUE THREAD

**Issue by Marcus-Arcadius** [AbdBarho/stable-diffusion-webui-docker#89]
![image](https://user-images.githubusercontent.com/78793842/191952257-39e9e1d2-b9eb-4368-b950-759b5d2c6794.png)

**Comment by AbdBarho** [comment]
Should be fixed now, can you try again from latest master?

**Comment by Marcus-Arcadius** [comment]
@AbdBarho Just tested it out and it's now working!
