### ISSUE TITLE
Output is a green image

### ISSUE THREAD

**Issue by kittyinc** [AbdBarho/stable-diffusion-webui-docker#9]
Specs:

CPU: Ryzen 3600
RAM : 16 GB
GPU: 1660 Super 6GB

- Running through WSL2 docker backend.
- CUDA works inside docker (checked with nvidia-smi docker image)
- Tried lowering resolution to 64x64 , closed all GPU accelerated programs.
- Tried running with default args
- Tried with --precision full and --precision full + default args:

Output for --precision full in both cases:
```
!!Runtime error (txt2img)!!
   expected scalar type Half but found Float
exiting...calling os._exit(0)
```

**Comment by AbdBarho** [comment]
@kittyinc is this related to your issue ? https://github.com/hlky/stable-diffusion-webui/issues/34

**Comment by kittyinc** [comment]
@AbdBarho yes, sorry if I created this issue in the wrong repo, I swear I searched everywhere haha.

I'll continue the discussion there, thanks!

**Comment by AbdBarho** [comment]
No problem!

I will leave this issue open in the mean time, perhaps someone else has the same problem.

**Comment by bx00000013** [comment]
To get it to work on my 1660 Super I had to edit the docker-compose.yml file and change the CLI_ARGS to --extra-models-cpu --optimized --precision full --no-half

**Comment by AbdBarho** [comment]
That's great news @bx00000013!, @kittyinc can you please try the suggestion to see if it solves your problem?

**Comment by kittyinc** [comment]
@AbdBarho I can confirm that this solves the problem.

I think it has to do with the 16XX series lacking tensor cores, I think that the --precission full --no-half flags force this to run in FP16
