### ISSUE TITLE
Potential Enhancement - AUTOMATIC1111 and Textual Inversion

### ISSUE THREAD

**Issue by rgriffogoes** [AbdBarho/stable-diffusion-webui-docker#93]
I wasn't able to find in the docs, but is there an official way to include pretrained embeddings for auto profile?

I saw that I could just add the files in a embeddings folder, so I changed my docker compose to mount a volume in the container. That way I can easily add embeddings.

In the logs I see:

> webui-docker-automatic1111-1  | Loaded a total of 1 text inversion embeddings

So I guess it is working.

If there are no current way of doing, I could open a PR with this for other to use it.

**Comment by AbdBarho** [comment]
@rgriffogoes That would be wonderful! I was too lazy to add it because no one requested it yet 😅

**Comment by AbdBarho** [comment]
Closed in #98
