### ISSUE TITLE
auto Interrogate broken, downloads a ~1Gb file each time clicked

### ISSUE THREAD

**Issue by darkskiez** [AbdBarho/stable-diffusion-webui-docker#94]
When i click img2img interrogate it downloads a big file, surely this should be downloaded by the download profile option?

webui-docker-automatic1111-1  | load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth
100%|███████████████████████████████████████| 890M/890M [01:30<00:00, 10.3MiB/s]

I think this happens multiple times too.

**Comment by AbdBarho** [comment]
duplicate of #88, currently working on it!!!!!

**Comment by AbdBarho** [comment]
is merged now, can you try again from latest master?

**Comment by darkskiez** [comment]
Seems to still download after each container restart.

**Comment by darkskiez** [comment]
hmm maybe not, but i'll have to check again later.

**Comment by AbdBarho** [comment]
feel free to re-open if the problem is no fixed.
